### ISSUE TITLE
TEC fitting SVD did not converge

### ISSUE THREAD

**Issue by tikk3r** [mhardcastle/ddf-pipeline#101]
On my dataset the pipeline fails on TEC fitting with the following message
``` - 14:34:16 - AsyncProcessPool          | [comp11] process comp11: exception raised processing job FitThisTEC_173: Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Other/AsyncProcessPool.py", line 850, in _dispatch_job
    result = call(*args, **kwargs)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/SmoothSols.py", line 309, in FitThisTEC
    gz,TEC,CPhase=self.FitThisTECTime(it,iDir,Est=Est)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/SmoothSols.py", line 347, in FitThisTECTime
    X=TECMachine.doFit()
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/Other/ClassFitTEC.py", line 94, in doFit
    self.doLMIter()
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/Other/ClassFitTEC.py", line 123, in doLMIter
    Hinv=killMS.Array.ModLinAlg.invSVD(H)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/Array/ModLinAlg.py", line 216, in invSVD
    u,s,v=np.linalg.svd(np.complex128(A))#+np.random.randn(*A.shape)*(1e-6*A.max()))
  File "/net/para11/data2/sweijen/software/env-losoto2-para/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1444, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/net/para11/data2/sweijen/software/env-losoto2-para/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge
```
and then finally
```
 - 14:35:38 - AsyncProcessPool          | Fit TEC: 510 jobs complete, average single-core time 15.28s per job
 - 14:35:38 - AsyncProcessPool          | FitThisTEC*: 1 jobs returned an error. Aborting.
```
It also sort-of hangs afterwards, needing a ctrl+c to be killed. What could be the cause? Is there a way to work around it? The data looks fine.

Frits

**Comment by mhardcastle** [comment]
I think this is one for @cyriltasse ...

**Comment by cyriltasse** [comment]
ok - it's weird... can you post somewhere the input solution file and the command line?

**Comment by tikk3r** [comment]
> ok - it's weird... can you post somewhere the input solution file and the command line?

The command it runs is

    Running: SmoothSols.py --SolsFileIn=DDS0_4960034163.005561_merged.npz --SolsFileOut=DDS0_4960034163.005561_smoothed.npz --InterpMode=TEC,PolyAmp

Job 147/510 then throws this error. The file is here: https://surfdrive.surf.nl/files/index.php/s/h9mQqoyPhSDgNQa

**Comment by tikk3r** [comment]
> on which kMS branch are you ?

I asked @twshimwell , we're on MergeDDFMaster.

**Comment by cyriltasse** [comment]
i've updated `MergeDDFMAster_FixEvP` which is the branch i had done the modifications on for you to test (fixing NChanSol problem, among a few more things - so i'd like to be sure i did not break anythinhg before merging to my active branch)

**Comment by mhardcastle** [comment]
Do you think we should all be using this branch for production?

**Comment by cyriltasse** [comment]
i would have liked them to test it first, since i made it to fix the bug they had found beg july...

**Comment by mhardcastle** [comment]
OK

**Comment by tikk3r** [comment]
Alright, the fix seems to have done the trick. It gave a warning `Problem inverting Matrix, saving as errSVDArray_9263` and then went on with the rest of the pipeline. Thanks!



> i would have liked them to test it first, since i made it to fix the bug they had found beg july...

What bug is this? I'm not sure if I was related to it or maybe I need a little refresher.

**Comment by mhardcastle** [comment]
Cyril's talking about #81, which you were not involved with.

**Comment by tikk3r** [comment]
So it got past the SVD issue, but now it throws another error during "Another DI step" (images up to `image_ampphase1.app.restored.fits.mask.fits` have been made). The error is

    AttributeError: ClassWirtingerSolver instance has no attribute 'P'

It runs
```
kMS.py --MSName L427100_SB020_uv.dppp_127A41D72t_124MHz.pre-cal.avg.ms --SolverType KAFCA --PolMode Scalar --BaseImageName PredictDI_1 --dt 0.200000 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 32 --OutSolsName DIS1 --PowerSmooth=1.000000 --InCol SCALED_DATA --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIR --SolverType CohJones --PolMode IFull --SkyModelCol DD_PREDICT --OutCol DATA_DI_CORRECTED --ApplyToDir 0 --dt 0.934731 --NChanSols 4
```

**Comment by cyriltasse** [comment]
ok pull and try again?

**Comment by tikk3r** [comment]
> ok pull and try again?

No luck, now it just dies:
```
============================== Bootstrap =============================

Running bootstrap
Running: bootstrap.py tier1-apr2018.cfg
Running: CleanSHM.py
 - 15:47:23 - ClearSHM                  | Clear shared memory
 - 15:47:23 - ClearSHM                  | Clear Semaphores
 - 15:47:23 - ClearSHM                  | Clear shared dictionaries
 - 15:47:50 - ClearSHM                  | Clear shared memory
 - 15:47:50 - ClearSHM                  | Clear Semaphores
 - 15:47:50 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py tier1-apr2018.cfg: return value is -11
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1482, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 987, in main
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None,dryrun=o["dryrun"])
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py tier1-apr2018.cfg: return value is -11
```
The strange thing is there are already images like `ampphase1.int.restored.fits` so I don't know why it wants to do bootstrap again either. And there's a spurious `P.DDS1.npy` that I've never seen before.

**Comment by mhardcastle** [comment]
OK, that's a segmentation fault running bootstrap.py, which is nothing to do with the fix Cyril pushed. Could be an issue with ClearSHM doing something it shouldn't, or could mean that your machine is in a strange state, or...

(The bootstrap code gets run every time the pipeline gets to that stage; if it's been run already it will not actually do anything.)
