### ISSUE TITLE
Bootstrapping finds no crossmatch

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#102]
Hi,

The pipeline stopped with the message that there was no crossmatch found while bootstrapping. I use 4 catalogue that should cover the area. VLSS,NVSS,B2,WENSS.

I checked "external_mask.fits" and the catalogues in Aladin. WENSS does have sources that match up with sources in the mask fits file.  VLSS does have sources but they are always slightly offset.

How can it be that it is not finding anything? And also, can I just continue without bootstrapping, and apply this at the end?

**Comment by mhardcastle** [comment]
No, you need to bootstrap at the point where the code does it, to get in-band spectral corrections.

Please post the exact error message and the bootstrap part of your config file...

**Comment by amisk** [comment]
The last thing I tried, altough I'm not sure if the pipeline just uses the new additions. Before that, only WENNS and VLSS were in there, with radii of 40,10.:

[bootstrap]
catalogues=['/home/amisk/work/N3432/boot/VLSS.fits','/home/amisk/work/N3432/boot/wenss.fits','/home/amisk/work/N3432/boot/B2.fits','/home/amisk/work/N3432/boot/NVSS.fits']
names=['VLSS','WENSS','B2','NVSS']
radii=[40,40,40,40]
frequencies=[74e6,327e6,408e6,1400e6]

And the error:

> Running bootstrap for obsid 146MHz.ms
> 146MHz.ms 146971130.371
> File image_bootstrap_146MHz.ms.app.restored.fits already exists, skipping DDF step
> Source list exists, skipping source extraction
> Total table length is 1151
> Filtered within 2.5 degrees: 684  
> Bright sources: 58
> Remove close neighbours: 52
> Table VLSS has 47 entries
> Table WENSS has 453 entries
> Table B2 has 35 entries
> Table NVSS has 1003 entries
> Traceback (most recent call last):
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/bootstrap.py", line 202, in <module>
>     run_bootstrap(o)
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/bootstrap.py", line 118, in run_bootstrap
>     make_catalogue('image_bootstrap_'+obsid+'.cube.int.restored.pybdsm.srl',ra,dec,2.5,cats,outnameprefix=obsid)
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/make_fitting_product.py", line 66, in make_catalogue
>     raise RuntimeError('No crossmatches exist after group matching')
> RuntimeError: No crossmatches exist after group matching
>  - 10:05:47 - ClearSHM                  | Clear shared memory
>  - 10:05:47 - ClearSHM                  | Clear Semaphores
>  - 10:05:47 - ClearSHM                  | Clear shared dictionaries
> FAILED to run bootstrap.py N3432.cfg: return value is 1
> Traceback (most recent call last):
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/pipeline.py", line 508, in <module>
>     run('bootstrap.py '+' '.join(sys.argv[1:]),log=None)
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/auxcodes.py", line 45, in run
>     die('FAILED to run '+s+': return value is '+str(retval))
>   File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/auxcodes.py", line 27, in die
>     raise Exception(s)
> Exception: FAILED to run bootstrap.py N3432.cfg: return value is 1
>

**Comment by mhardcastle** [comment]
OK, well, that config file requires matches in all four catalogues and I guess it's just possible that they are not present (though a bit surprising). As the bootstrap web page says, I wouldn't use NVSS if you have WENSS, and you only need one match above the LOFAR band. So try:

```
[bootstrap]
catalogues=['/home/amisk/work/N3432/boot/VLSS.fits','/home/amisk/work/N3432/boot/wenss.fits','/home/amisk/work/N3432/boot/B2.fits']
names=['VLSS','WENSS','B2']
radii=[40,40,40]
frequencies=[74e6,327e6,408e6]
groups=[1,2,2]
```
That will require a match in VLSS, plus either a match in WENSS or one in B2. If that doesn't work, then something is definitely wrong...

**Comment by amisk** [comment]
I get some error about index 4 beeing to large for array with size 3. This might be the result of my tring to continue without bootstrapping.
Which option do I need for the redofrom option to get back right before bootstrapping?

**Comment by amisk** [comment]
I restarted from "dirin". This might take a while ...

**Comment by amisk** [comment]
Still not working.
```
--> Extracting spectral indices for all ch0 sources
WARNING: Image has only one channel. Spectral index module disabled.
--> Wrote ASCII file 'image_bootstrap_146MHz.ms.cube.int.restored.pybdsm.srl'
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead.
--> Wrote file 'image_bootstrap_146MHz.ms.cube.int.restored.pybdsm_rms.fits'
Total table length is 1149
Filtered within 2.5 degrees: 677  
Bright sources: 55
Remove close neighbours: 51
Table VLSS has 47 entries
Table WENSS has 453 entries
Traceback (most recent call last):
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/bootstrap.py", line 202, in <module>
    run_bootstrap(o)
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/bootstrap.py", line 118, in run_bootstrap
    make_catalogue('image_bootstrap_'+obsid+'.cube.int.restored.pybdsm.srl',ra,dec,2.5,cats,outnameprefix=obsid)
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/make_fitting_product.py", line 66, in make_catalogue
    raise RuntimeError('No crossmatches exist after group matching')
RuntimeError: No crossmatches exist after group matching
 - 21:13:52 - ClearSHM                  | Clear shared memory
 - 21:13:52 - ClearSHM                  | Clear Semaphores
 - 21:13:52 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py N3432.cfg: return value is 1
Traceback (most recent call last):
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/scripts/pipeline.py", line 508, in <module>
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None)
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/auxcodes.py", line 45, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/soft/lofar-stuff/DDF/ddf-pipeline/utils/auxcodes.py", line 27, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py N3432.cfg: return value is 1

```

**Comment by twshimwell** [comment]
What does your bootstrap image look like out of interest? The *boostrap*app.restored.fits

**Comment by mhardcastle** [comment]
So I don't know if this issue is still open, but I do notice that the code seems to be being run on a single MS, which will almost certainly not work -- it's never been tested. See the error messages about the cube only having one channel? Is this what you're intending?

**Comment by amisk** [comment]
It never happened since ... I guess it can be closed.
