### ISSUE TITLE
 ddf-pipeline running error

### ISSUE THREAD

**Issue by pommierm** [mhardcastle/ddf-pipeline#107]
When I run the pipeline:

pipeline.py tier1-DR2-NVSS.cfg

I get following error:

Running: MakeCatalog.py --RestoredIm image_dirin_SSD_m.app.restored.fits --rmsmean_map [Noise.mean.fits,Noise.fits]
 - 13:37:49 - MakeCatalog               | File image_dirin_SSD_m.app.restored.fits exist
 - 13:37:49 - MakeCatalog               | File image_dirin_SSD_m.app.restored.pybdsm.gaul.fits exists
 - 13:37:49 - MakeCatalog               |    Skipping...
Running: ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45
/home/mamta/.local/lib/python2.7/site-packages/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
 - 13:37:56 - ClusterImage              | Reading image_dirin_SSD_m.app.restored.pybdsm.srl.fits
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/SkyModel/ClusterCat.py", line 307, in <module>
    main(options=options)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/SkyModel/ClusterCat.py", line 296, in main
    CIM=ClusterImage(**options.__dict__)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/SkyModel/ClusterCat.py", line 70, in __init__
    decc,rac=f[1].header["I_CRVAL1"],f[1].header["I_CRVAL2"]
  File "/home/mamta/.local/lib/python2.7/site-packages/pyfits/header.py", line 127, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/mamta/.local/lib/python2.7/site-packages/pyfits/header.py", line 1561, in _cardindex
    raise KeyError("Keyword %r not found." % keyword)
KeyError: "Keyword 'I_CRVAL1' not found."
 - 13:37:59 - ClearSHM                  | Clear shared memory
 - 13:37:59 - ClearSHM                  | Clear Semaphores
 - 13:37:59 - ClearSHM                  | Clear shared dictionaries
FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1482, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 873, in main
    use_makemask_products=True)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 341, in clusterGA
    run(runcommand,dryrun=options['dryrun'],log=logfilename('MakeCluster-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1

Thanks,
Mamta

**Comment by twshimwell** [comment]
Doesnt seem to be pyfits, astropy or pybsf. 

The image_dirin_SSD_m.app.restored.pybdsm.srl.fits I can open in topcat and it seems normal with ~1000 entries.

**Comment by mhardcastle** [comment]
The actual error is the `KeyError: "Keyword 'I_CRVAL1' not found."`. 

Is the version of pybdsf the latest version, pulled from github?

**Comment by twshimwell** [comment]
Its the same version as I use.

**Comment by twshimwell** [comment]
The header of the image_dirin_SSD_m.app.restored.pybdsm.srl.fits file:

In [3]: f[1].header
Out[3]: 
XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  345 / length of dimension 1                          
NAXIS2  =                 1046 / length of dimension 2                          
PCOUNT  =                    0 / number of group parameters                     
GCOUNT  =                    1 / number of groups                               
TFIELDS =                   45 / number of table fields                         
TTYPE1  = 'Source_id'                                                           
TFORM1  = 'J       '                                                            
TUNIT1  = ''                                                                    
TTYPE2  = 'Isl_id  '                                                            
TFORM2  = 'J       '                                                            
TUNIT2  = ''                                                                    
TTYPE3  = 'RA      '                                                            
TFORM3  = 'D       '                                                            
TUNIT3  = 'deg     '                                                            
TTYPE4  = 'E_RA    '                                                            
TFORM4  = 'D       '                                                            
TUNIT4  = 'deg     '                                                            
TTYPE5  = 'DEC     '                                                            
TFORM5  = 'D       '                                                            
TUNIT5  = 'deg     '                                                            
TTYPE6  = 'E_DEC   '                                                            
TFORM6  = 'D       '                                                            
TUNIT6  = 'deg     '                                                            
TTYPE7  = 'Total_flux'                                                          
TFORM7  = 'D       '                                                            
TUNIT7  = 'Jy      '                                                            
TTYPE8  = 'E_Total_flux'                                                        
TFORM8  = 'D       '                                                            
TUNIT8  = 'Jy      '                                                            
TTYPE9  = 'Peak_flux'                                                           
TFORM9  = 'D       '                                                            
TUNIT9  = 'Jy/beam '                                                            
TTYPE10 = 'E_Peak_flux'                                                         
TFORM10 = 'D       '                                                            
TUNIT10 = 'Jy/beam '                                                            
TTYPE11 = 'RA_max  '                                                            
TFORM11 = 'D       '                                                            
TUNIT11 = 'deg     '                                                            
TTYPE12 = 'E_RA_max'                                                            
TFORM12 = 'D       '                                                            
TUNIT12 = 'deg     '                                                            
TTYPE13 = 'DEC_max '                                                            
TFORM13 = 'D       '                                                            
TUNIT13 = 'deg     '                                                            
TTYPE14 = 'E_DEC_max'                                                           
TFORM14 = 'D       '                                                            
TUNIT14 = 'deg     '                                                            
TTYPE15 = 'Maj     '                                                            
TFORM15 = 'D       '                                                            
TUNIT15 = 'deg     '                                                            
TTYPE16 = 'E_Maj   '                                                            
TFORM16 = 'D       '                                                            
TUNIT16 = 'deg     '                                                            
TTYPE17 = 'Min     '                                                            
TFORM17 = 'D       '                                                            
TUNIT17 = 'deg     '                                                            
TTYPE18 = 'E_Min   '                                                            
TFORM18 = 'D       '                                                            
TUNIT18 = 'deg     '                                                            
TTYPE19 = 'PA      '                                                            
TFORM19 = 'D       '                                                            
TUNIT19 = 'deg     '                                                            
TTYPE20 = 'E_PA    '                                                            
TFORM20 = 'D       '                                                            
TUNIT20 = 'deg     '                                                            
TTYPE21 = 'Maj_img_plane'                                                       
TFORM21 = 'D       '                                                            
TUNIT21 = 'deg     '                                                            
TTYPE22 = 'E_Maj_img_plane'                                                     
TFORM22 = 'D       '                                                            
TUNIT22 = 'deg     '                                                            
TTYPE23 = 'Min_img_plane'                                                       
TFORM23 = 'D       '                                                            
TUNIT23 = 'deg     '                                                            
TTYPE24 = 'E_Min_img_plane'                                                     
TFORM24 = 'D       '                                                            
TUNIT24 = 'deg     '                                                            
TTYPE25 = 'PA_img_plane'                                                        
TFORM25 = 'D       '                                                            
TUNIT25 = 'deg     '                                                            
TTYPE26 = 'E_PA_img_plane'                                                      
TFORM26 = 'D       '                                                            
TUNIT26 = 'deg     '                                                            
TTYPE27 = 'DC_Maj  '                                                            
TFORM27 = 'D       '                                                            
TUNIT27 = 'deg     '                                                            
TTYPE28 = 'E_DC_Maj'                                                            
TFORM28 = 'D       '                                                            
TUNIT28 = 'deg     '                                                            
TTYPE29 = 'DC_Min  '                                                            
TFORM29 = 'D       '                                                            
TUNIT29 = 'deg     '                                                            
TTYPE30 = 'E_DC_Min'                                                            
TFORM30 = 'D       '                                                            
TUNIT30 = 'deg     '                                                            
TTYPE31 = 'DC_PA   '                                                            
TFORM31 = 'D       '                                                            
TUNIT31 = 'deg     '                                                            
TTYPE32 = 'E_DC_PA '                                                            
TFORM32 = 'D       '                                                            
TUNIT32 = 'deg     '                                                            
TTYPE33 = 'DC_Maj_img_plane'                                                    
TFORM33 = 'D       '                                                            
TUNIT33 = 'deg     '                                                            
TTYPE34 = 'E_DC_Maj_img_plane'                                                  
TFORM34 = 'D       '                                                            
TUNIT34 = 'deg     '                                                            
TTYPE35 = 'DC_Min_img_plane'                                                    
TFORM35 = 'D       '                                                            
TUNIT35 = 'deg     '                                                            
TTYPE36 = 'E_DC_Min_img_plane'                                                  
TFORM36 = 'D       '                                                            
TUNIT36 = 'deg     '                                                            
TTYPE37 = 'DC_PA_img_plane'                                                     
TFORM37 = 'D       '                                                            
TUNIT37 = 'deg     '                                                            
TTYPE38 = 'E_DC_PA_img_plane'                                                   
TFORM38 = 'D       '                                                            
TUNIT38 = 'deg     '                                                            
TTYPE39 = 'Isl_Total_flux'                                                      
TFORM39 = 'D       '                                                            
TUNIT39 = 'Jy      '                                                            
TTYPE40 = 'E_Isl_Total_flux'                                                    
TFORM40 = 'D       '                                                            
TUNIT40 = 'Jy      '                                                            
TTYPE41 = 'Isl_rms '                                                            
TFORM41 = 'D       '                                                            
TUNIT41 = 'Jy/beam '                                                            
TTYPE42 = 'Isl_mean'                                                            
TFORM42 = 'D       '                                                            
TUNIT42 = 'Jy/beam '                                                            
TTYPE43 = 'Resid_Isl_rms'                                                       
TFORM43 = 'D       '                                                            
TUNIT43 = 'Jy/beam '                                                            
TTYPE44 = 'Resid_Isl_mean'                                                      
TFORM44 = 'D       '                                                            
TUNIT44 = 'Jy/beam '                                                            
TTYPE45 = 'S_Code  '                                                            
TFORM45 = 'A       '                                                            
TUNIT45 = ''                                                                    
INIMAGE = 'image_dirin_SSD_m.app.restored.fits' / Filename of image             
FREQ0   =          144627000.0 / Reference frequency                            
EQUINOX =               2000.0 / Equinox                                        
COMMENT Source list for image_dirin_SSD_m.app.restored.fits                     
COMMENT Generated by PyBDSM version 1.8.13                                      
COMMENT Reference frequency of the detection ("ch0") image: 1.44627e+08 Hz      
COMMENT Equinox : 2000.0

**Comment by cyriltasse** [comment]
ho yeah good point @mhardcastle - this is probably not the latest `pybdsf`

**Comment by twshimwell** [comment]
OK ive now updated it to 1.8.14. You want to try again Mamta? Dont forget to remove all the existing *pybds* files before starting it up again.

**Comment by pommierm** [comment]
File "/net/para10/data1/shimwell/software/killmsddf/new-install//DDFacet/SkyModel/ClusterCat.py", line 70, in __init__
    decc,rac=f[1].header["I_CRVAL1"],f[1].header["I_CRVAL2"]
  File "/home/mamta/.local/lib/python2.7/site-packages/pyfits/header.py", line 127, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/mamta/.local/lib/python2.7/site-packages/pyfits/header.py", line 1561, in _cardindex
    raise KeyError("Keyword %r not found." % keyword)
KeyError: "Keyword 'I_CRVAL1' not found."
 - 18:01:00 - ClearSHM                  | Clear shared memory
 - 18:01:00 - ClearSHM                  | Clear Semaphores
 - 18:01:00 - ClearSHM                  | Clear shared dictionaries
FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1482, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 873, in main
    use_makemask_products=True)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 341, in clusterGA
    run(runcommand,dryrun=options['dryrun'],log=logfilename('MakeCluster-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1

**Comment by pommierm** [comment]
After update and removing existing files with pybds, the error message (above) still continues

**Comment by mhardcastle** [comment]
OK, well, those keywords are put in there by pybdsf. They are clearly not there in the FITS header posted by Tim, but they should be:

```
In [1]: from astropy.io import fits

In [2]: f=fits.open('image_dirin_SSD_m.app.restored.pybdsm.srl.fits')

In [3]: f[1].header
Out[3]: 
XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  345 / length of dimension 1                          
NAXIS2  =                 1236 / length of dimension 2                          
PCOUNT  =                    0 / number of group parameters                     
GCOUNT  =                    1 / number of groups                               
TFIELDS =                   45 / number of table fields                         
TTYPE1  = 'Source_id'                                                           
TFORM1  = 'J       '                                                            
TUNIT1  = ''                                                                    
TTYPE2  = 'Isl_id  '                                                            
TFORM2  = 'J       '                                                            
TUNIT2  = ''                                                                    
TTYPE3  = 'RA      '                                                            
TFORM3  = 'D       '                                                            
TUNIT3  = 'deg     '                                                            
TTYPE4  = 'E_RA    '                                                            
TFORM4  = 'D       '                                                            
TUNIT4  = 'deg     '                                                            
TTYPE5  = 'DEC     '                                                            
TFORM5  = 'D       '                                                            
TUNIT5  = 'deg     '                                                            
TTYPE6  = 'E_DEC   '                                                            
TFORM6  = 'D       '                                                            
TUNIT6  = 'deg     '                                                            
TTYPE7  = 'Total_flux'                                                          
TFORM7  = 'D       '                                                            
TUNIT7  = 'Jy      '                                                            
TTYPE8  = 'E_Total_flux'                                                        
TFORM8  = 'D       '                                                            
TUNIT8  = 'Jy      '                                                            
TTYPE9  = 'Peak_flux'                                                           
TFORM9  = 'D       '                                                            
TUNIT9  = 'Jy/beam '                                                            
TTYPE10 = 'E_Peak_flux'                                                         
TFORM10 = 'D       '                                                            
TUNIT10 = 'Jy/beam '                                                            
TTYPE11 = 'RA_max  '                                                            
TFORM11 = 'D       '                                                            
TUNIT11 = 'deg     '                                                            
TTYPE12 = 'E_RA_max'                                                            
TFORM12 = 'D       '                                                            
TUNIT12 = 'deg     '                                                            
TTYPE13 = 'DEC_max '                                                            
TFORM13 = 'D       '                                                            
TUNIT13 = 'deg     '                                                            
TTYPE14 = 'E_DEC_max'                                                           
TFORM14 = 'D       '                                                            
TUNIT14 = 'deg     '                                                            
TTYPE15 = 'Maj     '                                                            
TFORM15 = 'D       '                                                            
TUNIT15 = 'deg     '                                                            
TTYPE16 = 'E_Maj   '                                                            
TFORM16 = 'D       '                                                            
TUNIT16 = 'deg     '                                                            
TTYPE17 = 'Min     '                                                            
TFORM17 = 'D       '                                                            
TUNIT17 = 'deg     '                                                            
TTYPE18 = 'E_Min   '                                                            
TFORM18 = 'D       '                                                            
TUNIT18 = 'deg     '                                                            
TTYPE19 = 'PA      '                                                            
TFORM19 = 'D       '                                                            
TUNIT19 = 'deg     '                                                            
TTYPE20 = 'E_PA    '                                                            
TFORM20 = 'D       '                                                            
TUNIT20 = 'deg     '                                                            
TTYPE21 = 'Maj_img_plane'                                                       
TFORM21 = 'D       '                                                            
TUNIT21 = 'deg     '                                                            
TTYPE22 = 'E_Maj_img_plane'                                                     
TFORM22 = 'D       '                                                            
TUNIT22 = 'deg     '                                                            
TTYPE23 = 'Min_img_plane'                                                       
TFORM23 = 'D       '                                                            
TUNIT23 = 'deg     '                                                            
TTYPE24 = 'E_Min_img_plane'                                                     
TFORM24 = 'D       '                                                            
TUNIT24 = 'deg     '                                                            
TTYPE25 = 'PA_img_plane'                                                        
TFORM25 = 'D       '                                                            
TUNIT25 = 'deg     '                                                            
TTYPE26 = 'E_PA_img_plane'                                                      
TFORM26 = 'D       '                                                            
TUNIT26 = 'deg     '                                                            
TTYPE27 = 'DC_Maj  '                                                            
TFORM27 = 'D       '                                                            
TUNIT27 = 'deg     '                                                            
TTYPE28 = 'E_DC_Maj'                                                            
TFORM28 = 'D       '                                                            
TUNIT28 = 'deg     '                                                            
TTYPE29 = 'DC_Min  '                                                            
TFORM29 = 'D       '                                                            
TUNIT29 = 'deg     '                                                            
TTYPE30 = 'E_DC_Min'                                                            
TFORM30 = 'D       '                                                            
TUNIT30 = 'deg     '                                                            
TTYPE31 = 'DC_PA   '                                                            
TFORM31 = 'D       '                                                            
TUNIT31 = 'deg     '                                                            
TTYPE32 = 'E_DC_PA '                                                            
TFORM32 = 'D       '                                                            
TUNIT32 = 'deg     '                                                            
TTYPE33 = 'DC_Maj_img_plane'                                                    
TFORM33 = 'D       '                                                            
TUNIT33 = 'deg     '                                                            
TTYPE34 = 'E_DC_Maj_img_plane'                                                  
TFORM34 = 'D       '                                                            
TUNIT34 = 'deg     '                                                            
TTYPE35 = 'DC_Min_img_plane'                                                    
TFORM35 = 'D       '                                                            
TUNIT35 = 'deg     '                                                            
TTYPE36 = 'E_DC_Min_img_plane'                                                  
TFORM36 = 'D       '                                                            
TUNIT36 = 'deg     '                                                            
TTYPE37 = 'DC_PA_img_plane'                                                     
TFORM37 = 'D       '                                                            
TUNIT37 = 'deg     '                                                            
TTYPE38 = 'E_DC_PA_img_plane'                                                   
TFORM38 = 'D       '                                                            
TUNIT38 = 'deg     '                                                            
TTYPE39 = 'Isl_Total_flux'                                                      
TFORM39 = 'D       '                                                            
TUNIT39 = 'Jy      '                                                            
TTYPE40 = 'E_Isl_Total_flux'                                                    
TFORM40 = 'D       '                                                            
TUNIT40 = 'Jy      '                                                            
TTYPE41 = 'Isl_rms '                                                            
TFORM41 = 'D       '                                                            
TUNIT41 = 'Jy/beam '                                                            
TTYPE42 = 'Isl_mean'                                                            
TFORM42 = 'D       '                                                            
TUNIT42 = 'Jy/beam '                                                            
TTYPE43 = 'Resid_Isl_rms'                                                       
TFORM43 = 'D       '                                                            
TUNIT43 = 'Jy/beam '                                                            
TTYPE44 = 'Resid_Isl_mean'                                                      
TFORM44 = 'D       '                                                            
TUNIT44 = 'Jy/beam '                                                            
TTYPE45 = 'S_Code  '                                                            
TFORM45 = 'A       '                                                            
TUNIT45 = ''                                                                    
INIMAGE = 'image_dirin_SSD_m.app.restored.fits' / Filename of image             
FREQ0   =          142674000.0 / Reference frequency                            
EQUINOX =               2000.0 / Equinox                                        
I_SIMPLE=                    T                                                  
I_BITPIX=                  -32                                                  
I_NAXIS =                    4                                                  
I_NAXIS1=                19845                                                  
I_NAXIS2=                19845                                                  
I_NAXIS3=                    1                                                  
I_NAXIS4=                    1                                                  
HIERARCH I_WCSAXES = 4                                                          
I_CRPIX1=               9923.0                                                  
I_CRPIX2=               9923.0                                                  
I_CRPIX3=                  1.0                                                  
I_CRPIX4=                  1.0                                                  
I_CDELT1= -0.00041666666666667                                                  
I_CDELT2=  0.00041666666666667                                                  
I_CDELT3=                  1.0                                                  
I_CDELT4=                  1.0                                                  
I_CUNIT1= 'deg     '                                                            
I_CUNIT2= 'deg     '                                                            
I_CUNIT4= 'Hz      '                                                            
I_CTYPE1= 'RA---SIN'                                                            
I_CTYPE2= 'DEC--SIN'                                                            
I_CTYPE3= 'STOKES  '                                                            
I_CTYPE4= 'FREQ    '                                                            
I_CRVAL1=            170.43705                                                  
I_CRVAL2=             49.74803                                                  
I_CRVAL3=                  1.0                                                  
I_CRVAL4=      142674255.37109                                                  
HIERARCH I_LONPOLE = 180.0                                                      
HIERARCH I_LATPOLE = 49.74803                                                   
HIERARCH I_RADESYS = 'ICRS    '                                                 
HIERARCH I_RESTFRQ = 142674255.3710938                                          
I_ORIGIN= 'DDFacet dev-8f10857'                                                 
I_BTYPE = 'Intensity'                                                           
I_BUNIT = 'Jy/beam '                                                            
HIERARCH I_SPECSYS = 'TOPOCENT'                                                 
I_OBJECT= 'P10Hetdex'                                                           
HIERARCH I_DATE-OBS = '2014-05-23'                                              
HIERARCH I_TELESCOP = 'LOFAR   '                                                
HIERARCH I_OBSERVER = 'unknown '                                                
HIERARCH I_DATE-MAP = '2018-07-04'                                              
I_BMAJ  = 0.003333333333333334                                                  
I_BMIN  = 0.003333333333333334                                                  
I_BPA   =                   90                                                  
COMMENT Source list for image_dirin_SSD_m.app.restored.fits                     
COMMENT Generated by PyBDSM version 1.8.13                                      
COMMENT Reference frequency of the detection ("ch0") image: 1.42674e+08 Hz      
COMMENT Equinox : 2000.0                                                        
```

The bit of the code in pybdsf (output.py) that adds the image headers is right next to the part that adds the COMMENTs, which are there in your header. You can't have one without the other in the current version of the code. That code was added by @cyriltasse  (and bugfixed by @wllwen007 ) a few months ago and is needed for ClusterCat to run. My guess is still that a wrong version of PyBDSF is being used. In the session where you're running the pipeline, do
```
import bdsf
print bdsf.__path__
```

Then check output.py in that directory for the lines
```
    for key in img.header.keys():
        if key in ['HISTORY','COMMENT','']: continue
        tbhdu.header['I_%s'%key]=img.header[key]
```

**Comment by mhardcastle** [comment]
(I have pushed a change to ClusterCat.py to replace the deprecated and obsolete pyfits import with astropy, just in case that's the problem, but I doubt it.)

**Comment by pommierm** [comment]
After installing pybdsf  v1.8.14 , it worked.

Thank you
