### ISSUE TITLE
issue with pybdsf

### ISSUE THREAD

**Issue by agwilber** [mhardcastle/ddf-pipeline#108]
The pipeline is stuck on a pybdsf task, fitting gaussians to islands. Islands are found but then the pipeline stays at this step indefinitely. I don't know if this is an issue for the DDF pipeline creators / users, but I am not sure what I can do to fix this. I tried on two separate fields and the pipeline gets stuck at the same point. Anyone seen this before? 

============================== Cluster the sky model =============================

Running: MakeCatalog.py --RestoredIm image_dirin_SSD_m.app.restored.fits --rmsmean_map [Noise.mean.fits,Noise.fits]
 - 14:51:01 - MakeCatalog               | File image_dirin_SSD_m.app.restored.fits exist
--> Opened 'image_dirin_SSD_m.app.restored.fits'
Image size .............................. : (19845, 19845) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (3.33333e-03, 3.33333e-03, 90.0) degrees
Frequency of image ...................... : 144.627 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 102.907 Jy
--> Calculating background rms and mean images
--> Skipping mean and rms image computation
-->    Openning mean image: Noise.mean.fits
--> Opened 'Noise.mean.fits'
-->    Openning rms image: Noise.fits
--> Opened 'Noise.fits'
--> Variation in rms image significant
--> Using 2D map for background rms
--> Variation in mean image not significant
--> Using constant background mean
Min/max values of background rms map .... : (0.00030, 0.01912) Jy/beam
Value of background mean ................ : -1e-05 Jy/beam
--> Expected 5-sigma-clipped false detection rate < fdr_ratio
--> Using sigma-clipping ('hard') thresholding
Minimum number of pixels per island ..... : 24
Number of islands found ................. : 1583

**Comment by cyriltasse** [comment]
Hey it seems it's that issue here https://github.com/lofar-astron/PyBDSF/issues/63

**Comment by cyriltasse** [comment]
4days! Wha - some heavy math must be going on! however my experience is that there was 0% CPU usage...

**Comment by mhardcastle** [comment]
I only noticed this when a run started to take longer than the 4-5 days that they normally take here, so I don't know whether there was any CPU usage at the time. But it's a weird bug anyway. I don't really have time to dig into the insides of pybsdf, though I have done in the past...

**Comment by agwilber** [comment]
Yeah it looks like my CPU are chilled out right now, like nothing is going on.

**Comment by agwilber** [comment]
Yes, MakeCatalog.py is at 0% CPU usage

**Comment by agwilber** [comment]
This issue is now fixed in PYBDSF ... pipeline is running past the point of finding islands now, hooray!

https://github.com/lofar-astron/PyBDSF/pull/78/commits/af7057281d40963d669dff53a116e279157e0ec5
