### ISSUE TITLE
MakeCatalog.py results in segmentation fault

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#111]
Hey,

We tried to run the pipeline on another dataset. When MakeCatalog.py is run, it crashes with a segmentation fault.

```
Running process with command: MakeCatalog.py --RestoredIm image_dirin_SSD_m.app.restored.fits --rmsmean_map [Noise.mean.fits,Noise.fits]
2018-10-05 01:40:00:  - 01:40:00 - MakeCatalog               | ESC[1mESC[92mFile image_dirin_SSD_m.app.restored.fits existESC[0mESC[0m
2018-10-05 01:40:00: ESC[1;34m--> Opened 'image_dirin_SSD_m.app.restored.fits'ESC[0m
2018-10-05 01:40:32: Image size .............................. : (19845, 19845) pixels
2018-10-05 01:40:32: Number of channels ...................... : 1
2018-10-05 01:40:32: Number of Stokes parameters ............. : 1
2018-10-05 01:40:32: Beam shape (major, minor, pos angle) .... : (3.33333e-03, 3.33333e-03, 90.0) degrees
2018-10-05 01:40:32: Frequency of image ...................... : 144.627 MHz
2018-10-05 01:40:34: Number of blank pixels .................. : 0 (0.0%)
2018-10-05 01:41:08: Segmentation fault
Process terminated with return value 139
```

The fits file looks ok. The only thing I noticed is, that Noise.mean.fits is completely zero. 294 million pixels, all have the value 0. But maybe that is supposed to be like that.

**Comment by cyriltasse** [comment]
Hey this is a `pybdsf` issue https://github.com/lofar-astron/PyBDSF/issues/63

**Comment by amisk** [comment]
Hey...

I updated pybdsf, but I still get a segmentation fault.
Do I need to recompile the lofar software after installing the new pybdsf version?

**Comment by cyriltasse** [comment]
It is a pybdsf issue... To my knowledge the main `pybdsf` developer is working on it - can reproduce, but it's still unfixed. You should perhaps post your questions there...

**Comment by mhardcastle** [comment]
There is a PR on the pybdsf github that may fix it, if you check out that branch.

**Comment by amisk** [comment]
Sorry to comment here again, but this was probably not a pybdsf issue. We had this on 3 machines. One of them had the newest pybdsf version. Interestingly, it happened for my collegues user, but not for mine. We found the culprit, although I dont know where the connection is.
When we experimented we FACTOR, it would often crash with a a "too many open files" error. In order to solve it, we set the soft and hard file limits to unlimited using

```
ulimit -s unlimited
ulimit -Sn unlimited

```
This was done at a user level.
My collegue still had thin in his .bashrc. After removing it and logging in again, the segmentation fault in MakeCatalog.py did not appear again.
Maybe worth noting.

**Comment by cyriltasse** [comment]
Just to be 100% sure: it's been merged by David to master a few minutes ago... Previously it was in the commit

https://github.com/lofar-astron/PyBDSF/commit/50075521349467780b538c88165d34f7e2762665

**Comment by amisk** [comment]
He had to restart the pipeline from scratch ... I will get back to you tomorrow.

**Comment by amisk** [comment]
Yep, clones the latest master from pybdsf and it still remained. I'm sure that the error is caused by setting the open file limits.
