### ISSUE TITLE
Comparing 45 directions to 90 directions

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#112]
Hi,

Tim suggested to post this here, so here we go :)

I did a test with the dr2 pipeline. Once using 45 directions, and once using 90 directions. The comparison was made for the edge-on galaxy NGC 3556 and the face-on galaxy NGC 3631, both in the same field, because I was not satisfied with the results at NGC 3631.

Except for the number of directions, every parameter was the same.
Here are the results.
20 Arcsec resolution:
![3556_20arcsec](https://user-images.githubusercontent.com/19927617/46603227-c9b85f80-caf2-11e8-9f9d-c4400b8e372f.png)
![3631_20arcsec](https://user-images.githubusercontent.com/19927617/46603254-d6d54e80-caf2-11e8-8320-b0f65b8fb2db.png)
6 Arcsec resolution:
![3556_6arcsec](https://user-images.githubusercontent.com/19927617/46603267-e2287a00-caf2-11e8-9342-411268693e18.png)
![3631_6arcsec](https://user-images.githubusercontent.com/19927617/46603274-e785c480-caf2-11e8-8a1f-901ca72a2c63.png)

As you can see, the higher number of directions has little effect on NGC 3556, but a huge effect on NGC 3631.

I also checked the noises and fluxes.

20 arcsec  - 45 directions:

| | NGC 3556 | NGC 3631 | |
|-|--------------|---------------|-|
| RMS | 137 | 186 | µJ/beam|
| Total Power | 1.37 | 0.22 | Jy|

20 arcsec  - 90 directions:

| | NGC 3556 | NGC 3631 | |
|-|--------------|---------------|-|
| RMS | 125 | 144 | µJ/beam|
| Total Power | 1.32 | 0.21 | Jy|

6 arcsec  - 45 directions:

| | NGC 3556 | NGC 3631 | |
|-|--------------|---------------|-|
| RMS | 69 | 82 | µJ/beam|
| Total Power | 1.25 | 0.51 | Jy|

6 arcsec  - 90 directions:

| | NGC 3556 | NGC 3631 | |
|-|--------------|---------------|-|
| RMS | 75 | 80 | µJ/beam|
| Total Power | 1.41 | 0.34 | Jy|

The noises were measured in these boxes:
![n3556_rmsbox](https://user-images.githubusercontent.com/19927617/46604417-7b0cc480-caf6-11e8-9546-1c89695a1a61.png)
![faceon_rmsbox](https://user-images.githubusercontent.com/19927617/46604422-7f38e200-caf6-11e8-8f16-2cebcfbe574e.png)

The total fluxes were measured within their 3 sigmal contour levels.

As you can see, the total fluxes vary within ~10% in NGC 3556. The variation in NGC 3631 is higher, probably doe to the high errors from the nearby sources.

What do you think?

Would it be feasable to increase the number for certain datasets?

**Comment by cyriltasse** [comment]
Looking really great!... Maybe we could make 90 as a default... 45 was conservative...

**Comment by twshimwell** [comment]
Why stop there ;)

Perhaps we should think about a way to determine the number of facets within the pipeline rather than something hard coded. 

Do you have the .fits images and residuals and also the directions files somewhere we can access them to take a look?

**Comment by amisk** [comment]
I can put them up somewhere. What are the direction files you need?

**Comment by twshimwell** [comment]
just one of the *tessel.reg files (not the image_dirin ones)

**Comment by amisk** [comment]
Ah, you mean the ds9 reg files. ok.

I forgot to show the entire field:
![20_arcsec_45_facets](https://user-images.githubusercontent.com/19927617/46606039-c9709200-cafb-11e8-8c6f-b8358440da0e.png)
![20_arcsec_90_facets](https://user-images.githubusercontent.com/19927617/46606043-cbd2ec00-cafb-11e8-88fd-50a3b56e3457.png)

**Comment by twshimwell** [comment]
ah ok so a bit more divergence in the outer facets when using 90 directions. Thats quite interesting for the holes problem that is keeping cyril awake at night.

**Comment by mhardcastle** [comment]
Yeah, this is why I would not go to 90 by default. 45 is a compromise for SNR vs representation of the variation of the ionosphere that we arrived at after quite a bit of experimentation. If the code could adaptively decide the number of facets for good data, that would be great, but the pipeline default settings have to cope with data of all qualities.

**Comment by amisk** [comment]
Here are the files.
For the 45 directions set, the reg file is from a dirin image, because I previously deleted everything except the fits files, and I redid the run up the point where I got a reg file that looked ok.

https://my.pcloud.com/publink/show?code=kZnKYn7Zfbhamo4apVkAT534Q5L6H44T9ekk

**Comment by amisk** [comment]
Is there a way to manually add directions?

**Comment by twshimwell** [comment]
You can only change the number of directions (and you cant change it during the pipeline run) and not tweak where they are at the moment.

**Comment by twshimwell** [comment]
Hmmm this diffuse bit right in the middle of the field (attached) is much brighter in the 45 directions version... Do you know if this is in the model in both runs Arpad?

![screenshot 2018-10-08 16 08 35](https://user-images.githubusercontent.com/12065270/46613826-7e16ad80-cb14-11e8-9910-8099eb4ca923.png)

**Comment by amisk** [comment]
Interesting ... in the 45 Directions run, there is nothing there.
![screenshot](https://user-images.githubusercontent.com/19927617/46618791-bd4afb80-cb20-11e8-8b0c-edd062b07ff4.png)

**Comment by twshimwell** [comment]
ah ok. Perhaps its just not deconvolved then.

**Comment by twshimwell** [comment]
ah yes in the low image (should have looked at this before) where it is likely deconvolved in both 45 and 90 direction runs this source has very similar brightness which is good.

![screenshot 2018-10-08 17 39 42](https://user-images.githubusercontent.com/12065270/46618995-36e2e980-cb21-11e8-8961-8dfef7f1d28b.png)

**Comment by mhardcastle** [comment]
Closing this as I think we're sticking with 45 directions for DR2. Long-term it would be nice to see if there's some less rigid approach.
