### ISSUE TITLE
Refining archived products

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#114]
Presently we have the below. But to facilitate post processing we might need to tweak this a little and keep a final mask plus a dyscoed column from the msfile.

DDS0_5020358093.01_smoothed.npz
DDS1_5020358093.01_smoothed.npz
DDS2_full_5020358093.01_smoothed.npz
DDS3_full_5020358093.01_smoothed.npz
DynSpecs_L632463.tgz
SKO-panstarrs.png
SOLSDIR
astromap.fits
facet-offset.txt
image_dirin_SSD_m.npy.ClusterCat.npy
image_full_ampphase_di_m.NS.DicoModel
image_full_ampphase_di_m.NS.app.restored.fits
image_full_ampphase_di_m.NS.int.model.fits
image_full_ampphase_di_m.NS.int.residual.fits
image_full_ampphase_di_m.NS.int.restored.fits
image_full_ampphase_di_m.NS.mask01.fits
image_full_ampphase_di_m.NS.tessel.reg
image_full_ampphase_di_m.NS_Band0_shift.app.facetRestored.fits
image_full_ampphase_di_m.NS_Band0_shift.int.facetRestored.fits
image_full_ampphase_di_m.NS_Band1_shift.app.facetRestored.fits
image_full_ampphase_di_m.NS_Band1_shift.int.facetRestored.fits
image_full_ampphase_di_m.NS_Band2_shift.app.facetRestored.fits
image_full_ampphase_di_m.NS_Band2_shift.int.facetRestored.fits
image_full_ampphase_di_m.NS_shift.app.facetRestored.fits
image_full_ampphase_di_m.NS_shift.int.facetRestored.fits
image_full_low_QU.cube.dirty.corr.fits.fz
image_full_low_QU.cube.dirty.fits.fz
image_full_low_m.DicoModel
image_full_low_m.app.restored.fits
image_full_low_m.int.model.fits
image_full_low_m.int.residual.fits
image_full_low_m.int.restored.fits
image_full_low_m.mask01.fits
image_full_low_m.tessel.reg
image_full_low_stokesV.dirty.corr.fits
image_full_low_stokesV.dirty.fits
image_full_vlow_QU.cube.dirty.corr.fits.fz
image_full_vlow_QU.cube.dirty.fits.fz
logs
panstarrs-fit_state.pickle
summary.txt

**Comment by mhardcastle** [comment]
That's easy to do, but we should ideally make a final decision before I have to start deleting data at Herts!

(I can save quite a lot of disk space by deleting intermediate products like the individual channel QU images, before I have to start on the measurement sets.)

**Comment by rvweeren** [comment]
I checked, a single 20 channel MS (with dysco) from DR2 only takes up 1.7 GB. This archived ms contains  DATA_DI_CORRECTED and the WEIGHT_SPECTRUM which is all we need for the extraction. I can write few line python script which does that if needed (only input is big-mslist.txt).

btw image_full_ampphase_di_m.NS.mask01.fits is important for the extraction process + all "image_full_ampphase_di_m.NS" products to do a predict with kMS.

**Comment by mhardcastle** [comment]
Yeah, OK, we need to add that to the archive script and then retrospectively run it on all archived data. I may get time to look at this over the weekend.

We already have all `image_full_ampphase_di_m.NS` products, don't we?

**Comment by rvweeren** [comment]
> We already have all `image_full_ampphase_di_m.NS` products, don't we?

Yes, think so (we can take the image_dirin_SSD_m.npy.ClusterCat.npy for the cluster file as it is identical)

Here a the script, probably very close to what you need: /home/rvweeren/LoTSS_ClusterCAL/archivems.py (on the herts cluster)

Simply write out ms.archive files (dsyco compressed) based on what is in bigmslist.txt
Only needs NDPPP (source /soft/lofar-071018/bin/init-lofar.sh should be enough)
```
python /home/rvweeren/LoTSS_ClusterCAL/archivems.py --h

usage: archivems.py [-h] [-m MSLIST] [-c COLUMN] [-s INMSDIR]

Compress and copy column of a MS for archiving into a new MS

optional arguments:
  -h, --help            show this help message and exit
  -m MSLIST, --mslist MSLIST
                        DR2 mslist file, default=big-mslist.txt
  -c COLUMN, --column COLUMN
                        Column that is copied from the MS and compressed,
                        default=DATA_DI_CORRECTED
  -s INMSDIR, --inmsdir INMSDIR
                        Force the ouput MS to be in the same directory as the
                        mslist, default=False

```

**Comment by mhardcastle** [comment]
Brilliant, thanks!

**Comment by rvweeren** [comment]
I think we need the IMAGING_WEIGHT column to have the ability to regenerate the images? (I also use it for my DI selfcal on a cutout region as it suppresses bad data nicely). I can easily copy it over with pyrap/python-casacore, but having trouble getting pyrap to work on herts (in combination with load gcc-6.4).  

(NDPPP from lofar-071018 does function ok with  gcc-6.4)

**Comment by mhardcastle** [comment]
Ah, the weights are already saved by KMS (in SOLSDIR/*.ms/*Weights*npy), but for some reason they are not in the archive. I can fix that as well by uploading the DDS3 weight. Or should they have gone in the dysco-compressed MS?

You'd have to use the version of python-casacore in /soft/lofar-071018 for it to work properly with LOFAR software. In general the pipeline isn't designed to work with the LOFAR tree on the path...

**Comment by rvweeren** [comment]
>Or should they have gone in the dysco-compressed MS?

I think that is the preferred option.

>You'd have to use the version of python-casacore in /soft/lofar-071018 for it to work properly

Not sure, but there does not seems to be a properly installed python-casacore in there (I double checked I picked up the right version with casacore._\_file_\_ ). It gives:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-6-68e7f351d754> in <module>()
----> 1 t = pt.table('L604554_SB244_uv.pre-cal_12AA2D219t_121MHz.pre-cal.ms')

/soft/lofar-071018/python-casacore/python-casacore/casacore/tables/table.py in __init__(self, tablename, tabledesc, nrow, readonly, lockoptions, ack, dminfo, endian, memorytable, concatsubtables, _columnnames, _datatypes, _oper, _delete)
    309                         opt = 6;
    310                 if isinstance(tabname,str):
--> 311                     Table.__init__ (self, tabname, lockopt, opt);
    312                     if ack:
    313                         six.print_('Successful', typstr, 'open of', lockopt['option']+'-locked table', tabname+':', self.ncols(), 'columns,', self.nrows(), 'rows')

TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > from this Python object of type str
```

It seems that the python-casacore in  /soft/lofar-071018 is not installed with gcc 6.4, while the rest of lofar-071018 is (properly) compiled with 6.4?

I just do
-`eval /usr/bin/modulecmd bash load gcc-6.4`
-`source /soft/lofar-071018/bin/init-lofar.sh`
-`export PYTHONPATH=/soft/lofar-071018/python-casacore/python-casacore:$PYTHONPATH`
(mysteriously, because it is not in any of my environment variables, python sys.path lists "/soft/lofar-270618/python-casacore/python-casacore" on top so I manually remove that before the import casacore)

**Comment by mhardcastle** [comment]
Hm, OK, strange about the casacore on Herts, but I guess I could have broken something in the install, which was kind of convoluted. Let me look at it.

Re dysco compression of the weights, should we just use IMAGING_WEIGHT as the weight rather than WEIGHT_SPECTRUM ? Or do we need both? I have in fact already run your script on all the data I have at Herts overnight last night, but I can run it again...

**Comment by rvweeren** [comment]
We beed both because WEIGHT_SPECTRUM is required for a solve.

I just updated my `archivems.py` on Herts, it now also copies IMAGING_WEIGHT by default. 
(but it needs a working python-casacore, so I can only run it in Leiden at the moment)

**Comment by mhardcastle** [comment]
OK, so the build was picking up the wrong boost version. Fixed now and I'm testing the new version of the script.

**Comment by rvweeren** [comment]
Good. I will do one full end-to-end test then, also running the extraction, to make sure we have all products needed for that.

**Comment by rvweeren** [comment]
I verified that the predict and subtracts works and the right columns are present now (when I run my script on one of the datasets in Herts).

**Comment by cyriltasse** [comment]
We also use the residual data in DynSpecMS - perhaps we could just generate it before that step...

**Comment by rvweeren** [comment]
Adding DATA_DI_CORRECTED-DD_PREDICT would increase the size (per ms) by about 1-1.5 GB (assuming we compress this). We can regenerate within about 2 hrs so I guess it depends on how heavily they are planning using this.

**Comment by cyriltasse** [comment]
@rvweeren they're already generated... we could just save them in DD_PREDICT and change the name of the column to not confuse everyone?...

**Comment by mhardcastle** [comment]
I'd be inclined to say they can regenerate it, and we provide a script that allows this as part of the pipeline infrastructure.

**Comment by twshimwell** [comment]
Haha just saw as i was writing that martin posted the opposite but I'd be tempted to say its worth it 
just because then the product is there and we are more robust to things like software changes (we cant keep DD_PREDICT because dysco doesnt like signal) and if people want to use it DATA_DI_CORRECTED-DD_PREDICT they dont need ddfacet or kms. 24x1.5GB x 3200 = 100TB so I guess it does add up though. Happy with whatever consensus.

**Comment by mhardcastle** [comment]
Down the line we could regenerate those columns as a service. I think the less we store that most people don't need, the more likely it is that people will download and use the data.

**Comment by twshimwell** [comment]
ok. Well lets go for that then. 

A slight aside --  do you think as part of the new webpage we will be able to automate receiving requests like this and doing the processing? So e.g. someone could upload a ds9 region file and that could be picked up and processed to provide a DD calibrated dataset in that direction (so the processing Reinout is doing). I guess it would just be a matter or changing the status on the fields column for the appropriate fields.

**Comment by mhardcastle** [comment]
Yeah, I'd like to be able to do that. There's no technical reason why not. (I'd just do it as a separate job to run on the Herts system, with some control on how many jobs are running to make sure that I don't get swamped.)

**Comment by twshimwell** [comment]
Great. That would be fantastic. These DD calibrated datasets in a particular direction I think can facilitate a lot of science that will always be hard to get from the standard survey images (e.g source subtraction and the endless different number of imaging parameters people might want to use).

**Comment by twshimwell** [comment]
For the HETDEX fields I think we will already need the DATA_DI_CORRECTED-DD_PREDICT column because they are ready to have a bash analysing these. But I once all these new products are archived on Leiden I can do all the regenerating of this column.

**Comment by mhardcastle** [comment]
So, just to update on thls, the back catalogue of processed MSs are now being uploaded by the script to Leiden, in priority order. New runs should be getting MS compression by default but it'll take a couple of days for me to know whether that works, then I'll merge the new code into master. The database keyword `archive_version` is 0 for a dataset without the `.archive` files and 1 if they are present.

**Comment by twshimwell** [comment]
I wonder if a bug was introduced into the upload script that stops uploading image_full_ampphase_di_m.NS.mask01.fits because looking at the archived files we see that the most recent ones of these files are:

-rw-r--r-- 1 hardcastle lofar 1.5G Sep  1 04:09 P151+55/image_full_ampphase_di_m.NS.mask01.fits
-rw-r--r-- 1 hardcastle users 1.5G Sep  2 02:24 P20Hetdex17/image_full_ampphase_di_m.NS.mask01.fits
-rw-r--r-- 1 hardcastle users 1.5G Sep  2 18:11 P9Hetdex01/image_full_ampphase_di_m.NS.mask01.fits
-rw-r--r-- 1 hardcastle lofar 1.5G Sep  3 11:22 P149+47/image_full_ampphase_di_m.NS.mask01.fits
-rw-r--r-- 1 hardcastle lofar 1.5G Sep  3 14:00 P146+55/image_full_ampphase_di_m.NS.mask01.fits

**Comment by twshimwell** [comment]
Yeh I think a "workdir" is needed in the os.path.isfile that looks for the masks.

**Comment by twshimwell** [comment]
(I wont bother pushing this because you have a new version of the code for uploading anyway)

**Comment by mhardcastle** [comment]
Ah yes you're right. All of that 'workdir' stuff was a hurried hack to compensate for the fact that threads don't have their own working directory... so, now there is an archive version 2, which contains the compressed MSs and the mask files, and everything will be gradually uploaded.

**Comment by rvweeren** [comment]
There are a symbolic links in the SOLSDIR pointing to /beegfs/car/mjh, maybe simply not archive these symbolic links to avoid confusion?

ls -allhtr /disks/paradata/shimwell/LoTSS-DR2/archive/P150+57/SOLSDIR/L426447_SB244_uv.dppp.pre-cal_1279B2584t_121MHz.pre-cal.ms/killMS.DDS3_full_smoothed.sols.npz 
lrwxrwxrwx 1 hardcastle lofar 60 Aug 23 19:48 /disks/paradata/shimwell/LoTSS-DR2/archive/P150+57/SOLSDIR/L426447_SB244_uv.dppp.pre-cal_1279B2584t_121MHz.pre-cal.ms/killMS.DDS3_full_smoothed.sols.npz -> /beegfs/car/mjh/P150+57/DDS3_full_4959446403.01_smoothed.npz

**Comment by mhardcastle** [comment]
Added --safe-links to the rsync command, which should do it. Ideally the pipeline wouldn't create absolute links.

**Comment by rvweeren** [comment]
FYI I just tested the extraction on an actual archived dataset in Leiden. That works, successfully extracted a region and run subsequent selfcal with good/expected results (also using the IMAGING_WEIGHT and WEIGHT_SPECTRUM).

**Comment by mhardcastle** [comment]
Great. I am just waiting for a run to finish with the archiving built in to the pipeline -- should be 24h or so. Then I think we can declare victory on this.

**Comment by mhardcastle** [comment]
Merged the compress_ms branch. See the documentation for how this works.
