### ISSUE TITLE
DR2 ddf-pipeline on LBA

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#115]
Having a few problems here. The first being with the DI calibration step. Left is image_dirin_SSD_m and right is image_dirin_SSD_m_c_di where the calibration has gone wrong. For this DI step dt = 1.07 and NChanSol = 4 (there are 40 channels and ~1MHz in each chunk of data). 

<img width="716" alt="screenshot 2018-10-20 06 52 44" src="https://user-images.githubusercontent.com/12065270/47251534-e6c72980-d434-11e8-95f5-ff01bffeedb4.png">

Perhaps its not surprising that its failing because the phases look like the below (so for some reason a big offset between XX and YY).
<img width="1013" alt="screenshot 2018-10-20 07 18 02" src="https://user-images.githubusercontent.com/12065270/47251743-51c62f80-d438-11e8-89ff-0e6b486123fa.png">

**Comment by mhardcastle** [comment]
I thought this had worked in the past? Did the DI step work previously?

**Comment by twshimwell** [comment]
Yeh I think it worked past this previously with a 8hr LBA calibrator observation (with the calibrator subtracted so just the wide field around) -- we got good images previously. This is an LBA sparse dataset whereas the other was an LBA outer one but not sure if that would cause any difference really. The DI processing has also changed a bit but i dont see that would cause this either. Nothing strange has been done to these data has it @revoltek? Not like changing it to circular or anything.

**Comment by cyriltasse** [comment]
Did you try a `ClipCal` on this?

**Comment by twshimwell** [comment]
yeh it does a clipcal -- an example log from that is https://www.dropbox.com/s/uhwhf3mlmka1hf1/ClipCal-comb_224_234.ms_DIS0.log?dl=0

**Comment by mhardcastle** [comment]
Strategy has evolved to not use DI step.
