### ISSUE TITLE
Pipeline effect on harddrives?

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#116]
Hi,

I don't know if this is an actual issue with the pipeline, but I'd like your opinions.
Now, a couple of times, on two different hard drives, the filesystem on those suddenly changed to read-only while the pipeline was running. This happens if an error is encountered. I did a SMART test and a block test, but according to them, the drives are fine, although a filesystem check reveals errors.

Could you think of anything that might result in this? Too much IO maybe?

Arpad

**Comment by mhardcastle** [comment]
The pipeline does a lot of IO, unsurprisingly, but you'll only see the FS going read-only if there is some underlying problem with the file system or (worse) the hardware. Check the system logs to see what actually happened. You're not running on some non-native file system like VFAT, are you? It's been extensively used on ext4 and xfs...

**Comment by mhardcastle** [comment]
Going to close this, re-open if there is new information.
