### ISSUE TITLE
should we cutoff at say 0.3 of the pb?

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#117]
The images we get from the pipeline often look much worse towards the edges but we are really imaging very very far from the pointing center. Should we have a final step to trim all the images to some value (say default 0.3) of the primary beam? (would also make things a bit smaller)

**Comment by twshimwell** [comment]
-- benefit of this is that when we share our images they look better.

**Comment by mhardcastle** [comment]
Guess we decided not to do anything about this.
