### ISSUE TITLE
move the low resolution full bandwidth

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#12]
If the low resolution full bandwidth image were moved before the high resolution full bandwidth image then we could use the masking of the low resolution image to capture extended sources which may be hard to mask from the high resolution image.

**Comment by mhardcastle** [comment]
Masking the low-res full-bandwidth image -- I have pushed to master some changes which improve (a) the masking and (b) the command-line interface.

If you pull these and try `python /path/to/ddf-pipeline/make_extended_mask.py image_full_low_m.app.restored.fits image_full_ampphase1m.app.restored.fits 1500 1.8` I'd be interested in whether you think those parameters make a sensible mask for the very extended stuff in your test images. Seems we can go a fair bit deeper in the full-bandwidth low image.

**Comment by twshimwell** [comment]
Had a go with this and it seems to do a good job getting the extended sources. I don't get any spurious detections and nothing is obviously missing from the mask. 

The structures of the masked regions are perhaps impacted a bit my the blotchiness of the low res imaging and maybe sources close to the extended emission which get incorporated into the mask but I think thats inevitable.

So I think seems good.

**Comment by mhardcastle** [comment]
Pushed changes to master to implement this deeper masking and then provide the new mask to the full-res imaging. Please test and report back!

**Comment by twshimwell** [comment]
I'll test.

**Comment by mhardcastle** [comment]
Declaring victory on this, reopen if you find problems.
