### ISSUE TITLE
Offset correction

### ISSUE THREAD

**Issue by martalves** [mhardcastle/ddf-pipeline#120]
Hi Mark, 
I'm running the pipeline on a 8h synthesis LOFAR HBA field; I have 200 MS of 1.9 MHz each. My goal is to do RM-synthesis using the calibrated 200 Q and U images. I ran into a problem at the offset correction step. I attach a screenshot of my terminal. Would you be able to help? Thank you! Marta

![screen shot 2018-11-02 at 15 19 29](https://user-images.githubusercontent.com/44372136/47920664-e1e18b80-deb2-11e8-9a64-ffff2f9f6e34.png)

**Comment by mhardcastle** [comment]
Do you actually need the offset corrections? They won't work on the Q and U images anyway. If not, remove the `offsets` section from the parset and the run should proceed.

I don't know quite what is happening here, it may be an astropy version incompatibility. But if we can avoid solving the problem then that's even better.

**Comment by martalves** [comment]
Hi Martin - sorry for getting your name wrong the last time,
thanks for your reply. Yes, I guess that for the moment I can get by without the offset corrections, as I'm not directly interested in the I map.
