### ISSUE TITLE
Change all symlinks to be relative rather than absolute path

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#121]
This can be done with e.g.

symlinks -c /disks/paradata/shimwell/LoTSS-DR2/other-fields/LBA-Bootes-Sparse/HBA-pipeline/SOLSDIR/Bootes_SB20.MS

which would change all the symlinks in the directory /disks/paradata/shimwell/LoTSS-DR2/other-fields/LBA-Bootes-Sparse/HBA-pipeline/SOLSDIR/Bootes_SB20.MS to have a relative path.

The reasoning is that once archived the symlink paths still work.

Not sure whats the best way to fix this for all archived data. Is it just for us to manually do it in leiden for all the archived files?

**Comment by mhardcastle** [comment]
Don't quite see how this will work since it doesn't know what absolute paths need changing to what relative paths.

We are no longer uploading symlinks (see discussion in #114) so the easiest fix to make the archive consistent is simply to remove the archived symlinks altogether.

**Comment by twshimwell** [comment]
If one had the symlinks being e.g. 

../../DDS3_full_5045777004.005561_smoothed.npz 

would that not work?

Yeh otherwise its easy for us to change the archive.

**Comment by rvweeren** [comment]
@twshimwell, yes changing it to something like this is easiest for the extraction (relative paths are allowed in symbolic links). A small script update the links to the full path before the extraction would also fix it.

In this way we can simply specify the solutions via

`--DDESolutions-DDSols=DDS3_full_smoothed --DDESolutions-SolsDir=SOLSDIR`

At the moment I am using something like `--DDESolutions-SolsDir=DDS3_full_4938170605.01_smoothed.npz`

But some LoTSS pointings have two observations, hence two sets of solutions and then the bookkeeping is more complicated as I need to make two mslists. 

Or is something like `--DDESolutions-SolsDir="DDS3_full_4938170605.01_smoothed.npz,DDS3_full_5001763524.01_smoothed.npz"`
 allowed??

(then there's no need to care about the sym links at all as we do not really need them)

**Comment by mhardcastle** [comment]
I would have thought you just need to remake the symlink on extraction (and the old broken absolute links should be purged from the archive).

Cyril's code in the pipeline that makes the links explicitly uses abspath, I don't know why.

**Comment by twshimwell** [comment]
Cyril mentioned he is going to change DDFacet so that it can read a dictionary of solution files. So perhaps we hold off doing anything here until that is up and running.

**Comment by mhardcastle** [comment]
Fixed the original issue in the migration of the archive so I think this can be closed now.
