### ISSUE TITLE
Integrate new calibration scheme in pipeline

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#122]
Just to discuss the integration of what's proposed here

https://github.com/cyriltasse/killMS/issues/15#issuecomment-435339478

in the pipeline? Everyone agrees we should go ahead with this? I can do it tomorow, and @mhardcastle does the necessary to redo what needs to be redone?

**Comment by twshimwell** [comment]
I'm very happy with this as its clearly making things much better.

Are there any other tests we should do? I'd like to do some injections of extended sources but i feel doing that now would delay things which would be a shame. Also qualitatively its looking good.

What values for uvmin at dt should we settle on?  I'd be tempted with <500m and >30mins

**Comment by rvweeren** [comment]
I would push the dt as large as possible (probably limited by the memory and the need to avoid swapping). I think we need uv-min testing, maybe if we decrease uvmin too much diffuse emission can be absorbed.

**Comment by twshimwell** [comment]
Cyril mentioned dt=60 used ~190GB so thats maybe as large as we can go (for me on one of the bad leiden machines this took 1hr per 10sb block).

OK ill start running a field with a range of uvmin (<1.5km).

**Comment by twshimwell** [comment]
I think this can be closed :)
