### ISSUE TITLE
potential deep field imaging strategy

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#129]
Perhaps others have different ideas but to image deep fields maybe we do something like:

1) take best field and run with pipeline.py
2) calibrate all fields using the dicmodel and facet layout in 1)
3) image everything.

To do this perhaps a nice way to do it is to have a input dicomodel in pipeline.py. If this dicomodel option is used then it skips all steps up until the calibration off the image_full_ampphase_di_m dicomodel step. Then we can do the deep fields simply by running pipeline.py once with the best field and again with the dicmodel and facet layout and all the data from all fields.

**Comment by twshimwell** [comment]
I think that all the products from pipeline.py -- like polarisation, stokes V, blank datasets and other things will be useful for the deepfields too.

**Comment by twshimwell** [comment]
I’ll try to implement allowing a dicomodel to be input. I had thought to resume from this place

CurrentDDkMSSolName=killms_data('image_full_ampphase_di_m'...

But do we want to do bootstrap and the DI calibration too? I guess ideally we do.

**Comment by cyriltasse** [comment]
In my opinion, no need for bootstrapping, but if we want to do polarisation imaging, we'll need to do the DI step...

**Comment by twshimwell** [comment]
Ok that’s good about bootstrap.

I think we do want polarisation but it seems quite expensive as in the pipeline think it would mean going right back to 

CurrentDDkMSSolName=killms_data('image_ampphase1_di',o['full_mslist'],'DDS2_full',...

**Comment by mhardcastle** [comment]
Given that we no longer normalize the flux scale, yes, we can probably do without bootstrap as long as the flux scale for the input model is good.

I think we have to go back to DI cal on the full mslist, i.e. where you say.

Can we be careful about branches if modifying code please? Ideally I'd like us to sign off on the _v3 branch and merge back into master before we start a new branch for testing this, otherwise we're going to have a nightmare at merge time (we already have incompatible changes to master and _v3). That means Cyril needs to be happy with the strategy for holes, though.

**Comment by twshimwell** [comment]
OK i dont actually think we need any code modification if we do this.

We simply have mslist = 6 msfiles from your best observation

big-mslist = all files from all observations.

**Comment by mhardcastle** [comment]
And make sure all the maps from the 'mslist' processing are copied into the working directory? (They'd have to be copied because the code will try to e.g. check imaging weights.) Bit hacky, but I suppose it'll work.

**Comment by twshimwell** [comment]
Yeh or just start the code from scratch with the mslist of 6 files and big-mslist of all files. I think that would handle it.

I thought it was quite elegent compared to any code alterations id make :)

**Comment by cyriltasse** [comment]
@twshimwell Why not... We could do mslist of 24 big-mslist of 24x10 or whatever...?

**Comment by cyriltasse** [comment]
It's not the way I would origially do it (cos it's more expensive), but maybe it's the simplest...

**Comment by twshimwell** [comment]
im not sure I understand this one:

@twshimwell Why not... We could do mslist of 24 big-mslist of 24x10 or whatever...?

Is this saying we put multiple observations in mslist.txt?

**Comment by cyriltasse** [comment]
There was just a missing word, sorry, it should be:

@twshimwell Why not... We could do mslist of 24 _and_ big-mslist of 24x10 or whatever...?

**Comment by twshimwell** [comment]
Ah I see. Yes we could certainly do that so do the full bandwidth of the best observation in mslist.txt. I wouldnt have thought it could hurt to do that and it barely impacts the compute time.

I might start a field with this strategy.

**Comment by twshimwell** [comment]
with just say 40hrs for now.

**Comment by mhardcastle** [comment]
You want to pick your best field to be the 'mslist' here so surely it makes sense to use something that's already run through the pipeline once and then copy the output as though it was the result of a 24-MS mslist.

Also, I have no idea whether bootstrap will work properly on a 24-MS mslist, though maybe it will...

**Comment by twshimwell** [comment]
Yeh so renaming the image_full_ampphase_di_m.NS files from a completed run to image_ampphase1_di and then starting from that.

**Comment by twshimwell** [comment]
OK the branch master_massive_if now allows for one to input a dicomodel, baseimagename, basemaskname and clusterfile. If this happens then the code begins at 

`separator("DI calibration of full mslist")`

I'm testing this now. When using this inputs none of the input files should be the same as the output files because otherwise they will be overwritten or steps could get ignored.

I have also added examples/tier1-nov2018-deepfields.cfg which is the example parset for running the deep fields (i.e. it takes the basedicomodel and does not do polarisation or low resolution imaging).

**Comment by twshimwell** [comment]
OK this seems to work. It begins at the correct place anyway.

**Comment by twshimwell** [comment]
I think the only open issue on this strategy is whether or not we want to use the current final products from an 8hr run to calibrate all the data. The issue that @cyriltasse mentioned is that this final deconvolution is done with AllowNegativeInitHMP=True but perhaps calibration works better from images created with AllowNegativeInitHMP=False.

**Comment by nudomarinero** [comment]
One question. Before running the master_massive_if version of the pipeline the imaging weights had to be removed (or did I get it wrong?). How was this done?

**Comment by mhardcastle** [comment]
You can use the control/remove_columns=True option, either in a config file or on the command line if you want to do it as a one-off (pipeline.py --control-remove_columns=True config.cfg). Or you can run the remove_columns.py script on an mslist manually.

**Comment by twshimwell** [comment]
When attempting to image 7 observations together (168msfiles) im running into memory errors on my 250GB node. The log is https://www.dropbox.com/s/qap3qr0bm012rd0/ddf-mem-error.txt?dl=0

**Comment by twshimwell** [comment]
And here is a image of memmonitor.py during this period.

This run i tracked was on a node with 512GB ram and 256GB in /dev/shm.

It seemed to get through loading about 6 observations before having this memory issue. I have 20 observations for this field.


<img width="715" alt="screenshot 2018-12-10 07 36 34" src="https://user-images.githubusercontent.com/12065270/49714781-8db68d80-fc4e-11e8-9c9b-171d6377e0b4.png">

**Comment by nudomarinero** [comment]
killMS raises an error in one band:
[KillMS-_disk03_jsm_LOFAR_data_017_avg_L231647_SBgr006-10_uv.MS.pre-cal.ms_DDS2_full.log](https://github.com/mhardcastle/ddf-pipeline/files/2668472/KillMS-_disk03_jsm_LOFAR_data_017_avg_L231647_SBgr006-10_uv.MS.pre-cal.ms_DDS2_full.log)

**Comment by nudomarinero** [comment]
I have just realised that I did not rename the input model and this may be generating some confusion to the script. I am trying again renaming the input image files.

**Comment by mhardcastle** [comment]
I don't see how other bands would have succeeded if that was the issue, but let us know. If not, this is a problem deep inside KillMS and @cyriltasse will have to take a look.

**Comment by cyriltasse** [comment]
@nudomarinero yeah i find it suspicious... if the problem persists, I'll need to take a look and to have access to that cluster - would that be possible?

**Comment by nudomarinero** [comment]
Yes, the problem persists but... now appears in L231647_SBgr004-10_uv.MS.pre-cal.ms (instead of L231647_SBgr006-10_uv.MS.pre-cal.ms) after processing 4 bands (!).
I will have a look about the access to the cluster but it may be very difficult as there is no access to external users to the ROE network. In the mean time, is there anything that I can look at?

Investigating a bit more, I have found that this error could be raised if there is a NaN or an Inf value in the matrix "A". It could be related to the lineal algebra libraries linked by Numpy.

**Comment by twshimwell** [comment]
To fix the memory issue @cyriltasse suggested I append --Misc-ConserveMemory=1 to my DDFacet calls when using lots of data. 

This was working very well but just in the last 30mins (after 20hrs of gridding stuff) its started writing out seemingly endless text saying

0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 
gridder: probably there is a problem in the BDA mapping: (ChanMean, gridChan, diff)=(0.600000, 0, 0.600000)
0 0 -1 -1 -1 -1 

I think it is still working though...

**Comment by nudomarinero** [comment]
Now I have a:
```
Solving ..  285/420 [================================                ]  67%  - 16'23"
Process WorkerAntennaLM-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/jsm/local/DDF-v2-deep/killMS/Wirtinger/ClassWirtingerSolver.py", line 1352, in run
    x,Pout,InfoNoise=JM.doEKFStep(G[iChanSol],P[iChanSol],evP[iChanSol],rms,Gains0Iter=G0Iter)
  File "/home/jsm/local/DDF-v2-deep/killMS/Wirtinger/ClassSolverEKF.py", line 270, in doEKFStep
    self.PrepareJHJ_EKF(Pa,rms)
  File "/home/jsm/local/DDF-v2-deep/killMS/Wirtinger/ClassSolverEKF.py", line 64, in PrepareJHJ_EKF
    JHJinv=ModLinAlg.invSVD(JHJ)
  File "/home/jsm/local/DDF-v2-deep/killMS/Array/ModLinAlg.py", line 216, in invSVD
    u,s,v=np.linalg.svd(np.complex128(A))#+np.random.randn(*A.shape)*(1e-6*A.max()))
  File "/home/jsm/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1562, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/jsm/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge`
```
in /disk03/jsm/LOFAR_data/017_avg/L231647_SBgr003-10_uv.MS.pre-cal.ms.

I will keep trying but it looks very random.

**Comment by nudomarinero** [comment]
OK, I have an idea of the origin of all this mess. It is the non-standard calibration of cycle 2 that is biting me again. 

If the input data of killMS is too far from the model (which is also affected by the parameters used in killMS) the SVD decomposition can diverge. I have seen that, if the DI step is skipped, this error is raised in some cases. Trying to apply a direction dependent calibration straight away to the output of pre-factor can raise this error in some cases as well, independently of the quality of the input model.

The error in the deep pipeline in my case (and probably the origin of the high noise found in many cycle 4 ELAIS-N1 images) comes from the fact that the corrected data is stored in the column "CORRECTED_DATA" for cycle 4 (standard) and in the column "DATA" for cycle 2 (non-standard).

**Comment by twshimwell** [comment]
The deep pipeline should do a DI calibration as the first step.

Oh odd about the DATA v CORRECTED_DATA thing. This is an issue even if you put the column in the parset if you try just the data in one of the formats? I guess to image all together you will need to get all the right data into a column of the same name.

**Comment by nudomarinero** [comment]
> I guess to image all together you will need to get all the right data into a column of the same name.
Exactly. Any ideas of any TaQL command to create an alias? If not I may just have to rename them.

**Comment by twshimwell** [comment]
In pyrap tables it’s quite easy to copy DATA to a new column

               desc = t.getcoldesc(args['column'])
               desc['name']= colname
               t.addcols(desc)
            print 'Writing %s'%colname
            t.putcol(colname,datacolumdata )

**Comment by mhardcastle** [comment]
OK, I think the outstanding issue here was merging the massive_if branch, which is now done. Closing.
