### ISSUE TITLE
merge in multi-obs capability

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#13]
Put Wendys bootstrap modifications into the new bootstrap so that multiple nights of observations are dealt with appropriately (lots of low-dec data being captured recently and nice to all work with the same pipeline)

**Comment by mhardcastle** [comment]
Yep. I can do the merge but I'll need Wendy's help with testing since she has suitable data.

**Comment by mhardcastle** [comment]
This is merged now and bootstrap still seems to work on single-obsid data. I will close for now, reopen if there's a problem when we test with multi-obs mslists.
