### ISSUE TITLE
dysco compress all prefactor products

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#133]
To save space we were thinking to dysco compress all prefactor products on the grid. The simplest way would probably be just taking the CORRECTED_DATA column of each dataset and no longer having an instrument table or the DATA column.

However, if DATA is required or the instrument table is required we can try to keep them all.

**Comment by mhardcastle** [comment]
Don't think we need either. But clearly we should test running the complete pipeline on a compressed set of products, preferably one we've done already.

**Comment by twshimwell** [comment]
It would mean that the products are no longer compatible with FACTOR which is a shame as many SKSP members use FACTOR.

**Comment by mhardcastle** [comment]
We've had the functionality to work on compressed data for some time, closing this.
