### ISSUE TITLE
dynspecms error

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#139]
Hmm for one of my newer runs I am seeing the error below. 

ms2dynspec.py --ms mslist-L657024.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel LOFAR --BeamNBand 1 --srclist brightlist.csv

                                 version v1.0-5-g673c0b6
 - 12:19:53 - AsyncProcessPool          | Fixing parent process to vthread 0
 - 12:19:53 - AsyncProcessPool          | Worker affinities not specified, leaving unset
usage: ms2dynspec.py [-h] [--ms MS] [--data DATA] [--model MODEL]
                     [--sols SOLS] [--srclist SRCLIST] [--rad RAD]
                     [--noff NOFF] [--LogBoring LOGBORING] [--imageI IMAGEI]
                     [--imageV IMAGEV] [--BaseDirSpecs BASEDIRSPECS] [--uv UV]
                     [--SolsDir SOLSDIR] [--NCPU NCPU]
ms2dynspec.py: error: unrecognized arguments: --BeamModel LOFAR --BeamNBand 1

**Comment by cyriltasse** [comment]
You're maybe not on the right branch (I'm on `ApplyBeam` beanch, which  has `v1.0-17-gc35b69c`)

**Comment by twshimwell** [comment]
Ah yes I was still on StokesV
