### ISSUE TITLE
measure and apply astrometry corrections

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#14]
Perhaps half of this should be on the ddfacet page...

In ddfacet read in astrometry corrections and apply when stitching together the facets.

In ddf-pipeline quality pipeline update the astrometry corrections measurements to use panstars and pass these to ddfacet once it can apply them.

**Comment by mhardcastle** [comment]
Will need help from @cyriltasse for the ddfacet end of things. For our initial production runs probably we should just try to measure the offsets.

**Comment by cyriltasse** [comment]
If one can give me a an npy array with an (l,m) offset per facet I can probably do something ~simple in a Restore.py that would take the LastResidual cache which contains all the needed individual facets infos...

**Comment by cyriltasse** [comment]
When facet-based astrometry correction is applied, what should I compute? app.restored, int.restored is enough? Or should I also do a alpha map?

**Comment by mhardcastle** [comment]
.app.restored and .int.restored is enough. We don't use the alpha maps for anything.

**Comment by cyriltasse** [comment]
So I've added ad option to do the astrometric correction per facet in AutoMasking_SNR.

It's got to be called like

DDF.py <previous.parset> --Output-Mode RestoreAndShift --Predict-InitDicoModel <UseToRestore.DicoModel> --Output-ShiftFacetsFile <ShiftFile.txt>

With ShiftFile being for example:

3.926042 0.595192 10 20
3.805634 0.698240 10 20
3.805606 0.598590 10 20
3.805585 0.498358 10 20

columns being ra_radian, dec_radian, dl_pixel, dm_pixel

Seems to be working well. All clear?

**Comment by mhardcastle** [comment]
OK... not quite sure I see what the ra and dec are for, if we're doing a shift per facet. Will the code just use them to figure out which shift goes with which facet?

**Comment by mhardcastle** [comment]
Ready for testing, please report issues here.

**Comment by mhardcastle** [comment]
Closing this as we seem to be happy.
