### ISSUE TITLE
Flux scale drift

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#140]
Flux scales are drifting pretty seriously in DR2 (as noted in #55).

Quality pipeline runs on the 183 v2.1 reprocessed datasets we have so far show that the median ratio of LOFAR to TGSS fluxes for isolated sources is 0.75, and LOFAR to NVSS is 3.6 (should be 4.9 for alpha = 0.7). There is more scatter in the LOFAR to TGSS ratios (see plot) but we can't blame this on TGSS alone because NVSS also shows it, and there is a correlation between the offsets for the two catalogues. And this must happen after bootstrap because NVSS is used in the bootstrap for a bunch of the fields.

We should probably figure out a global correction factor to apply before mosaicing (at least bootstrap should have removed the frequency dependence).

One thing I wondered about was whether we could deduce a correction factor from the normalization of the source counts above some flux cutoff. It would be possible to fit for this pretty easily in the quality pipeline since we make a catalogue of the central ~ 16 sq deg. The limiting factor would be cosmic variance I guess. I might try to code the fit up and see how it looks.

The other question is whether we can do anything about the drift in the pipeline. Originally we had normalization in there... could we normalize the overall amplitudes in the smoothing and DI steps? Doesn't help for the existing fields because I am absolutely not reprocessing them again.

![fshist](https://user-images.githubusercontent.com/5337708/50605249-b03c6f00-0eb9-11e9-80b9-9e2d163fe3ff.png)

**Comment by twshimwell** [comment]
I can also try a script I have that attempts to align paintings based on fluxes measured in the overlapping regions. Source counts sounds nicer to me though. I guess with source counts in e.g. galactic regions and things like coma there could be a few problems but for the dr2 region it’s all quite nice regions.

**Comment by mhardcastle** [comment]
Yeah, the alignment script idea relies on the flux scale being correct on average though -- which it doesn't seem as though it is.

I have a proof of principle script using the source counts which seems to give something like the right answer. Will post some results here maybe next week.

**Comment by mhardcastle** [comment]
OK, I've pushed the source count fitting code to master.

The basic idea is to use the 150-MHz source counts in Intema+ 17 as a reference, and assume that the functional form given there is right. Then any difference between the normalization of the source counts in the LOFAR data and that form must be because of an incorrect flux scale, so you can iteratively find the scaling factor that needs to be applied to the fluxes. I fit a power law to the LOFAR number counts in the centre of each field, normalizing at 100 mJy because the number counts are pretty well known at that point, and applying a 20-sigma completeness cut. There is a pretty strong prior on the power-law index (when I had this free the mean value was very consistent with the Intema+ functional form at 100 mJy but the scaling factor was too dependent on the fitted power low index). The scaling factors (divide fluxes by these values) for ~250 fields range between 0.68 and 1.0 and the mean is 0.84 -- compared to 0.79 from direct TGSS flux scale comparison. Here's the effect on the flux ratio histograms -- clearly a big step in the right direction.

![ratio](https://user-images.githubusercontent.com/5337708/50740183-b183d980-11e2-11e9-9e41-f376daa16b03.png)

**Comment by twshimwell** [comment]
So some fluxes will change by 1/0.4. Eeeek thats pretty huge. Out of interest how many sources are typically in the source counts?

A weighted mean sounds nice but then would be impacted by errors from all 3 situations perhaps. So id say this is too complex a correction to apply.

I think my favoured option would be to adopt this new method.  Is it worth scaling the 150MHz counts to our central frequency of 144MHz (maybe a 3% difference)? My least favoured option would be to adopt TGSS (nice to keep it completely independent as more of a comparison).

We already bootstrap off WENSS (or NVSS) and VLSSr but I guess now those bootstrapping corrections are only relevant for inband spectral index measurements (which should be checked again by people before they use them). Our flux scale seems to be getting increasingly complicated...

**Comment by twshimwell** [comment]
(I suspect scaling by the source counts may cause serious issues for the cosmology studies which is a downside)

**Comment by twshimwell** [comment]
Just looking at how well aligning pointings from sources in the overlapping regions could work. Here I am just using the raw pybdsf catalogues but would probably benefit from a bit of filtering to just keep compact sources.

Anyway, as a first test ive split the sky into a bunch of regions (250 of these) and each region contains say 12 pointings. I'm then using multinest to allow each catalogue to be scaled and finding the scaling parameters that maximise the liklihood.

The results are shown in the attached. The xaxis is RA of a cross matched catalogue of two pointings, the y-axis is the flux ratio between pointings at that RA. 

Red is uncorrected fluxes
Green is fluxes corrected using this method
Blue is fluxes corrected using the source count alignment method (so the results from Martins analysis).

For a more quantitative assessment. The standard deviation of the ratios is 0.129, 0.113 and 0.132 for the red, green and blue respectively.

I'm doing more runs (all the regions that have a good number of pointings in DR2) so can post more results when i get them. 

![screenshot 2019-01-16 14 36 30](https://user-images.githubusercontent.com/12065270/51252447-22be4c00-199c-11e9-818c-0ab8ee24e8b1.png)

**Comment by mhardcastle** [comment]
Discussion of this issue is continuing in #171. (However note that the issue with NVSS is not as bad as I said at the top of this thread, because I matched with all NVSS sources and we are deeper than NVSS, hence biased to flat spectrum. If I put a flux cut in the NVSS ratios are more reasonable.)
