### ISSUE TITLE
Bad facet alert

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#147]
Since we restarted the full processing I've seen several fields come through with bad facets near the centre of the field, which pretty much never happened in earlier processing unless we were in the Galactic plane. Examples are `/beegfs/car/mjh/P279+43` and `/beegfs/car/mjh/P283+43` on the Herts cluster.

This may just be coincidence, but is it possible that the changes to killMS to implement the slow solve might have broken something? The problems start to show up after the first ampphase calibration.

**Comment by cyriltasse** [comment]
Ouch.... I'll have to take a look then... Now sure i can do this before beginning of next week...

**Comment by cyriltasse** [comment]
Can I get a node from now to whenever I've sorted out the problem?

**Comment by mhardcastle** [comment]
Yeah, you can have node043 in about 10 minutes, I'll kill what's running there.

**Comment by cyriltasse** [comment]
thanks

**Comment by mhardcastle** [comment]
It's free now.

**Comment by twshimwell** [comment]
any joy with this one? I was thinking to start a few new runs perhaps.

**Comment by cyriltasse** [comment]
Hoooo - I think I found it...

**Comment by cyriltasse** [comment]
ok - i find it hard to test cos `/car-data` is so slow. I've pushed the changes (completely disabled `PowerSmooth`) on branch  `kMS:FixQ_PowerSmooth`. I don't know if that will be enough to fix the issue though. Lemme know.

**Comment by cyriltasse** [comment]
Maybe start over calibrating `DDS2_full`

**Comment by mhardcastle** [comment]
I think the problems start up before that, gonna go back to the first amp solution. (Which will also be quite quick to show whether it's working.)

I'll get a test running this evening.

Why do you think `PowerSmooth` has suddenly stopped working?

**Comment by cyriltasse** [comment]
I've noted some MS have many CS flagged...

**Comment by mhardcastle** [comment]
OK, this is looking much better at ampphase1. top=new, bottom=old.

Will let it run through to the end.

![ds9](https://user-images.githubusercontent.com/5337708/51634155-70fabe80-1f4b-11e9-8700-e0fb61444bf8.png)

**Comment by cyriltasse** [comment]
Encouraging!

**Comment by mhardcastle** [comment]
These fields are generally much better, though still not perfect, with the fix to remove the powersmooth. I have also taken powersmooth controls out of the pipeline altogether, since they no longer do anything, and am closing this now.
