### ISSUE TITLE
archiving

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#15]
Need to decide what to keep from a ddf-pipeline run.

Perhaps:

-- all image_full* files besides the *brutal* and the *labelIslands*  (high res and low res)
-- final solutions
-- bootstrap results
-- quality control pipeline output
-- logs 
-- i wonder if it also possible to keep somewhere which parset was run and which github repository versions was used?
-- the data? (or do we want this in a separate archive, its about 500GB -- if we put it here we probably also want to bring across diagnostics from the prefactor)

**Comment by mhardcastle** [comment]
* If processing the data on a remote site such as Herts it's best if we don't have to upload it again. So I'd vote no to this.
* We can perhaps write at the end of the pipeline run an automatic human-readable text file with details of the pipeline execution and versions of the codes. (Note that some useful information will get into the FITS headers as well once my changes to master ddfacet propagate into the code we're actually using...)
* Do we need the noise, mask (other than final mask), model (other than final model), dirty images?

Also, can you tell me where on Leiden you will want us to dump this?

**Comment by twshimwell** [comment]
OK yes makes sense not to keep the data then.

The automatic text file with details sounds good (FITS headers sounds excellent too, especially when we actually release images).

OK, maybe we don't need all full products then. Maybe the dirty is quite nice as its a real dirty and can give insight into deconvolution issues. But yeh perhaps the noise doesnt tell us much and maybe only the final masks and models are really that useful.

So this would leave just:

High and low res -- final model, final mask, full bandwidth dirty, final residual, final image
Other -- final solutions, quality output, logs, bootstrap

This should be enough for out final release products plus reimaging a region of interest and some basic diagnostics incase something seems wrong  or strange.

I've emailed over details about storage.

**Comment by mhardcastle** [comment]
OK, there is an archiver script in master that runs in the working directory and makes a tar file, and at the end of ddf-pipeline a summary.txt file is created with some details of what was run. (This relies on the version number code I have pushed into our current working branches of both DDF and killMS, @cyriltasse , so I hope this is OK...)

Assuming these tar files get everything we want, we then just need small wrapper scripts for each site that rename the archive.tar file appropriately and dump it in the right place.

**Comment by mhardcastle** [comment]
Added quality pipeline output to this. Going to test by archiving some of my HETDEX observations and pushing them off to Leiden. @twshimwell , can you check that this works for you and the contents of the tarfile seem sensible?

**Comment by twshimwell** [comment]
sure will have a go testing this and let you know. Ive just got to run the quality pipeline first.

**Comment by twshimwell** [comment]
Ah might have to wait as my existing runs seem to be missing some crucial files for the quality pipeline (the ampphase1m.smooth)

**Comment by mhardcastle** [comment]
We don't make .smooth images any more, the .int images are what you
want. The default has changed accordingly in the quality_options.py,
have you pulled?

**Comment by twshimwell** [comment]
Ah haha, not recently enough it seems. OK running now.

**Comment by mhardcastle** [comment]
I uploaded some archives of my old runs to the Leiden space over the weekend.

If you are happy, Tim, we can close this issue.

**Comment by twshimwell** [comment]
The pybdsm call I guess now runs on the whole image? It ran for me but it took 2 days...

**Comment by mhardcastle** [comment]
Yes it does. If you download and install the latest pybdsf (yes f) from github you should see a substantial speedup, like a few hours rather than 2 days.

**Comment by twshimwell** [comment]
Ah ok ill try that. I'll look at the archive things after this meeting.

**Comment by twshimwell** [comment]
Looks good to me Martin.

**Comment by mhardcastle** [comment]
Good, closing this for now.
