### ISSUE TITLE
ms2dynspec doesnt know what BeamModel and BeamNBand are

### ISSUE THREAD

**Issue by botteon** [mhardcastle/ddf-pipeline#151]
hi, we have this error in Bologna;

```
Running: ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2
. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel
 LOFAR --BeamNBand 1 --srclist brightlist.csv
 - 12:36:43 - AsyncProcessPool          | Fixing parent process to vthread 0
 - 12:36:43 - AsyncProcessPool          | Worker affinities not specified, leaving unset
usage: ms2dynspec.py [-h] [--ms MS] [--data DATA] [--model MODEL]
                     [--sols SOLS] [--srclist SRCLIST] [--rad RAD]
                     [--noff NOFF] [--LogBoring LOGBORING] [--imageI IMAGEI]
                     [--imageV IMAGEV] [--BaseDirSpecs BASEDIRSPECS] [--uv UV]
                     [--SolsDir SOLSDIR] [--NCPU NCPU]
ms2dynspec.py: error: unrecognized arguments: --BeamModel LOFAR --BeamNBand 1
 ______             _____                ___  ___ _____
 |  _  \           /  ___|               |  \/  |/  ___|
 | | | |_   _ _ __ \ `--. _ __   ___  ___| .  . |\ `--.
 | | | | | | | '_ \ `--. \ '_ \ / _ \/ __| |\/| | `--. \
 | |/ /| |_| | | | /\__/ / |_) |  __/ (__| |  | |/\__/ /
 |___/  \__, |_| |_\____/| .__/ \___|\___\_|  |_/\____/
         __/ |           | |
        |___/            |_|
                                 version v1.0-5-g673c0b6
 - 12:36:44 - ClearSHM                  | Clear shared memory
 - 12:36:44 - Multiprocessing           | reaping 1 shared memory objects associated with 1 dead DDFacet processes
 - 12:36:44 - ClearSHM                  | Clear Semaphores
 - 12:36:44 - ClearSHM                  | Clear shared dictionaries
FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel LOFAR --BeamNBand 1 --srclist brightlist.csv: return value is 2
Traceback (most recent call last):
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1760, in <module>
    main(o)
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1724, in main
    run(runcommand,dryrun=o['dryrun'],log=logfilename('ms2dynspec.log'),quiet=o['quiet'])
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel LOFAR --BeamNBand 1 --srclist brightlist.csv: return value is 2

```

we are using dynspec PlotVStokes  branch

**Comment by cyriltasse** [comment]
You have to use the newer version of DynSpecMS...



    Le mercredi 30 janvier 2019 à 13:09:15 UTC+1, botteon <notifications@github.com> a écrit :  
 
 
hi, we have this error in Bologna;

`Running: ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2
. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel
LOFAR --BeamNBand 1 --srclist brightlist.csv
   
   - 12:36:43 - AsyncProcessPool | Fixing parent process to vthread 0
   - 12:36:43 - AsyncProcessPool | Worker affinities not specified, leaving unset   
usage: ms2dynspec.py [-h] [--ms MS] [--data DATA] [--model MODEL]   
[--sols SOLS] [--srclist SRCLIST] [--rad RAD]   
[--noff NOFF] [--LogBoring LOGBORING] [--imageI IMAGEI]   
[--imageV IMAGEV] [--BaseDirSpecs BASEDIRSPECS] [--uv UV]   
[--SolsDir SOLSDIR] [--NCPU NCPU]   
ms2dynspec.py: error: unrecognized arguments: --BeamModel LOFAR --BeamNBand 1

| _ \ / | | / |/ |
| | | | _ _ __ \ --. _ __ ___ ___| . . |\ --.
| | | | | | | ' \ --. \ '_ \ / _ \/ __| |\/| | --. 
| |/ /| || | | | /_/ / |) | / (| | | |/_/ /
|/ _, || |_/| ./ _|__| |/__/
/ | | |
|/ ||
version v1.0-5-g673c0b6
   
   - 12:36:44 - ClearSHM | Clear shared memory
   - 12:36:44 - Multiprocessing | reaping 1 shared memory objects associated with 1 dead DDFacet processes
   - 12:36:44 - ClearSHM | Clear Semaphores
   - 12:36:44 - ClearSHM | Clear shared dictionaries   
FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel LOFAR --BeamNBand 1 --srclist brightlist.csv: return value is 2   
Traceback (most recent call last):   
File "/opt/ddf-pipeline/scripts/pipeline.py", line 1760, in    
main(o)   
File "/opt/ddf-pipeline/scripts/pipeline.py", line 1724, in main   
run(runcommand,dryrun=o['dryrun'],log=logfilename('ms2dynspec.log'),quiet=o['quiet'])   
File "/opt/ddf-pipeline/utils/auxcodes.py", line 54, in run   
die('FAILED to run '+s+': return value is '+str(retval))   
File "/opt/ddf-pipeline/utils/auxcodes.py", line 36, in die   
raise Exception(s)   
Exception: FAILED to run ms2dynspec.py --ms mslist-L602890.txt --data DATA_DI_CORRECTED --model DD_PREDICT --sols [DDS3_full_smoothed,DDS3_full_slow_merged] --rad 2. --imageI image_full_ampphase_di_m.NS.int.restored.fits --imageV image_full_low_stokesV.dirty.corr.fits --LogBoring 0 --SolsDir SOLSDIR --BeamModel LOFAR --BeamNBand 1 --srclist brightlist.csv: return value is 2   
`

we are using dynspec PlotVStokes branch

**Comment by cyriltasse** [comment]
It's with the `ApplyBeam` branch...

**Comment by botteon** [comment]
Ok thanks, we will do it
