### ISSUE TITLE
offset.py utils/get_cat.py failing

### ISSUE THREAD

**Issue by sarrvesh** [mhardcastle/ddf-pipeline#153]
I am running pipeline.py with offset correction method=panstarrs. The run failed with the following error:

Running: offsets.py tier1-jul2018.cfg
Determining astrometric offsets with method panstarrs in mode normal
Merging downloaded catalogues
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/offsets.py", line 449, in <module>
    do_offsets(o)
  File "/opt/lofar/ddf-pipeline/scripts/offsets.py", line 394, in do_offsets
    data=merge_cat(method,**kwargs)
  File "/opt/lofar/ddf-pipeline/scripts/offsets.py", line 363, in merge_cat
    t=Table.read(f)
  File "/usr/lib64/python2.7/site-packages/astropy/table/table.py", line 2521, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/astropy/io/registry.py", line 528, in read
    'read', cls, path, fileobj, args, kwargs)
  File "/usr/lib64/python2.7/site-packages/astropy/io/registry.py", line 616, in _get_valid_format
    "{0}".format(format_table_str))
astropy.io.registry.IORegistryError: Format could not be identified.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No
               ascii.aastex  Yes   Yes            No
                ascii.basic  Yes   Yes            No
                  ascii.cds  Yes    No            No
     ascii.commented_header  Yes   Yes            No
                  ascii.csv  Yes   Yes            No
              ascii.daophot  Yes    No            No
                 ascii.ecsv  Yes   Yes            No
           ascii.fast_basic  Yes   Yes            No
ascii.fast_commented_header  Yes   Yes            No
             ascii.fast_csv  Yes   Yes            No
       ascii.fast_no_header  Yes   Yes            No
             ascii.fast_rdb  Yes   Yes            No
             ascii.fast_tab  Yes   Yes            No
          ascii.fixed_width  Yes   Yes            No
ascii.fixed_width_no_header  Yes   Yes            No
 ascii.fixed_width_two_line  Yes   Yes            No
                 ascii.html  Yes   Yes           Yes
                 ascii.ipac  Yes   Yes            No
                ascii.latex  Yes   Yes           Yes
            ascii.no_header  Yes   Yes            No
                  ascii.rdb  Yes   Yes           Yes
                  ascii.rst  Yes   Yes            No
           ascii.sextractor  Yes    No            No
                  ascii.tab  Yes   Yes            No
                       fits  Yes   Yes           Yes
                       hdf5  Yes   Yes           Yes
                    votable  Yes   Yes           Yes
                     aastex  Yes   Yes            No        Yes
                        cds  Yes    No            No        Yes
                        csv  Yes   Yes           Yes        Yes
                    daophot  Yes    No            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
 - 07:33:50 - ClearSHM                  | Clear shared memory
 - 07:33:50 - ClearSHM                  | Clear Semaphores
 - 07:33:50 - ClearSHM                  | Clear shared dictionaries
FAILED to run offsets.py tier1-jul2018.cfg: return value is 1
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1745, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1598, in main
    run('offsets.py '+' '.join(sys.argv[1:]),log=None)
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run offsets.py tier1-jul2018.cfg: return value is 1

The code fails on line 363 in offsets.py. Looking at panstarrs/*.vo files, I notice that all vo files have a single line with the following message: `Please limit your access to this service to four simultaneous connections.`

I deleted the directory panstarrs and restarted pipeline.py. I got the same error again but the first 25 of the 120 .vo files had proper xml content while the rest had the same error message as before.

Would it be possible to handle this better in utils/get_cat.py?

**Comment by mhardcastle** [comment]
I assume that the PanSTARRS folks have changed how their server works.

I coded a fix for this at about 5 am this morning and am just testing it...

**Comment by mhardcastle** [comment]
Fixed by commit 8b0f56766b0cd556039464fec994652becff92be .

**Comment by botteon** [comment]
Apparently it is not working again....

```
Hex tiling image
Number of hexes across 10.645299228203394
Number of hexes up 10.618575217691854
Running: offsets.py tier1-jul2018-NVSS.cfg
Determining astrometric offsets with method panstarrs in mode normal
Merging downloaded catalogues
WARNING: W21: None:3:0: W21: vo.table is designed for VOTable version 1.1, 1.2 and 1.3, but this file is 1.0 [astropy.io.votable.exceptions]
WARNING: W42: None:3:0: W42: No XML namespace specified [astropy.io.votable.exceptions]
Traceback (most recent call last):
  File "/opt/ddf-pipeline/scripts/offsets.py", line 449, in <module>
    do_offsets(o)
  File "/opt/ddf-pipeline/scripts/offsets.py", line 394, in do_offsets
    data=merge_cat(method,**kwargs)
  File "/opt/ddf-pipeline/scripts/offsets.py", line 363, in merge_cat
    t=Table.read(f)
  File "/opt/astropy-2.0.7/lib64/python2.7/site-packages/astropy/table/table.py", line 2519, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/opt/astropy-2.0.7/lib64/python2.7/site-packages/astropy/io/registry.py", line 528, in read
    'read', cls, path, fileobj, args, kwargs)
  File "/opt/astropy-2.0.7/lib64/python2.7/site-packages/astropy/io/registry.py", line 616, in _get_valid_format
    "{0}".format(format_table_str))
astropy.io.registry.IORegistryError: Format could not be identified.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No
               ascii.aastex  Yes   Yes            No
                ascii.basic  Yes   Yes            No
                  ascii.cds  Yes    No            No
     ascii.commented_header  Yes   Yes            No
                  ascii.csv  Yes   Yes            No
              ascii.daophot  Yes    No            No
                 ascii.ecsv  Yes   Yes            No
           ascii.fast_basic  Yes   Yes            No
ascii.fast_commented_header  Yes   Yes            No
             ascii.fast_csv  Yes   Yes            No
       ascii.fast_no_header  Yes   Yes            No
             ascii.fast_rdb  Yes   Yes            No
             ascii.fast_tab  Yes   Yes            No
          ascii.fixed_width  Yes   Yes            No
ascii.fixed_width_no_header  Yes   Yes            No
 ascii.fixed_width_two_line  Yes   Yes            No
                 ascii.html  Yes   Yes           Yes
                 ascii.ipac  Yes   Yes            No
                ascii.latex  Yes   Yes           Yes
            ascii.no_header  Yes   Yes            No
                  ascii.rdb  Yes   Yes           Yes
                  ascii.rst  Yes   Yes            No
           ascii.sextractor  Yes    No            No
                  ascii.tab  Yes   Yes            No
                       fits  Yes   Yes           Yes
                       hdf5  Yes   Yes           Yes
                    votable  Yes   Yes           Yes
                     aastex  Yes   Yes            No        Yes
                        cds  Yes    No            No        Yes
                        csv  Yes   Yes           Yes        Yes
                    daophot  Yes    No            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
 - 21:31:41 - ClearSHM                  | Clear shared memory
 - 21:31:41 - ClearSHM                  | Clear Semaphores
 - 21:31:41 - ClearSHM                  | Clear shared dictionaries
FAILED to run offsets.py tier1-jul2018-NVSS.cfg: return value is 1
Traceback (most recent call last):
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1760, in <module>
    main(o)
  File "/opt/ddf-pipeline/scripts/pipeline.py", line 1613, in main
    run('offsets.py '+' '.join(sys.argv[1:]),log=None)
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run offsets.py tier1-jul2018-NVSS.cfg: return value is 1

```

**Comment by mhardcastle** [comment]
Have you pulled the latest version in the past 10 days?

**Comment by botteon** [comment]
Yes, last pull is ~20 min ago

**Comment by mhardcastle** [comment]
Well, that's odd, because the current version of merge_cat should tell you what file it failed on. Your line numbers are consistent with having an old version.

**Comment by botteon** [comment]
Yes, I forgot to delete the panstarrs directory of the previous run (thanks Tim!). Not it seems to be working! False alarm...

**Comment by mhardcastle** [comment]
Well, you only needed to delete the bad files, and I still don't think you can be running the latest version, so there's some possibility that it still won't work when the download's finished. But OK, we'll see what happens.

I am arranging a much better solution to the PanSTARRS download problem, it's just going to take a little time.

**Comment by mhardcastle** [comment]
OK, the long-term fix is to switch to using `[offsets] method=pslocal` in the config file. This gets all the PanSTARRS information from a server 'local' to the project, i.e. my webserver at Herts. I have set things up so that the retrieval from here is as efficient as it can be, i.e. only the necessary information is transferred, but am storing all the PanSTARRS DR1 catalogue -- about a billion optical objects above our detection threshold -- so we can do more if we need to later.

The only downside is that it introduces a new dependency, on astropy-healpix (which I use to tile the sky). Version 0.3.0 of this works for me. Newer versions depend on upgrades of astropy that we can't install because of the Python 2/3 issues.

If you can't install this for some reason then the old panstarrs method should still work. If you want to give the pslocal method a try, please pull.
