### ISSUE TITLE
maximum recursion  depth exceeded while calling a python object

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#154]
Perhaps more appropriate for the DDFacet github but here is an error I encounter when I have pretty large but not huge islands. The field has two large approximately circular islands one with a radius of 0.25deg and the other with a radius of 0.1deg.

[ddfacet-recursion-depth.log](https://github.com/mhardcastle/ddf-pipeline/files/2844684/ddfacet-recursion-depth.log)

**Comment by mhardcastle** [comment]
I've now got this problem in the low-res imaging of the Perseus field. Did you solve it?

**Comment by cyriltasse** [comment]
This shows when there's an overwhelming number of islands, can you check the latest `DDFacet` generated mask.fits?

**Comment by twshimwell** [comment]
I thought we “fixed” this by making use of the manual mask option to stop big regions of emission getting split into billions of different bits

**Comment by mhardcastle** [comment]
Don't really want to use a manual mask in the DR2 processing if we can avoid it. The failure in my case is at the _low_m stage, here's the _low_im image and the latest mask. Looks like the code is masking in sidelobes of Perseus and other bad regions...

![ds9](https://user-images.githubusercontent.com/5337708/57764499-7e56d700-76fb-11e9-89a6-aabc2d209f05.png)

**Comment by cyriltasse** [comment]
I did a modification of `MakeMask` to fix that, let me push perhaps

**Comment by cyriltasse** [comment]
can you checkout/pull `ddf_pipeline_fixes_may18_Galactic`, remake the mask and see how it is?...

**Comment by mhardcastle** [comment]
Testing this now.

**Comment by mhardcastle** [comment]
So the mask now has a much larger number of islands, but some of the ones on large bad regions of the map are gone. Should see whether the problem with DDF recurs in the next half an hour or so.

**Comment by mhardcastle** [comment]
... OK, it gets to the next stage and then fails.

```
 - 20:22:32 - ClassIslandDistanceMachin | [4.9/5.4 8.5/9.2 17.4Gb] Searching Islands
 - 20:23:08 - ClassIslandDistanceMachin | [5.3/5.4 8.9/9.2 17.4Gb]   found 60426 islands
 - 20:23:09 - ClassImageDeconvMachine   | [5.1/5.4 8.7/9.2 17.4Gb]   selected 57490 islands [out of 60426] with peak flux > 0.000193 Jy
 - 20:23:09 - ClassIslandDistanceMachin | [5.1/5.4 8.7/9.2 17.4Gb]   calculating global islands cross-contamination
 - 20:23:09 - ClassIslandDistanceMachin | [5.1/5.4 45.8/45.8 17.4Gb]   extracting Island edges
    Calc. Dist. ............57490/57490 [================================================] 100%  - 48'22" 
 - 21:13:00 - ClassIslandDistanceMachin | [67.6/101.6 82.7/116.8 17.4Gb]   grouping cross contaminating islands...
Traceback (most recent call last):
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/DDF.py", line 387, in <module>
    main(OP, messages)
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/DDF.py", line 235, in main
    Imager.main()
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 1097, in main
    repMinor, continue_deconv, update_model = self.DeconvMachine.Deconvolve()
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 388, in Deconvolve
    self.SearchIslands(StopFlux)
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 243, in SearchIslands
    ListIslands=IslandDistanceMachine.CalcCrossIslandFlux(ListIslands)
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassIslandDistanceMachine.py", line 250, in CalcCrossIslandFlux
    ListIslandMerged.append(list(self.GiveNearbyIsland(iIsland,set([]))))
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassIslandDistanceMachine.py", line 203, in GiveNearbyIsland
    SetThisIsland=self.GiveNearbyIsland(iIsland,SetThisIsland)
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassIslandDistanceMachine.py", line 203, in GiveNearbyIsland
    SetThisIsland=self.GiveNearbyIsland(iIsland,SetThisIsland)
[...]
    SetThisIsland=self.GiveNearbyIsland(iIsland,SetThisIsland)
  File "/home/mjh/pipeline-fix/DDFacet/DDFacet/Imager/SSD/ClassIslandDistanceMachine.py", line 193, in GiveNearbyIsland
    CTh=(self.PSFCross[iIsland]>Th)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

```
etc.

**Comment by cyriltasse** [comment]
What does the mask look like now?

**Comment by mhardcastle** [comment]
Left is input MakeMask mask, right is mask01 from the current run.

![ds9](https://user-images.githubusercontent.com/5337708/57828483-95e99a80-77a3-11e9-9aa5-1538051163b1.png)

**Comment by cyriltasse** [comment]
Hey sorry I did nt have time to do any work today - just chatting about some cool LOFAR projects... Anyway - can you tell where these products are? And how you source software in herts?

**Comment by cyriltasse** [comment]
We might have to go ninja mode anyway for this field...

**Comment by mhardcastle** [comment]
Sure. It's all in `/beegfs/car/mjh/P049+41`. You should be able to `source /home/mjh/pipeline-fix/init.sh` to get the version of the software using the new branch on your path.

**Comment by mhardcastle** [comment]
Got another one of these, P264+08. I think here the short-baseline calibration is being screwed up by sources just outside the region we image. Would still be good if ddfacet didn't crash though.

**Comment by mhardcastle** [comment]
And another one of these, in a Galactic field. Gonna use sys.setrecursionlimit blindly in the hope of getting past it!

**Comment by cyriltasse** [comment]
Can you check out the mask? Maybe there's something wrong... it must be full of little islands....

**Comment by mhardcastle** [comment]
Oh it is, it's the low-resolution image of a Galactic field and there's all sorts of short-baseline junk there. But we can generally get a decent image of SNRs and such if we can just get it to run to completion. I could tweak the threshold for masking I guess, but I'd rather just see whether it can be make to run with the normal settings.

**Comment by cyriltasse** [comment]
yeah - ideally we could have a smarter algorithm for grouping islands, but the recursive call was the only solution I was seeing at the time... increasing the recursion limit might do the trick hopefully...

**Comment by mhardcastle** [comment]
Yeah, that gets it past the point where there was a problem. Of course now there are some very large islands, so it's taking its time deconvolving them, but we'll see if that works.

**Comment by cyriltasse** [comment]
Cool! Are you doing any ajustments for galactic fields? like decreasing number of directions, or cutting on short baselines?

**Comment by twshimwell** [comment]
For the Coma cluster the data looked nice with removing the uvmin in the imaging. Deconvolution was weird at full resolution though and even though the mask covered the entire coma region it wouldnt deconvolve. To get it working I instead did a kind of iterative mask bit where i masked 1/8th of the region at a time and then did the cleaning in a little loop. Pretty hacky but it did manage to clean it.

im trying the WS3 region at the moment. The same number of directions but have cut the resolution a lot because otherwise again I cant deconvolve it.

**Comment by cyriltasse** [comment]
@twshimwell did you have a go with the multiscale clean developped by Landman in SA?

**Comment by twshimwell** [comment]
Yeh I had tried it in the past but wanted to try the latest version but was having issues building the latest ddfacet in leiden

**Comment by mhardcastle** [comment]
Well, the original problem is fixed by putting 
```
sys.setrecursionlimit(10000)
```
in straight after `import sys` in DDF.py. Hacky but it works.

I can't post the image here because it's proprietary (Tim: this is PNK3-17), but the Galactic plane is nuts at 6 arcsec. Loads of weird structure in what I assume are SNR. Obviously doesn't calibrate so well away from compact sources...

**Comment by twshimwell** [comment]
Quite a crazy image! :) I think the pipeline has done quite well given just standard settings and the complexity of the field. The residual map looks not too bad.

By comparison the im doing on W3 where the emission is much larger looks pretty good for the main source but its too big to deconvolve well with SSD even at 25" resolution it seems.

**Comment by mhardcastle** [comment]
I have the latest DDF working* here in a Python 3 singularity image -- could try the multiscale clean as an alternative to SSD here, if you want. We could presumably just make this an option in ddf-pipeline and things should just work?

[*] working except for the bunch of bugs we haven't fixed yet, that is.

**Comment by cyriltasse** [comment]
Now you make me want to see that image... :))

**Comment by twshimwell** [comment]
Oh great. Can I use a node on Herts? Alternatively, I can just copy your singularity image to Leiden?

**Comment by twshimwell** [comment]
/net/lofar9/data2/shimwell/W3-region/L544363 for the W3 one

**Comment by mhardcastle** [comment]
Yeah, you can use a node here if you like (because that means it's easier to fix if something doesn't work -- and I have been building DDF et al outside the singularity).

E-mail me...

**Comment by mhardcastle** [comment]
Fix pushed to a DDF branch in the process of being merged, closing this!
