### ISSUE TITLE
archiving bootstrap results

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#155]
Was wondering if we should archive bootstrap results for the lotss images. It might be useful for sanity checks later on.

**Comment by mhardcastle** [comment]
Bit late now! But yes, we should have been doing this.

**Comment by twshimwell** [comment]
seeing the commit. Do we also want (/would have wanted) *cross*fits so we have the catalogues?

**Comment by mhardcastle** [comment]
Yeah, added that now too.
