### ISSUE TITLE
Same Frequency in all Band0,1,2 images

### ISSUE THREAD

**Issue by sabourke** [mhardcastle/ddf-pipeline#156]
The Band0,1,2 fits images all claim to be at 144.63 MHz. Can you tell me what the real frequencies are?

**Comment by mhardcastle** [comment]
Yes, this is a DDFacet bug, see issue #57. The frequencies are in the .cfg file used for the processing, but they default to 128.0, 143.7, 160.2 MHz.

**Comment by sabourke** [comment]
Ok, cheers.
