### ISSUE TITLE
Imaging weights for initial imaging

### ISSUE THREAD

**Issue by wllwen007** [mhardcastle/ddf-pipeline#158]
this is more of a question than an issue really (and maybe a naive one at that):

The first imaging steps are done with Weight-ColName='None' so essentially equal weights. Why not use WEIGHT_SPECTRUM? and are the weights in WEIGHT_SPECTRUM considered when the KMS solutions are used to produce the weights in IMAGING_WEIGHT?

(in a way this was actually helpful in revealing some bad unflagged but down weighted data...)

**Comment by cyriltasse** [comment]
Yeah - this is a better way indeed... Do you know is `WEIGHT_SPECTRUM` generated?

**Comment by wllwen007** [comment]
Yeah ... `WEIGHT_SPECTRUM` is generated by DPPP -- originally it is based on the autocorrelations (inverse to the variance in the autocorrelations of the raw data), and updated in prefactor when the major amplitude corrections (beam, bandpass) are made

**Comment by mhardcastle** [comment]
So do we know if using WEIGHT_SPECTRUM in DDF actually works?

**Comment by wllwen007** [comment]
> So do we know if using WEIGHT_SPECTRUM in DDF actually works?

Seems to, at least for the dirin steps, and for LBA makes an improvement in the image. I tried also on one of the low-dec gama fields in HBA -- not much difference there (unsurprising since the HBA weights don't vary that much, while the LBA weights quite strongly depend on the bandpass)

LBA
(l) with -Weight-ColName="WEIGHT_SPECTRUM" ; (r) with -Weight-ColName="None"
![image](https://user-images.githubusercontent.com/2170761/55721094-bedb7a80-5a02-11e9-9d24-f062084a2115.png)

HBA (Gama field)
(l) with -Weight-ColName="WEIGHT_SPECTRUM" ; (r) with -Weight-ColName="None"
![image](https://user-images.githubusercontent.com/2170761/55721129-d3b80e00-5a02-11e9-962a-303f5f7447b0.png)

**Comment by mhardcastle** [comment]
In that case I'd be happy to have this put in as an option in the pipeline, if you like?

**Comment by wllwen007** [comment]
I've added an option in the parset `use_weightspectrum` (defaults to False) that will use the WEIGHT_SPECTRUM instead of None when not using the kMS IMAGING_WEIGHTS  ... if you're happy with that you can merge the pull request

**Comment by mhardcastle** [comment]
Merged the PR and closing. If we don't think there is much benefit from using this by default for the HBA I won't change the LoTSS parsets for now.
