### ISSUE TITLE
reimaging

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#16]
Would be nice to have a reimaging pipeline so that people can easily reimage their favourite galaxy cluster using their favourite imager.

This could use the final dicomodels to subtract the sources away from the source of interest. The solutions in the direction of the source could be applied and the data could be averaged with some tolerance of time and bandwidth smearing to allow for easy reimaging.

**Comment by twshimwell** [comment]
Just 1.5 years later... but a script is now in the repository to do this -- sub-sources-outside-region.py

The kms calibration bit is still being tested.

**Comment by mhardcastle** [comment]
Could we document the reimaging script, then we could close this?

**Comment by mhardcastle** [comment]
We did document this, so now I'm closing this issue, better late than never!
