### ISSUE TITLE
Big dot in the centre of an image

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/ddf-pipeline#162]
I am running the pipeline in all the datasets of ELAIS-N1. In the imaging step between DIS2 and DDS3, the output image is completely wrong. There is a huge dot in the centre with a density flux of 10^22 Jy/beam. 

I have been chasing the problem and it looks to be related to one of the datasets (029). When running the following command I can find the big dot as well:
```
DDF.py --Output-Name=image_full_ampphase_di_029-locked --Data-MS=/home/jsm/repos/cuillin_processing/ddf_config/big-mslist-029.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA_DI_CORRECTED --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.500000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=/data/jsm/ddf-deep-cycle2and4 --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --GAClean-AllowNegativeInitHMP True --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 6.000000 --Weight-ColName="IMAGING_WEIGHT" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=5.00 --Mask-External=image_ampphase1_di_m.mask01.fits --DDESolutions-GlobalNorm=None --DDESolutions-DDModeGrid=AP --DDESolutions-DDModeDeGrid=AP --DDESolutions-DDSols=DDS2_full_smoothed --Predict-InitDicoModel=image_ampphase1_di_m.DicoModel --Selection-UVRangeKm=[0.100000,1000.000000] --GAClean-MinSizeInit=10 --Beam-Smooth=1 --Misc-ConserveMemory=1
```

Now the weird part. The solutions do not look particularly bad but there are a couple of bands that may be a bit noisy (004 and 005). I divided the bands in the upper and lower part and it confirmed that the spot appears in the lower part. However, when I divided the lower part in two bands again, the problem was not there anymore (!). Both images (including the one containing the noisy bands) where OK. I tried then to image all the bands but remove 004 and 005 and the spot was there again. The weird part is that dividing the dataset in 4 frequency chunks the problem is not there. I checked that the option Misc-ConserveMemory=1 (that I have started to use) is not related to that.

In the images affected you can see how the model is perfectly OK but the residual part is the one containing the big spot:
![p029-model](https://user-images.githubusercontent.com/215599/53800769-60b80500-3f35-11e9-9c67-93124cc27c52.png)
![p029-dirty](https://user-images.githubusercontent.com/215599/53800772-6281c880-3f35-11e9-8bf2-3293fc629bf9.png)

I am continuing with the processing without the dataset 029 but this problem looks like something that could be worth to investigate. Have you seen something like this before? Any idea of the origin of this?

I am using the branch ddf_pipeline_fixes_may18 of DDFacet.

**Comment by cyriltasse** [comment]
Nope - Never seen anything like this before... Keep us updated!...

**Comment by mhardcastle** [comment]
OK to close this Pepe?

**Comment by nudomarinero** [comment]
Only observed once. Probably better to close unless someone else finds it again.
