### ISSUE TITLE
Bootstrap crash

### ISSUE THREAD

**Issue by tvanhateren** [mhardcastle/ddf-pipeline#164]
Hi,
I am testing my setup of the ddf-pipeline (DR1 branch) by running it on a calibrator observation.
Specifically L151880 from the lofar long term archive.
However the process is crashing in the bootstrapping stage:
[image_bootstrap_L151880.log](https://github.com/mhardcastle/ddf-pipeline/files/2946079/image_bootstrap_L151880.log)

**Comment by twshimwell** [comment]
Looks like many of your images are blank (because --Freq-NBand=61 where we normally have 6).

What config file are you feeding the pipeline?

**Comment by tvanhateren** [comment]
The config file is just the standard tier1.cfg with the path adjusted for the local environment
[151880.txt](https://github.com/mhardcastle/ddf-pipeline/files/2946209/151880.txt)

**Comment by twshimwell** [comment]
and the mslist.txt and big-mslist.txt what are those ones? Are the input data 10subband blocks of data?

This simply gets the nfreqs for

        freqs=[]
        mss=[l.rstrip() for l in open(mslist).readlines()]
        for ms in mss:
            t = pt.table(ms+'/SPECTRAL_WINDOW', readonly=True, ack=False)
            freq=t[0]['REF_FREQUENCY']
            if freq not in freqs:
                freqs.append(freq)
channels=len(freqs)

**Comment by mhardcastle** [comment]
Yeah, must be the mslist.txt.

**Comment by tvanhateren** [comment]
I have generated the mslists using the make_mslists script.
The bit of code does result in 61 channels

**Comment by twshimwell** [comment]
what is the input data that you are giving it? Normally we use the products of the prefactor pipeline. This is ~25 10subband datasets. It is not e.g. a 240 1subband datasets.

**Comment by tvanhateren** [comment]
I am also using the output from prefactor.
Ahh, I see. I am directly imaging the calibrator. Which means I skipped the Pre-Facet-Target.parset which performs the concatenation to 10 subbands per group.

**Comment by twshimwell** [comment]
Ah ok goodo. I'll close this issue for now then.
