### ISSUE TITLE
LBA DI time/freq solution intervals

### ISSUE THREAD

**Issue by wllwen007** [mhardcastle/ddf-pipeline#168]
I've been running ddf-pipeline on a test LBA DI-calibrated dataset that Francesco has produced (phases transferred from simultaneous calibrator and then TEC solutions against a GSM model (TGSS with spec indicies) so the initial DI calibration is about as good as it gets).

I'm running with the full mslist (24 ms's each 2MHz wide with 40 channels, 4s) from the start, and only using 15 directions to start off with.
The DD steps in ddf-pipeline seem to bring some improvement, but the DI steps make things worse.

top left-right: dirin, dirin di, phase1
bottom left-right: amphase1, ampphase1 di
![image](https://user-images.githubusercontent.com/2170761/55633681-30c28280-57bd-11e9-810a-04167693ea2d.png)

I think the issue may be in the solution intervals for the DI step:
give_dt_dnu is very optimistic about what S/N it should get (I thought it should be estimating the expected signal based on the model visibility column, but it seems to be getting this from the data visibilities -- there is about a factor 5 difference in the mean of my DATA amplitude and the mean of the DD_PREDICT amplitude) and as a result it's setting NChanSols to be 4 with dt of about a minute, and the solutions look pretty noisy. I think typical HBA observations have NChanSols of only 2 or 1.

Solutions for BAND10 around 55MHz (CS013, CS031, and RS310 are flagged), with 4 solutions in freq.
![killMS DIS0 sols-iDir0-A](https://user-images.githubusercontent.com/2170761/55637103-9c5c1e00-57c4-11e9-9278-f17022df2e33.png)
![killMS DIS0 sols-iDir0-P](https://user-images.githubusercontent.com/2170761/55637104-9c5c1e00-57c4-11e9-8c7f-7956772a5abb.png)
(assuming I've plotted these correctly, based on PlotSols)

I've tweaked it to force it to try for a higher S/N (manually using T=20)
top l-r: dirin, dirin di(T=10)
bottom l-r: dirin dirin di (T=20)
![image](https://user-images.githubusercontent.com/2170761/55634896-b7785f00-57bf-11e9-9e1e-e45fa8b10133.png)
this seems promising, though maybe not perfect.
(note one other difference here is that I the dirin image in the bottom left is made using the Weight-ColName in WEIGHT_SPECTRUM, but the dirin di image would be using the IMAGING_WEIGHT after kMS has been run)

Solutions for the same band, now with NChanSols=2
![killMS DIS0 sols-iDir0-A](https://user-images.githubusercontent.com/2170761/55637350-1e4c4700-57c5-11e9-8cbc-4bb5346f989d.png)
![killMS DIS0 sols-iDir0-P](https://user-images.githubusercontent.com/2170761/55637349-1e4c4700-57c5-11e9-823c-669fd0c78d48.png)

**Comment by mhardcastle** [comment]
@cyriltasse should probably comment on the give_dt_dnu algorithm...

**Comment by rvweeren** [comment]
Would it not be better to only run the DD step? Or is your point that that the DI step at least should not make things worse? (I can imagine the the DD errors are larger in LBA than in HBA so that one might not get much further improvement in a DI step after a "simple" DI TEC fitting against a GSM)

**Comment by wllwen007** [comment]
> Would it not be better to only run the DD step? Or is your point that that the DI step at least should not make things worse? (I can imagine the the DD errors are larger in LBA than in HBA so that one might not get much further improvement in a DI step after a "simple" DI TEC fitting against a GSM)

yeah, the point is that the DI step should not really make it that much worse

**Comment by cyriltasse** [comment]
I should take a look - maybe it's a bug...

**Comment by wllwen007** [comment]
> I should take a look - maybe it's a bug...

@cyriltasse shouldn't this line
https://github.com/mhardcastle/ddf-pipeline/blob/5abf65fa94af9627ccc57ef2d02bf9d70d16c4fa/scripts/pipeline.py#L659
perhaps reference the model data column to estimate the signal, i.e. something like:
`da=np.abs(p[:,:,0][f[:,:,0]==0])`

(I don't fully understand why for the LBA I have about a factor of 5 difference between the median amplitude of the Model and Data columns)

**Comment by mhardcastle** [comment]
Fixed by #203 for practical purposes, so closing.
