### ISSUE TITLE
MakeCatalog and images without sources

### ISSUE THREAD

**Issue by botteon** [mhardcastle/ddf-pipeline#169]
Hi, I am processing a LoTSS pointing and it crashed when ClusterCat.py is run. 
Apparently the `image_dirin_SSD*restored.fits` images have no sources, indeed MakeCatalog.py ends with this error:
```
No sources were found in the image. Output file not written.  
No sources were found in the image. Output file not written.  
No sources were found in the image. Output file not written.  
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsm_rms.fits'
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsm_mean.fits'
```
and ClusterCat.py complains about not finding `image_dirin_SSD_m.app.restored.pybdsm.srl.fits`.

I tried to process another field and I got stuck at the same step, although this time MakeCatalog.py ended with 
```
--> Wrote FITS file 'image_dirin_SSD_m.app.restored.pybdsm.srl.fits'
--> Wrote FITS file 'image_dirin_SSD_m.app.restored.pybdsm.gaul.fits'
--> Wrote BBS sky model 'image_dirin_SSD_m.app.restored.pybdsm.sky_in'
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsm_rms.fits'
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsm_mean.fits'
```
Note however that `image_dirin_SSD_m.app.restored.pybdsm.srl.fits` has only two rows, and the last output of ClusterCat.py is

```
Running: ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_di
rin_SSD_m.npy.ClusterCat.npy --NCluster 45
 - 04:47:23 - ClusterImage              | Reading image_dirin_SSD_m.app.restored.pybdsm.srl.fits
 - 04:47:23 - ClusterImage              | Image center: 13:29:03.650 +59:54:03.672
 - 04:47:23 - ClusterImage              | Reading source catalog image_dirin_SSD_m.app.restored.pybdsm.srl.fits
 - 04:47:23 - ClusterImage              | Merging sources...
 - 04:47:23 - ClusterImage              | Have merged 2 -> 1
 - 04:47:23 - ClusterImage              |   Seleted 1 sources [out of 1] with flux density > 0.030000 Jy
 - 04:47:23 - ClusterImage              | Reading polygon file: MaskDiffuse.pickle
 - 04:47:23 - ClusterDEAP               | Initialise population
/opt/DDFacet/lib/python2.7/site-packages/DDFacet/ToolsDir/GeneDist.py:87: RuntimeWarning: invalid value encountered in divide
  D/=D[-1]
Traceback (most recent call last):
  File "/opt/DDFacet/SkyModel/ClusterCat.py", line 337, in <module>
    main(options=options)
  File "/opt/DDFacet/SkyModel/ClusterCat.py", line 329, in main
    CIM.Cluster()
  File "/opt/DDFacet/SkyModel/ClusterCat.py", line 274, in Cluster
    xyNodes,self.LPolygon=CC.Cluster()
  File "/opt/DDFacet/SkyModel/Sky/ClassClusterDEAP.py", line 220, in Cluster
    self.reinitPop2(pop)
  File "/opt/DDFacet/SkyModel/Sky/ClassClusterDEAP.py", line 199, in reinitPop2
    indSel=DDFacet.ToolsDir.GeneDist.GiveNonRedundantSample(self.S,self.nNode)
  File "/opt/DDFacet/lib/python2.7/site-packages/DDFacet/ToolsDir/GeneDist.py", line 48, in GiveNonRedundantSample
    iSel=int(round(DM.GiveSample(1)[0]))
ValueError: cannot convert float NaN to integer
```

**Comment by cyriltasse** [comment]
Did you look at the image?

**Comment by botteon** [comment]
Yes, in both cases there are no sources

**Comment by cyriltasse** [comment]
ok! That explains why `ClusterCat.py` won't work then! :) Why is there no sources then? Is it just zeros, or just noise? or what?

**Comment by botteon** [comment]
They are noise-like

[first field](www.ira.inaf.it/~botteon/image_dirin_SSD.app.restored_2.fits)

[second field](www.ira.inaf.it/~botteon/image_dirin_SSD.app.restored.fits)

the second one is "better", I can spot at least a source, indeed this is the case where MakeCatalog.py found something..

**Comment by cyriltasse** [comment]
`ddf-pipeline` can't do very much about it... @twshimwell any idea?

**Comment by twshimwell** [comment]
What is the field you are attempting to process? I suspect the DI processing is rubbish.

**Comment by botteon** [comment]
P222+60 and P202+60

Yeah, I was also suspecting that...but it would be unlucky that I picked two bad fields in a row!

**Comment by twshimwell** [comment]
DI phase solutions for P202+60 look terrible... im not quite sure why.

Are you able to take a look at the DATA column for P202+60 (just do the equivalent to the image_dirin_init step but with DATA instead of CORRECTED_DATA)? That should help diagnose a little where the problem is.

![Uploading Screenshot 2019-04-11 10.26.20.png…]()

**Comment by twshimwell** [comment]
For P222+60 the phase calibration solution plots were not uploaded for some reason. Are you able to similarly look at the DATA column for this one.

**Comment by twshimwell** [comment]
I am suspecting that all fields currently coming out of juelich are impacted like this. Not sure what is going on but maybe something is blocking or changing the downloading of the TGSS catalogues. Anyway, will be interesting to see what the DATA column looks like.

**Comment by botteon** [comment]
This is P202+60, *dirty.corr.fits images for DATA (left) and CORRECTED_DATA (right)

![Screenshot from 2019-04-11 11-14-10](https://user-images.githubusercontent.com/23218111/55945371-f76d9500-5c4a-11e9-8237-feccfda270a7.png)

**Comment by twshimwell** [comment]
Hmmm ok what a pain. Something must have changed at juelich with regards to downloading the tgss sky model without us knowing. Shame because we were just getting data through juelich for the first time in a while... hopefully we can figure it out and reprocess soon.

**Comment by twshimwell** [comment]
But at least the data look ok which is good so it’s not something fundamentally wrong with these data

**Comment by botteon** [comment]
I close this thread as it is not an issue related to ddf-pipeline

**Comment by twshimwell** [comment]
Alex Drabent has fixed this on juelich now. The impacted pointings (I think just P222+60, P202+60 and one P354+01 observation) will be rerun.
