### ISSUE TITLE
pybdsm parameters in quality control pipeline

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#17]
The pybdsm parameters to be used on the survey have been tweaked slightly (http://lofar.strw.leidenuniv.nl/wiki/doku.php?id=co-ordinated_deep_field_strategy) and could be also updated in the quality control pipeline.

**Comment by mhardcastle** [comment]
Might as well, though of course the QC results won't be used for the final cataloguing.

We should also change the QC stuff to find sources in the full field for the PanSTARRS matching.

Do you want to handle this, Tim?

**Comment by twshimwell** [comment]
To match what is presently being suggested for the catalogue making off the mosaics. I will change to

bdsm.process_image(fitsname, detection_image=detectimage, thresh_isl=4.0, thresh_pix=5.0, rms_box=(150,15), rms_map=True, mean_map='zero', ini_method='intensity', adaptive_rms_box=True, adaptive_thresh=150, rms_box_bright=(60,15), group_by_isl=False, group_tol=10.0,output_opts=True, output_all=True, atrous_do=True,atrous_jmax=4 flagging_opts=True, flag_maxsize_fwhm=0.5,advanced_opts=True, blank_limit=None)

For the final catalogue matching I gather there is still fine-tuning ofvthe rms_box_normal and jmax settings: rms_box_normal varying from 50 to 150; jmax from 4 to 6.

**Comment by mhardcastle** [comment]
Not much point in doing jmax>4 for quality control. Let's leave jmax and rms_box as they are.

**Comment by twshimwell** [comment]
OK. Ive altered the master branch to have these new parameters in the pybdsm call in quality_pipeline.py

**Comment by mhardcastle** [comment]
Thanks. Quality pipeline will need some updating to deal with the new layout of files, I'll take a look at that.

**Comment by mhardcastle** [comment]
Quality pipeline should be OK now. Closing.
