### ISSUE TITLE
Attempting to correct the LoTSS-DR2 fluxes

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#171]
Even though we bootstrap fluxes early in the calibration procedure they seem to drift during the processing. Hence, we need to correct the final Stokes I images with some factor.

Our thinking for how to do this is to 

1) Align the fluxscale of neighbouring pointings by using sources in the overlapping region

2) After pointings are aligned then apply some global correction based e.g. on comparing calibrator sources in the region, global source counts, matching another survey etc.

This ticket will discuss this and show how well it is/isnt working.

**Comment by twshimwell** [comment]
With regards to 1. I think the first issue is what exactly we want to minimise here. The way I have this coded up at the moment I try to minimise this function.

```
def chisqfunc(pointingscaling,mediandict,matchingarray):
    rollingchisq = []
    extraerror = []

    for i in range(0,len(matchingarray)):
            pointing1 = matchingarray[i][0]
            pointing2 = matchingarray[i][1]

            Flux_1 = mediandict['%s_%s'%(pointing1,pointing2)][0]
            Error_1 = mediandict['%s_%s'%(pointing1,pointing2)][1]
            Flux_2 = mediandict['%s_%s'%(pointing1,pointing2)][2]
            Error_2 = mediandict['%s_%s'%(pointing1,pointing2)][3]

	    pointing1index = pointinglist.index(pointing1)
	    pointing2index = pointinglist.index(pointing2)

	    pointing1index = np.where(tovary == pointing1index)
	    pointing2index = np.where(tovary == pointing2index)
            if np.shape(pointing1index)[1] == 0.0:
                scaling1 = 1.0
            else:
                scaling1 = pointingscaling[pointing1index[0][0]]
            if np.shape(pointing2index)[1] == 0.0:
                scaling2 = 1.0
            else:
                scaling2 = pointingscaling[pointing2index[0][0]]


            errorsquared = (Error_1*scaling1)**2.0+(Error_2*scaling2)**2.0
	    errorsquared = errorsquared
            prechi2 = np.sum(((Flux_1*scaling1)-(Flux_2*scaling2))**2.0/errorsquared)

            rollingchisq.append(prechi2)
    chisq = np.sum(rollingchisq)

    return chisq
```

Here the pointingscaling contains the scaling factor to be applied. The mediandict colums [0], [1], [2], [3] contain all cross matched values for field1 fluxes, field 1 flux errors, field 2 fluxes, field 2 flux errors. The loop goes over all fields.

**Comment by cyriltasse** [comment]
Flux Correction Ninja Task Force coming online! :)

Could we have radial dependence to the offets? I'd expect the beam model is quite wrong (even the array-factor only)... You did look at that already @twshimwell ?

**Comment by twshimwell** [comment]
A bit in the LoTSS-DR1 paper but its pretty basic stuff. I'd say more investigation on the accuracy of the beam model would be good too.

**Comment by nudomarinero** [comment]
We could try to work on the same data and compare outcomes later. I suppose that we could work on the same 9 pointings shown in the last telecon. What are those fields? Are the catalogues available for download?

**Comment by twshimwell** [comment]
To start in the most simple way im looking at 2 neighbouring fields.

The results are below. Note that the chisq (defined the same as the above) goes down as it should but the median doesnt come out at 1.0 (as expected really as this isnt what is being minimised). The third plot shows the actual data that goes into the minimisation (well not the errors) and also the approximate results (the dervied scaling factors are 1.01 and 1.18 -- here the line shows 1.18).

<img width="611" alt="Screenshot 2019-04-17 13 12 06" src="https://user-images.githubusercontent.com/12065270/56283605-8dedfa80-6112-11e9-89b9-6c503a709512.png">
<img width="610" alt="Screenshot 2019-04-17 13 12 16" src="https://user-images.githubusercontent.com/12065270/56283606-8dedfa80-6112-11e9-8328-e3a8f082a9df.png">

<img width="1486" alt="Screenshot 2019-04-17 13 23 13" src="https://user-images.githubusercontent.com/12065270/56284159-fab5c480-6113-11e9-9390-032eecbad508.png">


Note that in the cross matching I only keep isolated (>30" away from anything), S-type sources within 0.5 of the primary beam and with a signal to noise > 20. These criteria apply to both pointings in the matching.

I think this result looks good but let me know if you think it should look better.

**Comment by twshimwell** [comment]
> We could try to work on the same data and compare outcomes later. I suppose that we could work on the same 9 pointings shown in the last telecon. What are those fields? Are the catalogues available for download?

Certainly we can try working on the same data  if you want. I have the "filtered" matched catalogues for these fields. I was hoping to first discuss the procedure we wanted to use though. For example, is the chisq function that i pasted a sensible thing for us to minmise.

**Comment by twshimwell** [comment]
If I now try a more complicated problem to try aligning the pointings shown in the layout below I think the results are a bit less encouraging. Below I also plot the chisq for each overlapping pointing region (note this is not really the chisq that is minimised because I am minimising for everything together  so I just have 1 chisq but this is the chisq of just each overlapping region). The ratio of the fluxes is also shown for each of the overlapping fields.

Just to explain exactly what these plots are. The median RA of the matched sources in a cross matched catalogue of overlapping pointings is plotted against either the ratio of the Total fluxes or the chisq computed for just those overlapping pointings (this is not the chisq that is minimised but its part of it -- the chisq that is minimised is the sum of all these).

<img width="561" alt="Screenshot 2019-04-17 13 28 45" src="https://user-images.githubusercontent.com/12065270/56284488-e45c3880-6114-11e9-93a1-25620acef816.png">
<img width="1058" alt="Screenshot 2019-04-17 13 29 04" src="https://user-images.githubusercontent.com/12065270/56284489-e4f4cf00-6114-11e9-9aa0-0ec24602f57d.png">
<img width="903" alt="Screenshot 2019-04-17 13 29 24" src="https://user-images.githubusercontent.com/12065270/56284491-e4f4cf00-6114-11e9-9208-67146f701b20.png">

**Comment by cyriltasse** [comment]
Can you define what you call Chi^2?

**Comment by twshimwell** [comment]
the bit of code in the 2nd post is the chisq

**Comment by twshimwell** [comment]
I guess the chisq i have used is very heavily weighted by bright sources like in the plot showing the results from the 11 pointings all together it does a good job minimising the big chisq but perhaps the others have negligible chisq compared to this... maybe my chisq definition is bad.

**Comment by mhardcastle** [comment]
So I suppose what you want to minimize is the differences between pairwise scaled fluxes across all fields. I think that's sort of what you're doing there, though I can see it's not going to be very efficient.

**Comment by twshimwell** [comment]
Yeh as you can imagine the dictionaries that are passed to this chisq function get huge if there are lots of pointings.

**Comment by mhardcastle** [comment]
What you really want is a contribution to chi^2 (or some other figure of merit, doesn't matter really) for each field based on the scaling for that field. And that shouldn't really be biased towards bright sources because the scaling factor is not dependent on the brightness of the source.

**Comment by cyriltasse** [comment]
Could we instead work on a scaling free metric telling us how good all 2-pointings sources would agree if the two pointings were best matched? If the beam model would be correct then then would distribute around 0?

**Comment by twshimwell** [comment]
Wouldnt we still have the issue of how we define whether a pointing is well aligned with the neighbouring one. For example, in the plot below shows fluxes in neighbouring fields on a linear scale and they are quite all over the place...


<img width="1478" alt="Screenshot 2019-04-17 14 05 55" src="https://user-images.githubusercontent.com/12065270/56286425-f68ca580-6119-11e9-8c74-628b417669ed.png">

**Comment by cyriltasse** [comment]
Assuming there is a huge scaling factor F, what happens if you plot just two pointings? Apart from the overall shift F, and the individual error bars, what would be left is the beam model error, right?...

**Comment by twshimwell** [comment]
Yeh and if we cutoff at 0.5 of the beam we are indeed going out to large radius where smearing also becomes an issue -- id be surprised if this didnt dominate over beam errors but im not sure about that. For example in LoTSS-DR1 we found whats shown below and 0.5 of the beam is about 2.1-2.2deg from the pointing centre. Even though here all the sources are deconvolved with the smeared psf I guess there is still some increased smearing caused by e.g. facets being larger away from the pointing centre and this will probably play a big role in the alignment too -- say 20% error.

<img width="451" alt="Screenshot 2019-04-17 14 16 00" src="https://user-images.githubusercontent.com/12065270/56287135-dc53c700-611b-11e9-92c8-bcc5e169930b.png">

**Comment by mhardcastle** [comment]
So I think Philip's right that we need to go less far down the beam. In addition to smearing there's just the fact that the sources down the beam are likely to have far crappier phase solutions because of the SNR -- you can see this on any field image.

All other things being equal brighter (true flux) sources are going to be further down the beam because there's more area there, so perhaps not surprising that we see such big factors at the high flux end in your plot above.

**Comment by mhardcastle** [comment]
(also the effect of being limited by the calibration is that you are DR limited, hence you have a fixed fractional error not a noise associated with the source, hence bright sources are no better than faint sources for determining the scale factor)

**Comment by twshimwell** [comment]
Yeh I was thinking to incorporate some fractional error in the Errors_1 and Errors_2 -- say 10%. This would kind of have the effect of making bright sources contribute less to the chisq value.

I'll spend some time looking at images of the sources and seeing if there is something obvious what some measurements are so different. I'll also try an even high pb cut.

**Comment by twshimwell** [comment]
This is proving pretty fiddly with the source selection and ive tried various different pb cuts and different ways to filter the sources used for the alignment. However, i've not really come across something satisfactory yet using this technique.

I wonder if its worth trying something a bit fancier. It seems that for aligning colourscales in pictures quite a common procedure is histogram matching. Maybe something like this is worth trying. It takes a little bit to setup as I need to filter out all the noise pixels first and also make common masks of the overlapping regions.

**Comment by mhardcastle** [comment]
I'm not sure how this would be expected to give a different result, fundamentally?

**Comment by twshimwell** [comment]
No ive since given up on that approach. I'm not using similar to the first approach but instead of using source catalogue values im using pixel values from regions within the source mask (I could also use model values). Not sure if its going to work any better but am doing some runs now.

**Comment by twshimwell** [comment]
OK i think im getting some decentish results now. I've only trying a small number of fields though with my tests just being on a region of 3 mosaics which corresponds to 12 pointings and 18 overlapping regions so just a very small region of DR2.

The procedure is:

(a) use standard mosaicing script but with a beamcut of 0.7 -- this provides reprojected maps for each pointing and a pybdsf source mask of the final mosaic (where the mosaic is the size of just 1 pointing but includes all neighbouring pointings)
(b) using the pybdsf source mask and the reprojected maps for each pointing find pixels that are in the mosaic mask for each pointing i.e. for every overlapping region the same pixels are selected from each of the overlapping pointings
(c) try to minimise the reduced chisq of the differences in the pixel values for all overlapping pointings together (note the results from this are a bit dependent on the error as if you put e.g. a 10% of the total flux error it essentially the brighter pixels significantly so is much more influenced by faint pixels).

Plots from my results (which have not quite converged but are nearly there) are in https://www.dropbox.com/s/dqqs97d9w2vizic/results.tar?dl=0

But to summarise a few:

The values of corresponding pixels in P19Hetdex and P15Hetdex. The red is before the correction factor is applied and the green is afterwards. There is a plot like this for each overlap of two pointings.
![P19Hetdex17_P15Hetdex13](https://user-images.githubusercontent.com/12065270/56585148-8a101b80-65dd-11e9-946c-12614c184ed7.png)

The values of all overlapping pixels. Red before correction and green afterwards.
![ALL](https://user-images.githubusercontent.com/12065270/56585596-6ef1db80-65de-11e9-8ad4-12e2d0b10b69.png)

The median of each overlapping region (ignore that all regions are shown twice).  Again red is before correction and green is afterwards.
![ALL_RATIO_MEDIAN](https://user-images.githubusercontent.com/12065270/56585645-892bb980-65de-11e9-9390-56599dfe4c04.png)

I think this looks quite encouraging but I dont think it will scale nicely to do the entire big DR2 region in one go (i'll try adding some more mosaics now and see how it looks).

**Comment by mhardcastle** [comment]
I like this approach. It cuts the effects of different PyBDSF Gaussian fitting out of the equation. And I agree that the results look encouraging.

I'm sure we can optimize things to get this (or anything else) to scale to DR2 sizes once the proof of principle code is there.

**Comment by twshimwell** [comment]
Ah its running much faster now (who would have thought you could just do e.g. mpiexec -n 32 to make it much faster).

I'm trying now ~30 mosaics. This consists of ~85 unique observations and ~320 different overlapping regions. So its quite a big run.

**Comment by mhardcastle** [comment]
Yeah, mcmc stuff is very parallelizable out of the box. We have plenty of CPUs to play with when we want to get all the way to 200 mosaics.

**Comment by twshimwell** [comment]
Doing around 30 unique observations took around 9hrs on 32cpus. 

The results are all in https://www.dropbox.com/s/odurpp2czphnb9x/results-6.tar?dl=0 if anyone wants to see. 

I think this still looks quite good. A few plots pasted below too.

The median ratio as a function of RA of the overlapping region

![ALL_RATIO_MEDIAN](https://user-images.githubusercontent.com/12065270/56847019-7662fe80-68d6-11e9-8a44-3d69eb97de33.png)

The median ratio as a function of RA and DEC after correction

![ALL_RA_DEC_postmeds](https://user-images.githubusercontent.com/12065270/56847035-91357300-68d6-11e9-8fd7-063d385209d5.png)

Same as above but before correction

![ALL_RA_DEC_premeds](https://user-images.githubusercontent.com/12065270/56847038-97c3ea80-68d6-11e9-8c4c-2e7531fd9496.png)

**Comment by twshimwell** [comment]
Oh and an interesting plot is looking at the derived scaling factors as a function of RA and DEC. Strange patterns...

![ALL_RA_DEC_scalings](https://user-images.githubusercontent.com/12065270/56847059-d35eb480-68d6-11e9-8631-51b5cdfb04ce.png)

**Comment by cyriltasse** [comment]
Many things could generate the plot above, but you'd expect to bootstrapping to wash out any tendency generated by beam model in the solution transfer... Weird... 

I dreamt I was at a conference drinking pints of beer with @mhardcastle and @twshimwell . In a moment of enthousiasm I was saying we could actually use the noise in the residual cross pols visibilities (that maps to the Galactic emission) to calibrate for the absolute flux! :) Now I think about it, this is an original and simple idea, I've never though of it in these terms! It might not work for various reasons, but it's interesting...

I'm off to hollidays, this all looks very encouraging @twshimwell

**Comment by mhardcastle** [comment]
Yeah, this looks very hopeful.

I am beginning to wonder if the bootstrapping is even being applied properly. With all the messing around with column names in the new pipeline version it's completely possible that something weird is going on.

Pending Cyril's dream solution perhaps we should look at the flux consistency after the bootstrap in individual runs a bit more. (Although what Tim's plot is showing *could* just be the crappy WENSS flux scale, which bootstrap is tied to...)

**Comment by twshimwell** [comment]
For some reason im struggling to scale this up much more. Somehow nans are getting derived as the best alignment factor... I've no idea how this can happen with the code. Now trying catching nans and setting them to inf but would be nicer to understand how they get there in the first place.

Its odd because if i e.g. analyse say 80 pointings together then i might get a nan for some overlapping pointing. If I look at that overlapping pointing I see nothing unusual at all though and if i e.g. try 30 pointings around that region i dont get any nans.

**Comment by twshimwell** [comment]
maybe pymultinest isnt the best tool for when the number of dimensions is very large (?). I'll try something else like emcee.

**Comment by twshimwell** [comment]
Yeh seems impossible to catch nans in the code as everything turns to nans.

**Comment by mhardcastle** [comment]
Must be possible to find out when a NaN first appears and why?

I think multinest should be fine for this in principle...

**Comment by twshimwell** [comment]
Yeh it surely must be possible. I have it running with 76 free parameters and its fine but going much higher and im getting the nans come in.

I was wondering if its related to https://github.com/JohannesBuchner/PyMultiNest/issues/86. I also get to 400 samples before i get nans. I tried switching from pymultinest.run to pymultinest.solve already as thats a bit safer and it didnt fix the issue.

**Comment by twshimwell** [comment]
But it could easily be simply my horrible coding. I'm trying emcee now.

I'll tidy up my code too so perhaps someone else can take a look at it and see if they see something silly im doing.

**Comment by twshimwell** [comment]
Many thanks @mhardcastle for making this much fast and not produce nans when doing big fields anymore. 

The improved emcee code now gives results for the entire big DR2 region in less than 30 mins.

The results are kind of summarised in the plot below where the median ratio of the overlapping pixels is plotted for each overlapping region. Red is before any correction and green is after the correction. The standard deviation of these median values is 0.1266 before any correction and 0.113 after correction. So the standard deviation of these medians doesnt improve greatly but it does improve a bit (this isnt what is being mimised its just a different way of looking at whether its working or not).

All the results are in ﻿https://www.dropbox.com/s/hj7j9mg88ip93hl/results-30.tar?dl=0

What do you think?

![ALL_RATIO_MEDIAN](https://user-images.githubusercontent.com/12065270/57177447-d07a3b80-6e63-11e9-8d87-5eb85b169274.png)

**Comment by twshimwell** [comment]
Looking in the results folder you will see some pretty serious outliers -- these cross matches are made from cross matching the projected blanked maps that go into the mosaics when in some instances its clear there are pretty dramatic issues as below. Ideally these types of things wouldnt get into the mosaicing in the first place so ill see if i can see whats going wrong.

![P166+60_P169+57](https://user-images.githubusercontent.com/12065270/57177976-22be5b00-6e6a-11e9-88a8-1c203696b19e.png)

**Comment by twshimwell** [comment]
Ah ok some of this is due to the filtering I was doing to find bad pixels (where I wasnt actually applying it properly). Maybe that'll help a bit.

**Comment by twshimwell** [comment]
pretty similar results after filtering out the bad pointings. The results improve a little by doing this scaling but not that much. 

I'd be tempted to say what we are seeing is kind of expected -- its just hard to get everything aligned. If there are other suggestions though I can try those.

**Comment by mhardcastle** [comment]
How do the correction factors look as a function of sky position? Does it look as though we get anything sensible?

Is this with or without a pre-correction to the NVSS scale?

**Comment by twshimwell** [comment]
The figure below shows how they look with sky position -- not really an very odd shapes now.

Ive put all of the output images on https://www.dropbox.com/s/djvjpez7ref3g3w/results-30.tar?dl=0

This is without a pre-correction factor. I can try that now though. Do you think its better to apply the pre-correction factor or to use it as a prior?

![ALL_RA_DEC_scalings](https://user-images.githubusercontent.com/12065270/57298213-f573e600-70d1-11e9-85b3-eb04ad2c3ef2.png)

**Comment by mhardcastle** [comment]
From a coding point of view it's easier to apply it in advance. And in particular I already did that, in the `find_alignment_emcee_prescale.py` code. You just have to then remember to combine the prescaling factor with the factor the code finds...

**Comment by twshimwell** [comment]
ok ill have a bash now and compare the results.

Here by the way the std of the medians was 0.115 after apply scaling and 0.133 before applying scaling. 

I guess we have to wait for the missing field before we finalise anything which is a shame as its very uncertain how long it will take to get that field out the lta. Its on the list of things to stage but nothings really progressing this week.

**Comment by twshimwell** [comment]
There are some differences between when pre applying NVSS scaling and not pre applying. However, the overall scatter is about the same -- I got 0.115 standard deviation without pre applying, 0.118 when preapplying and 0.133 without applying any corrections.

Lots of plots if anyone is interested are in:

https://www.dropbox.com/s/hcdpzwbk4d9z4og/results-30.tar?dl=0 -- results when not pre applying

https://www.dropbox.com/s/cy1h3hxjbqnslkg/results-prescale-30.tar?dl=0 -- results when pre applying

Given its slightly simpler (and we already have quite an involved flux scaling) id be tempted to go with the option of not preapplying.

**Comment by mhardcastle** [comment]
I'm just concerned that without the pre-scaling the priors may be too narrow to pick up really discrepant fields. (But maybe there aren't really any of those. Too late to download the tar file and check tonight...)

**Comment by twshimwell** [comment]
Yeh good point would not be nice to be influenced too much by the priors. I'll also try a run increasing the prior width from 20 to 40% to see what that does.

**Comment by twshimwell** [comment]
The run with the a 40% wide prior looks pretty similar. When looking at the standard deviation of the medians I get 0.112 so its pretty similar but a tiny little bit better. I think it shows the priors are not having too much impact but perhaps it is good to have a wider prior like this just incase of serious outliers.

Results from this one are in﻿ https://www.dropbox.com/s/et6p3xt82eicuhs/results-bigprior-30.tar?dl=0

**Comment by mhardcastle** [comment]
Going to close this as we found a solution for DR2.
