### ISSUE TITLE
exitafter doesn't stop pipeline

### ISSUE THREAD

**Issue by tikk3r** [mhardcastle/ddf-pipeline#175]
Hello,

I was trying to process an observation up to e.g. the dirin step only by putting `exitafter=dirin` in the config file, and I noticed that the pipeline happily continues beyond the given point. Looking at the stop function in `pipeline.py`, it will only stop if using the database:
https://github.com/mhardcastle/ddf-pipeline/blob/fc73ac0d4d0cb7ee646ace3a32a86b6e21a22c80/scripts/pipeline.py#L59-L62
My guess is the `sys.exit` should be called outside the if statement?

Cheers,
Frits

**Comment by mhardcastle** [comment]
(Good catch)
