### ISSUE TITLE
npz file not found by killms

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#178]
Hi,

I had this posted in the other killms git, but I'm posting it here again, just make sure everybody reads it :)
And I am writing here now, since it was suggested that it might be a pipeline issue.

So, it happend again, this time again with the up to date versions of prefactor, DDFacet, KillMS and ddf-pipeline. killMS.DDS3_full_smoothed.sols.npz is not found:
`
IOError: [Errno 2] No such file or directory: '/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_120MHz.pre-cal.ms/killMS.DDS3_full_smoothed.sols.npz'`

However, the file does exist somewhere else:
"/data/amisk/killms/L583135/SOLSDIR/L583135_SB000_uv_129E8238At_120MHz.pre-cal.ms/killMS.DDS3_full_smoothed.sols.npz", which is a link to "/data/amisk/killms/L583135/DDS3_full_4998046603.005561_smoothed.npz".

It does appear that it was just created in the wrong directory, or it looks in the wrong directory.
Can I just create a link in the meantime?

**Comment by mhardcastle** [comment]
I don't understand how the file could have been created in a completely different directory!

Just to help me track this down, can you post the context from the pipeline itself (i.e. the ddf-pipeline traceback that will have been generated when killMS failed)? And also your ddf-pipeline config file?

**Comment by twshimwell** [comment]
mslist.txt and big-mslist.txt might be relevant too.

**Comment by amisk** [comment]
Which log file are you referring to? There are a lot :)

Here is a part of the big ms list:
/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_120MHz.pre-cal.ms
/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_122MHz.pre-cal.ms
/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_124MHz.pre-cal.ms
/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_126MHz.pre-cal.ms
/data/amisk/scratch/prefactor_LC7_target_L583135/results/L583135_SB000_uv_129E8238At_128MHz.pre-cal.ms

I added absolute paths so I can have the cfg file in a separate directory and run the pipeline from there. Same for the small ms list.

and here is the ddf pipeline cfg file.

```
[data]
mslist=/data/amisk/scratch/prefactor_LC7_target_L583135/results/big-mslist.txt
full_mslist=/data/amisk/scratch/prefactor_LC7_target_L583135/results/big-mslist.txt
colname = DATA

[image]
imsize=20000
robust=-0.15
psf_arcsec=12.0
final_robust=-0.5
final_psf_arcsec=6.0
do_decorr=True
low_imsize = 6000
low_psf_arcsec = 20
low_robust = -0.25
final_rmsfactor=1.0

[control]
cache_dir=/data/amisk/scratch/killms/
restart=True
bootstrap=True
polcubes=False
stokesv=False
spectral_restored=False
clearcache=False

[masking]
tgss=/data/amisk/scratch/killms/TGSSADR1_7sigma_catalog.fits
extended_size=2000
thresholds=[15,5,5,5]
rmsfacet = True

[bootstrap]
catalogues=['/data/amisk/scratch/killms/VLSS.fits','/data/amisk/scratch/killms/wenss.fits']
names=['VLSS','WENSS']
radii=[40,10]
frequencies=[74e6,327e6]

[solutions]
ndir=45
uvmin=.2
normalize=['None','None','None']
NIterKF=[6, 6, 6, 6, 6, 6, 6]
dt_slow=1.
dt_fast=0.5
dt_di=0.2

[spectra]
do_dynspec=False

[offsets]
method=panstarrs
```

**Comment by mhardcastle** [comment]
Not a logfile but the final output of the pipeline itself.

**Comment by amisk** [comment]
OK, I ran it again, and put the screen output in this file.
https://my.pcloud.com/publink/show?code=XZQ3lA7Zw90FjAcEy9Fmj96F4k5e4pnMEFUy

**Comment by mhardcastle** [comment]
OK, I guess this is something to do with your different paths for the MS files and the working directory. We never do this, so it's not supported. That said, it probably ought to work. Let me see if there's a quick fix.

**Comment by amisk** [comment]
Hmm, ok. I like to have separate input, working, and config directories.

**Comment by mhardcastle** [comment]
Well, the first thing I notice is that you're not running the current killMS version and that there's a recent(ish) change (d04db23898cec89187f100b87b05b8628f2133fa in killMS) which is relevant to the use of SOLSDIR for the smoothed files. So before you do anything else can you pull killMS (should be branch `FixQ_PowerSmooth`) and see if that solves the problem?

**Comment by amisk** [comment]
Has not crashed since 2 hours, that might have been the solution.
Thanks!

**Comment by mhardcastle** [comment]
Good stuff. If it didn't crash immediately on trying to read the .npz problem then this problem probably is solved. Closing, reopen if necessary.
