### ISSUE TITLE
Using new DDFacet and killMS

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#187]
We should make any changes to ddf-pipeline needed to use the new master versions of DDFacet and killMS.

**Comment by mhardcastle** [comment]
First issue -- I tried running new DDFacet on my test dataset (a 10-SB DR1 LOFAR dataset with killMS solutions) and get significantly worse results around some bright point sources, see image (left is new, right is old).

@cyriltasse could this be because the PSF is now calculated differently? Or do you think it's something else?
![ds9](https://user-images.githubusercontent.com/5337708/60669836-38023680-9e67-11e9-869c-b35f0d670d05.png)

Data and results in `/beegfs/car/mjh/ddftest/`

**Comment by cyriltasse** [comment]
It's been bug fixes mostly... Seems left is not deconvolved...?

**Comment by cyriltasse** [comment]
Is clustering the same?

**Comment by mhardcastle** [comment]
Yeah clustering is the same, masks are identical, and deconvolution is certainly happening in some places...

**Comment by mhardcastle** [comment]
Closing this to open a new issue on full ddf-pipeline testing.
