### ISSUE TITLE
make_extended_mask wraps sources in case of negative indices

### ISSUE THREAD

**Issue by tikk3r** [mhardcastle/ddf-pipeline#189]
https://github.com/mhardcastle/ddf-pipeline/blob/6d39b58f6c90a0ed33f6f4688a22a892413a6f4c/utils/make_extended_mask.py#L111-L117

When an index falls outside the full resolution map in a negative sense, masked regions wrap around and enter the image at a wrong position. I noticed this when using the 6'' map to make a mask for a 1'' map, which covers a much smaller area around the center.

For example, this green circle indicates the same source in the high resolution mask on the left and the low resolution mask on the right.
![masking_wrap](https://user-images.githubusercontent.com/2464769/61537562-bcdc7b00-aa37-11e9-9ba8-64f8a96f9e2e.png)

I think a positivity check on the coordinates should be enough, if I'm not mistaken.
```python
for xv,yv,op in zip(x,y,opix): 
    try: 
        if (xv>=0 and yv>=0) and (mask[int(op[1]),int(op[0])]>0): 
            maskf[yv,xv]=1 
    except IndexError: 
        # catch wcs mismatches or similar 
        pass 
```

**Comment by mhardcastle** [comment]
Good catch. Of course that is supposed to be caught by the try/except, and of course it isn't.. Wouldn't normally be a problem anyway to have a mask in the wrong place, but easy to fix.
