### ISSUE TITLE
Version mismatches

### ISSUE THREAD

**Issue by tvern23** [mhardcastle/ddf-pipeline#190]
I'm trying to run this pipeline on some LOFAR data but using the install script the killMS and DDFacet versions do not appear correct. Using https://github.com/saopicc/killMS.git , lofar-stable version  - still has the killMS.py script whereas the pipeline.py script tries to call kMS.py. 

If use the master branches of DDF and killMS from https://github.com/cyriltasse, then the ClipCal has a problem using DDF logger, "
logger.itsLog.logger.setLevel(logger.logging.CRITICAL)
AttributeError: 'module' object has no attribute 'itsLog'

" 
Not clear which version of DDF logger is compatible with this master version of killMS/ClipCal.

**Comment by mhardcastle** [comment]
For the old stable versions you need the 'stable' branch of ddf-pipeline too. (But I don't recommend that.)

Right now the latest master versions of DDF and killMS are broken in various ways for ddf-pipeline and I don't recommend those either, till we can get the bugs out. The logger problem is an open issue on Cyril's github but it's almost certainly not the only one.

So, if you have access to the repository I suggest Cyril's old development branches, DDFacet branch `ddf_pipeline_fixes_may18`  and killMS branch `FixQ_PowerSmooth`. It should be possible to modify the install script to use these branches.

Hopefully this situation will get better over the next month or so.

**Comment by tvern23** [comment]
ok well that seems to be working ok for now. thanks

**Comment by mooneyse** [comment]
Hi @mhardcastle, I've encountered the same issue, using the `ddf_pipeline_fixes_may18` branch of the DDF pipeline with the `lofar-stable` branch of `https://github.com/saopicc/killMS`.

Is the `FixQ_PowerSmooth` branch of killMS publicly available? I can't see it on `https://github.com/cyriltasse/killMS_old` or `https://github.com/saopicc/killMS`. Thanks.

I tried simply pointing `pipeline.py` at killMS.py from the `lofar-stable` branch but got an error:
```bash
killMS.py: error: no such option: --SolsDir
```

**Comment by mhardcastle** [comment]
Yeah, using the lofar-stable branch only works with the stable branch of ddf-pipeline.

The only solution to using the current pipeline version -- which is definitely what you should be doing -- is to get access to @cyriltasse's private repositories or, equivalently, to the KSP singularity image where it's all built for you.

**Comment by mhardcastle** [comment]
(There was some theory that the private code might be going to become public but that hasn't happened -- yet.)

**Comment by mooneyse** [comment]
Ah OK, great thanks for that. @cyriltasse, would it be possible to gain access to this repo? (I already have access to your DDF repo.)

Or, @tikk3r, by any chance do you have a copy of your LOFAR DDF Singularity image that has already been built successfully that I could `scp`?
