### ISSUE TITLE
cannot find image_dirin_SSD_m.npy.ClusterCat.npy

### ISSUE THREAD

**Issue by rvweeren** [mhardcastle/ddf-pipeline#197]
I get the crash below about not finding image_dirin_SSD_m.npy.ClusterCat.npy. My suspicion is that this is caused by the fact that I pass a clusterfile in the cfg file?

Should it be hardcoded as such? 
https://github.com/mhardcastle/ddf-pipeline/blob/aab52091b8711d9683d1184b079a013589f442ed/scripts/offsets.py#L437

[image]
imsize=20000
[.....]
clusterfile=Timimage_dirin_SSD_m.npy.ClusterCat.npy

9857 LOFAR sources before filtering
7562 LOFAR sources after filtering
Set up structure
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/offsets.py", line 459, in <module>
    do_offsets(o)
  File "/opt/lofar/ddf-pipeline/scripts/offsets.py", line 437, in do_offsets
    NDir=np.load("image_dirin_SSD_m.npy.ClusterCat.npy").shape[0]
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: 'image_dirin_SSD_m.npy.ClusterCat.npy'
 - 03:30:03 - ClearSHM                  | Clear shared memory
 - 03:30:04 - ClearSHM                  | Clear Semaphores
 - 03:30:04 - ClearSHM                  | Clear shared dictionaries
FAILED to run offsets.py tier1-jul2018.cfg: return value is 1
Traceback (most recent call last):

**Comment by mhardcastle** [comment]
No, it shouldn't be hard-coded. I guess using the clusterfile should just work. Pushing a fix...
