### ISSUE TITLE
SourceCatSub column in solutions

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#204]
I dont think ive seen this issue before.

On a run i am doing I have weird issues with mergesols where the solution files have a ['SourceCatSub'] part but this is a pickle. It can be read fine if the solutions are opened with np.open(filename,allow_pickle=True) but otherwise it fails. We dont use allow_pickle=True usually though so it fails.

Running: MergeSols.py --SolsFilesIn=solslist_5071733298.005561.txt --SolFileOut=DDS0_5071733298.005561_merged.npz
 - 09:40:24 - ClassInterpol             | Running Merge on the following SolsFile:
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB046_uv.pre-cal_12E4C8233t_124MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB086_uv.pre-cal_12E4C8233t_132MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB126_uv.pre-cal_12E4C8233t_140MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB166_uv.pre-cal_12E4C8233t_148MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB206_uv.pre-cal_12E4C8233t_156MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   /net/lofar9/data2/shimwell/ongoing-runs/dataa/SOLSDIR/L732217_SB246_uv.pre-cal_12E4C8233t_163MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:40:24 - ClassInterpol             |   Sorting in frequency
 - 09:40:24 - ClassInterpol             |   Solution channel width is 1.953125 MHz for each solution file
 - 09:40:24 - ClassInterpol             |   Checking solution conformity
 - 09:40:24 - ClassInterpol             |   Merging solutions in frequency
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/MergeSols.py", line 242, in <module>
    main(options=options)
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/MergeSols.py", line 232, in main
    CM.MakeDicoMerged()
  File "/net/para10/data1/shimwell/software/killmsddf/new-install/killMS/MergeSols.py", line 150, in MakeDicoMerged
    DicoOut['SourceCatSub']=Dico0['SourceCatSub']
  File "/home/shimwell/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/shimwell/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by mhardcastle** [comment]
I think this is an incompatibility between old kms and new versions of python. It's fixed in latest master killms.

Don't ask me why I am closing two-year-old issues on github...
