### ISSUE TITLE
bootstrap failed?

### ISSUE THREAD

**Issue by duyhoang2014** [mhardcastle/ddf-pipeline#206]
Hi everyone. I am running ddf-pipeline on a low dec field and having an error at the bootstrap step. You have any idea why that is and how to fix it?

-----------------------------------------
--> Extracting spectral indices for all ch0 sources
Calculating spectral indices for sources  : [======================================================================================================--> Wrote ASCII file 'image_bootstrap_L660934.cube.int.restored.pybdsm.srl'
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead.
--> Wrote file 'image_bootstrap_L660934.cube.int.restored.pybdsm_rms.fits'
Total table length is 1500
Filtered within 2.5 degrees: 764
Bright sources: 127
Remove close neighbours: 121
Table VLSS has 64 entries
Table WENSS has 0 entries
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 252, in <module>
    run_bootstrap(o)
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 154, in run_bootstrap
    make_catalogue('image_bootstrap_'+obsid+'.cube.int.restored.pybdsm.srl',ra,dec,2.5,cats,outnameprefix=obsid)
  File "/opt/lofar/ddf-pipeline/utils/make_fitting_product.py", line 66, in make_catalogue
    raise RuntimeError('No crossmatches exist after group matching')
RuntimeError: No crossmatches exist after group matching
 - 19:45:41 - ClearSHM                  | Clear shared memory
 - 19:45:41 - ClearSHM                  | Clear Semaphores
 - 19:45:41 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py tier1-jul2018.cfg: return value is 1
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1819, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1213, in main
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None,dryrun=o["dryrun"])
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py tier1-jul2018.cfg: return value is 1

**Comment by twshimwell** [comment]
Hey Duy,

There error is because there are not any sources in WENNS. Try replacing WENNS with NVSS in the parset (also updaating the freqs in the parset)

**Comment by twshimwell** [comment]
(see e.g. https://github.com/mhardcastle/ddf-pipeline/blob/master/examples/tier1-jul2018-NVSS.cfg for an example of nvss in the parset)

**Comment by mhardcastle** [comment]
Yeah, the 'example' here is the one that we use for anything below about dec 30 in the LoTSS processing. It uses NVSS and WENSS and does not fail if WENSS is not present, so it is safe to use anywhere in the LOFAR sky.
