### ISSUE TITLE
Test  decor

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#21]
Should go on ddffacet probably but something we need to test in the LOFAR pipeline. Writing here as a reminder.

**Comment by twshimwell** [comment]
Testing runs started (on a slow node unfortunately)

**Comment by twshimwell** [comment]
Looks promising to me.

![image_full_ampphase1m cat fits_first_match_filtered_fluxerrors](https://cloud.githubusercontent.com/assets/12065270/24893912/e0767c3a-1e86-11e7-852f-5095d8f0b8a6.png)
![image_full_ampphase1m cat fits_first_match_filtered_fluxerrors](https://cloud.githubusercontent.com/assets/12065270/24893914/e80eae90-1e86-11e7-95a5-56de93667a0e.png)

Unrelated to decorr but interesting is that this field does seem to have some flux versus TGSS flux issues with good agreement in the peak flux but quite bad agreement in the integrated flux (with the LOFAR flux ~1.6 times higher). Not sure the cause of this discrepancy but I guess a reasonable portion of this is caused by the LOFAR sources being a little blurred with integrated/peak values of 1.2-1.4. I didn't bootstrap here but I guess that would have aligned the total fluxes and the peak fluxes would have become discrepant. Anyway, will get some more statistics on this type of flux agreement once we start running things again.

![image_full_ampphase1m cat fits_tgss_match_filtered_fluxratio_integrated](https://cloud.githubusercontent.com/assets/12065270/24893931/0a5abdd6-1e87-11e7-81ed-3a251a770cfe.png)
![image_full_ampphase1m cat fits_tgss_match_filtered_fluxratio_peak](https://cloud.githubusercontent.com/assets/12065270/24893932/0a7c412c-1e87-11e7-8e88-47672812cc47.png)

Everyone happy with this decorr test or do we want more tests before closing the ticket?

**Comment by mhardcastle** [comment]
Yeah, I don't think we can read too much into the TGSS thing without (a) bootstrap and (b) a comparison of both of them with some other standard like 7C. TGSS can be wrong by tens of per cent. Definitely something to look at after production though.

I'll close this for now.

**Comment by cyriltasse** [comment]
@twshimwell thanks, I had not seen it... Plot not as spectacurlar as the first one you had produced. But I think it's all right?

**Comment by cyriltasse** [comment]
@twshimwell The decorr plot is on a subset of sources classified as point or is it all sources?

**Comment by twshimwell** [comment]
Its isolated point like sources only.

**Comment by twshimwell** [comment]
Yeh I think it looks ok too.
