### ISSUE TITLE
Regression in recent DDF / kMS

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#214]
I've been testing the new python3 version of the pipeline in a pure python3 environment with python3 versions of DDF / kMS: specifically the current saopicc version of DDFacet, v0.5.2, with a fix local fixes for python3 issues, and @cyriltasse 's branch MasterPython3 , again with a few strictly py3 language fixes that I've pushed to the branch. (And a local python2/3 version of DynspecMS for which I've submitted a PR.)

Everything *runs* fine now and I can get through all the pipeline steps. But the results vary from slightly worse to much worse. An example of 'much worse' is a comparison I've just done between old and new runs of P348+23 (new on the left, old on the right, see below). The higher noise is visible by eye. The new run uses the old Clustercat files, so it's not that that's the problem.

![ds9](https://user-images.githubusercontent.com/5337708/77535593-bf2e8900-6e92-11ea-9550-5a406c5eddfc.png)

I have verified that the py2/3 pipeline produces results identical to the old version when running with the old tools (that is, killMS branch FixQ_PowerSmooth and DDF branch ddf_pipeline_fixes_may18). So it's not in the pipeline code itself. Of course the python3 version uses a python3 version of the LOFAR beam (from the astron repo) rather than the LOFAR software tree, and lots of the other underlying software has changed. But I have to say my guess is that something about the python3 conversion of DDF or killMS has broken something subtle but important in the way they work.

I'm happy to try to spend some time and effort debugging this. Probably the first thing I'll do is to redo P348+23 as a test field with the old tools so we can see where the errors start showing up. If we can convince ourselves that this is a killMS problem rather than a DDF problem, say, that would be a start.

Comments welcome from @cyriltasse or anyone else!

**Comment by cyriltasse** [comment]
Well spotted @mhardcastle thanks for the tests... The good news is that we're getting closer to have a fully function py3 version...

I can see two tests right now:
- To rule out LOFARBeam we could work in apparant flux in both versions and see if the difference is still there... But I doubt the problem is coming from this...
- Could we compute the py2/3 AP images after the first DD round - probably see qualitative differences, then if so, swap the solutions, and see if the problem persists?

**Comment by mhardcastle** [comment]
Good plan @cyriltasse -- I have a py2 rerun of this field going now and will be able to compare intermediate images as it goes. I'll post results here.

**Comment by cyriltasse** [comment]
My gut feeling is that the problem comes from somewhere in kMS... if confirmed I'll download the necessary and investigate the potential differences...

**Comment by mhardcastle** [comment]
Looks a lot like kMS is to blame.

Comparison of dirin images (old software on the left, new on the right)
![dirin](https://user-images.githubusercontent.com/5337708/77678250-c59f2c80-6f88-11ea-8bf7-ef8a403b468e.png)

Comparison of phase1 images (likewise):
![phase1](https://user-images.githubusercontent.com/5337708/77678282-d2bc1b80-6f88-11ea-9936-f7e3439105b3.png)

So everything goes wrong at phase1. I can try using the kMS solutions from the new version and imaging with the old DDF to confirm that it's the solutions that are the problem...

**Comment by cyriltasse** [comment]
Interesting... Could we make a comparison with the unsmoothed solutions to rule out SmoothSols?

**Comment by mhardcastle** [comment]
I guess we should be able to plot the smoothed and unsmoothed solutions for both runs... let me see if I can remember how to do that...

**Comment by cyriltasse** [comment]
PlotSolsIm.py should do the trick

**Comment by mhardcastle** [comment]
Yeah, looks like the unsmoothed solutions are crazy. 

Old:
![plotsolsim_old](https://user-images.githubusercontent.com/5337708/77681396-27fa2c00-6f8d-11ea-89ff-887a2480d774.png)

New:
![plotsolsim_new](https://user-images.githubusercontent.com/5337708/77681412-2cbee000-6f8d-11ea-85f8-0d844b4b5c37.png)

**Comment by mhardcastle** [comment]
Also plotsols:
![plotsols](https://user-images.githubusercontent.com/5337708/77681580-74de0280-6f8d-11ea-83cd-4266fb131265.png)
![plotsols_new](https://user-images.githubusercontent.com/5337708/77681587-77d8f300-6f8d-11ea-8376-d5029cb92ce5.png)

**Comment by cyriltasse** [comment]
@mhardcastle can you point me to these two solution files?

**Comment by mhardcastle** [comment]
On the Herts system, in /beegfs/car/mjh/P348+23 and P348+23-new respectively.

Those specific files are SOLSDIR/L734371_SB132_uv.pre-cal_12E5F4B77t_148MHz.pre-cal.ms/killMS.DDS0.sols.npz

________________________________

**Comment by cyriltasse** [comment]
@mhardcastle what are the two kMS branches you're using?

**Comment by cyriltasse** [comment]
oh - got it sorry it was in your first post...

**Comment by cyriltasse** [comment]
Hey @mhardcastle  - I'm being delayed with LOFARBeam that I have trouble with having both py2 and 3 versions working... but I'll do the tests in aparant flux... So remaking the DI image...

**Comment by cyriltasse** [comment]
@mhardcastle the two solutions files you were plotting above were made from the same DicoModel?

**Comment by mhardcastle** [comment]
No, but they are made from DI maps that look pretty much identical. I can cross-check if you like and try py3 killms with the py2 Dicomodel...

**Comment by cyriltasse** [comment]
I'm really puzzled... I can't get good solutions either from the old or new branches... I'm `FixQ_PowerSmooth` for kMS and  `ddf_pipeline_fixes_may18` for DDFacet. Did you rerun the old py2 version or it's a fresh run with everything other updated libraries?

**Comment by mhardcastle** [comment]
OK, so I have been doing a lot of playing with this.

Rerunning killMS on the same dataset over and over again does not work because flagging based on IMAGING_WEIGHT takes place -- then IMAGING_WEIGHT is updated causing more flagging. I have patched killMS to allow the IMAGING_WEIGHT not to be written on request which gives me a test platform. Note that normally in ddf_pipeline DD killMS is run *after* a DI killMS has been done -- so the IMAGING_WEIGHTs are already updated and that's what's shown in the plotsols output above. These tests were done without any IMAGING_WEIGHT column in the test dataset at all and plotsols (same dataset, same dicomodel except converted to apparent) looks like this:
![plotsols_test](https://user-images.githubusercontent.com/5337708/78229968-9b89c500-74c8-11ea-98c0-162a8bfc7648.png)

First of all, kMS does *not* give consistent output between runs with the same code, same dataset and same parameters. This must be something to do with numerical instability because the difference starts small and increases with time. To illustrate this with two sets of complex gains I plot |G_2 - G_1|/(|G_1|+|G_2|) which gives a sense of the magnitude of the difference in gain. Here is an example of two successive runs using my (Herts) installation of the pipeline software for a direction near the centre:
![normal_normal_dir18](https://user-images.githubusercontent.com/5337708/78228455-a0e61000-74c6-11ea-86ca-5f1681aa4242.png)
and a direction at the edge of the field:
![normal_normal_dir0](https://user-images.githubusercontent.com/5337708/78228490-aba0a500-74c6-11ea-919e-7c19e711d877.png)
I have now got this py2 version running in a venv where I can upgrade packages at will and it does not seem significantly worse than this.

The python3 version -- which has the latest versions of everything in a pure py3 singularity image -- is much more divergent from the original than successive runs are:
![normal_py3_dir18](https://user-images.githubusercontent.com/5337708/78228889-28338380-74c7-11ea-8c09-26933abc91bd.png)
![normal_py3_dir0](https://user-images.githubusercontent.com/5337708/78228902-2b2e7400-74c7-11ea-9e8f-6d03d8838396.png)
However it's not obvious that these solutions are intrinsically _bad_, they're just different. By eye on PlotSols they look similar.

The non-deterministic behaviour here is worrying and I think we ought to try to understand it, and to understand where the 'normal' and 'py3' differences come from. It's not clear whether these differences are the cause of the problem.

**Comment by mhardcastle** [comment]
However worth noting that py3 is very much more consistent with *itself* in successive runs. Note scale.

![py3_py3](https://user-images.githubusercontent.com/5337708/78238295-54093600-74d4-11ea-8ba3-d5157b619847.png)

**Comment by mhardcastle** [comment]
I've upgraded numpy, scipy and numexpr in my venv to the latest versions that still work with py2, and the situation is unchanged. Next step would be to downgrade those packages in the py3 singularity to match the py2 packages and see what happens. Suggestions for other packages that might be relevant are welcome.

**Comment by cyriltasse** [comment]
I'm completely lost... Could we chat tomorow @mhardcastle @twshimwell ?

**Comment by mhardcastle** [comment]
I'm around.

**Comment by cyriltasse** [comment]
py3 version, on `DATA_DI_CORRECTED` (top) vs `CORRECTED_DATA` (bottom)

![image](https://user-images.githubusercontent.com/6523227/78377939-944dde80-75d0-11ea-80f4-5c93a4d39dda.png)

![image](https://user-images.githubusercontent.com/6523227/78377983-a2036400-75d0-11ea-9e00-fe54f8e8b39d.png)

**Comment by mhardcastle** [comment]
Hmm, that's weird. Is that with or without the use of IMAGING_WEIGHTS in the py3 code though?

**Comment by cyriltasse** [comment]
It's with `IMAGING_WEIGHTS` _not_ taken into account in `ClassMS` (current `MasterPython3` branch behaviour)

**Comment by mhardcastle** [comment]
Would be interesting to see DATA_DI_CORRECTED but with IMAGING_WEIGHTS taken into account. All I've done to fix this is to move the table close to after the check.

**Comment by cyriltasse** [comment]
I'll try to overwrite my current IMAGING_WEIGHTS with what's in killMS.DIS0.Weights.0.npy and rerun taking them into account

**Comment by mhardcastle** [comment]
You saw I pushed the version with the --UpdateWeights flag?

**Comment by cyriltasse** [comment]
> You saw I pushed the version with the --UpdateWeights flag?

Yeah just saw you pushed stuff, i didn't look at the detail... thanks...

Here is the py3 version, solutions for DATA_DI_CORRECTED (taking into account the restored killMS.DIS0.Weights.0.npy)

![image](https://user-images.githubusercontent.com/6523227/78398520-7d6cb380-75f3-11ea-8398-dd6f111510c1.png)

**Comment by twshimwell** [comment]
Eek. Are there other fields that are still on herts that show similar?

**Comment by mhardcastle** [comment]
@cyriltasse So the imaging weights are not the issue, since those solutions are basically the same. Damn! That seemed like a good idea...

Still testing the effect on the pipeline overall.

@twshimwell Currently nothing we've processed has used the py3 pipeline. I am just finishing up redoing some archive ms for a few fields but they will all be done with py2 until we can sort this out.

**Comment by mhardcastle** [comment]
For completeness, fifference plot of gains for DI solutions in py2 and py3. Not zero but much less generally than for DD.
![py2-py3-di](https://user-images.githubusercontent.com/5337708/78456838-0a6c4700-769e-11ea-84bb-ab4a0edfc4e2.png)

**Comment by mhardcastle** [comment]
Differences between py2 and py3 for this field for first DD calibration, with IMAGING_WEIGHT flagging enabled in py3 version. Much better. We may have cracked it...
![py2-py3-new-dir18](https://user-images.githubusercontent.com/5337708/78460596-00584180-76ba-11ea-91dd-6109972ab4fd.png)

**Comment by mhardcastle** [comment]
... and images post-calibration are now of very similar quality. Going to run through the rest of the pipeline to confirm but I think the big regression is gone and we can close this issue.

I have pushed the version that flags on IMAGING_WEIGHT in ClassMS to the MasterPython3 killMS branch. @cyriltasse if you want to test a version that does something better with the weights then I'm very happy to help.

**Comment by cyriltasse** [comment]
So the final answer is that the difference was coming from the IMAGING_WEIGHT if the previous run not being taken into account in the calibration for the py3 version?

**Comment by mhardcastle** [comment]
Yes, I think that's all it was.
