### ISSUE TITLE
Python 2 vs Python 3 again

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#216]
So we've got past the bug in #214 but there are still Py2/Py3 (or probably killms/DDF) differences that I think are worth worrying about.

I've run a comparison as before between current ddf-pipeline master with 1) python2 environment, DDF-pipeline branch ddf_pipeline_fixes_may18 and killms version FixQ_PowerSmooth and 2) python3 environment, DDF-pipeline from saopicc public release with python3 fixes, killMS MasterPython3.

I've looked at two fields, a 'good' high dec field P198+67 and a less good low-dec field P348+23, with the same clustering in both cases.

Here is a central comparison for P198+67 (py2 on the left, py3 on the right):

![central](https://user-images.githubusercontent.com/5337708/80364405-c70c8f00-887d-11ea-8060-e1b62e6bcb0c.png)

So far so good, maybe py3 is a tiny bit worse round the bright source but nothing to worry about. But go down the beam and weird stuff starts to happen:

![downbeam](https://user-images.githubusercontent.com/5337708/80364561-0d61ee00-887e-11ea-851f-1069caed0376.png)

The big negative holes are centred round real sources -- but only some real sources. What is weirder is that they come and go at different parts of the pipeline:

![allimages](https://user-images.githubusercontent.com/5337708/80365446-831a8980-887f-11ea-9b74-1c85b32b4394.png)

(these are image_dirin_SSD.app.restored.fits, image_dirin_SSD_m_c_di_m.app.restored.fits, image_phase1.app.restored.fits, image_ampphase1.app.restored.fits, image_ampphase1_di.app.restored.fits, image_full_ampphase_di_m.app.restored.fits and
image_full_ampphase_di_m.NS.app.restored.fits).

On the other hand P348+23, which has a number of bad facets away from the centre, is overall a bit better with the Py3 version. 

Data on the Herts cluster in /beegfs/car/mjh:

P198+67-py2 (Python 2)
P198+67 (Python 3)
P348+23 (Python 2)
P348+23-newer (Python 3)

Any thoughts?

**Comment by cyriltasse** [comment]
Super weird....

**Comment by cyriltasse** [comment]
ok - the difference in in the `--Beam-At` parameter

![Screenshot_2020-04-30_13-44-38](https://user-images.githubusercontent.com/6523227/80706589-d5121800-8ae8-11ea-99d2-3124eaacc65e.png)

now we need to say `--Beam-At=tessel` to mimic the py2 behaviour. Or we can change kMS call to have the same behaviour

**Comment by mhardcastle** [comment]
Testing a version that does --Beam-At=facet for both if the option is available to do so in branch `beam_at_issue`.

**Comment by mhardcastle** [comment]
OK, when I do this I get (from kMS)
```
 - 21:55:44 - ClassVisServer     | Estimating Beam directions at the center of the individual facets areas
Traceback (most recent call last):
  File "/home/mjh/pipeline-py3/killMS/killMS/kMS.py", line 1269, in <module>
    main(OP=OP,MSName=MSName)
  File "/home/mjh/pipeline-py3/killMS/killMS/kMS.py", line 679, in main
    Load=VS.LoadNextVisChunk()
  File "/home/mjh/pipeline-py3/killMS/killMS/Data/ClassVisServer.py", line 858, in LoadNextVisChunk
    RA=np.array([self.SM.DicoImager[iFacet]["RaDec"][0] for iFacet in range(len(self.SM.DicoImager))])
AttributeError: 'cSM' object has no attribute 'DicoImager'
```
Master-Python3 branch of kMS. Too late at night to debug this but I'll look again in the morning...

**Comment by cyriltasse** [comment]
weird - can you point me to the full log?

**Comment by mhardcastle** [comment]
Oh, this is the DI cal of course because I'm starting from scratch. Could it be that this option doesn't work with the DI cal?

**Comment by mhardcastle** [comment]
Log at `/beegfs/car/mjh/P198+67-py3-facet/logs/KillMS-L746334_SB021_uv.pre-cal_12E8B7895t_125MHz.pre-cal.ms_DIS0.log`.

**Comment by cyriltasse** [comment]
Oh but weird, this is the DI step, it doesn't need to know about the facet locations...

**Comment by mhardcastle** [comment]
Sure, but the --BeamAt option still seems to be causing it problems even though it shouldn't use it. Well, I'll just use this for the DD kMS and we'll see what happens...

**Comment by mhardcastle** [comment]
Having got through the earlier processing steps with this approach (very slow because of parallelization problems, see issues on DDF and kMS githubs) the first very slow amplitude smooth hangs:

```
================================== Very slow amplitude smooth (full mslist) ==================================

Running: kMS.py --MSName L746334_SB001_uv.pre-cal_12E8B7895t_121MHz.pre-cal.ms --SolverType KAFCA --PolMode Scalar --BaseImageName image_full_ampphase_di_m --dt 43.630000 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 32 --OutSolsName DDS3_full_slow --InCol DATA_DI_CORRECTED --DebugPdb=0 --Weighting Natural --UVMinMax=0.500000,1000.000000 --SolsDir=SOLSDIR --PreApplySols=[DDS3_full_smoothed] --NChanSols 1 --BeamMode LOFAR --LOFARBeamMode=A --DDFCacheDir=. --BeamAt=facet --NodesFile ClusterCat-original.npy --DicoModel image_full_ampphase_di_m_masked.DicoModel
[...]
 - 08:31:40 - ClassVisServer     | Estimating Beam directions at the center of the individual facets areas
 - 08:31:41 - ClassVisServer     | Update LOFAR beam in 90 directions [Dt = 5.0 min] ...
 - 08:32:53 - ClassVisServer     |        .... done Update LOFAR beam
 - 08:32:53 - ClassVisServer     | Loading solution file DDS3_full_smoothed in AP mode
 - 08:33:01 - ClassJonesDomains  | Merging Jones arrays
 - 08:33:01 - ClassJonesDomains  | Compute frequency domains of merged Jones arrays
 - 08:33:01 - ClassJonesDomains  |   There are 1 channels in the merged Jones array
```

**Comment by mhardcastle** [comment]
Running kMS manually here's the actual error:
```
 - 10:11:21 - ClassJonesDomains  |   There are 1 channels in the merged Jones array
Traceback (most recent call last):
  File "/home/mjh/pipeline-py3/killMS/killMS/kMS.py", line 1269, in <module>
    main(OP=OP,MSName=MSName)
  File "/home/mjh/pipeline-py3/killMS/killMS/kMS.py", line 679, in main
    Load=VS.LoadNextVisChunk()
  File "/home/mjh/pipeline-py3/killMS/killMS/Data/ClassVisServer.py", line 1145, in LoadNextVisChunk
    DicoJones=DomainsMachine.MergeJones(DicoJones1,DicoJones)
  File "/home/mjh/pipeline-py3/killMS/killMS/Data/ClassJonesDomains.py", line 207, in MergeJones
    DicoOut["Jones"][itime,:,:,ich,:,:]=ModLinAlg.BatchDot(G0,G1)
  File "/home/mjh/pipeline-py3/killMS/killMS/Array/ModLinAlg.py", line 124, in BatchDot
    C00[:]=a0*a1+c0*b1
ValueError: operands could not be broadcast together with shapes (2790,) (5580,) 
```
So I assume this is something to do with the solutions for tessels rather than facets.

**Comment by cyriltasse** [comment]
Ok - should be something tractable. I'll try to reproduce...

**Comment by cyriltasse** [comment]
Ok I've pushed a change to `Master-Python3`...

**Comment by mhardcastle** [comment]
Cyril's fix gets us going with this again. Onwards and upwards. Should have a final image from this test in a few days.

**Comment by mhardcastle** [comment]
The full-res image for the py3/beam-at image is now available. There are very small differences between sources down the beam, but no longer anything major. That means that, except possibly for runtime which I need to look at again, we can probably declare victory on the py3 version.

**Comment by cyriltasse** [comment]
Fantastic! Time for testing new stuff maybe then?
