### ISSUE TITLE
Break out surveys db and remove admin scripts

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#225]
The ddf-pipeline repo has got too complicated. There is a mixture of stuff that is really essential to the pipeline (and extraction/quality pipelines), scripts that I use to run things which only I really need, and the database stuff that some other projects use.

I think the new structure should be:
1) ddf-pipeline: only the key pipeline elements
2) lotss-query: the database repository
3) lotss-hba-survey: general survey maintenance scripts, e.g. plotting and database wrangling for the web server.

(1) depends on 2). (3) depends on (1) and (2).

Does this seem OK to everyone? I'll post a list of scripts to be removed from ddf-pipeline...

**Comment by mhardcastle** [comment]
Scripts to be removed from ddf-pipeline scripts directory:
* check_lgz.py
* check_location.py
* compress_archived.py
* concat_mosaic_cats.py
* find_dr2_area.py
* find_pos.py
* insert_field.py
* make_custom_config.py
* make_dr2_release.py
* make_i_subim.py
* make_mosaic_header.py
* make_pol_subim.py
* make_subim.py
* make_vlow_stokesI.py
* monitor.py 
* monitor_vlow_repro.py
* plot_db_*.py
* queue_quality.py
* remove_archived.py
* run_job.py
* run_pipeline.py
* run_pipeline_leiden.py

I think these are all either obsolete, or of interest to only me or possibly @twshimwell . They'll all move to lotss-hba-survey where we can continue to run them.

**Comment by twshimwell** [comment]
Good idea to tidy things up. All sounds good to me.
