### ISSUE TITLE
strange behaviour in facet offset determination

### ISSUE THREAD

**Issue by wllwen007** [mhardcastle/ddf-pipeline#226]
I ran into a strange issue in the facet offset determination on my LBA field, probably because with only 5 directions, the imaging facets are much smaller than the calibration directions.

Checking the offset plot, the mean positions seem to be in strange places (outside of their facets even!)
![SKO-pslocal-bad](https://user-images.githubusercontent.com/2170761/86952144-d5670900-c152-11ea-81d8-a5a9d2bb1a3d.png)
with an added scatter of the lofar positions colour-coded by the Facet number so you can see the sources have been put in the wrong facet.

I think I traced it to RegPoly.label_poly  changing plabel not plab
https://github.com/mhardcastle/ddf-pipeline/blob/839df54dc3af3493e9305a0847446d3d56f52064/utils/facet_offsets.py#L116

Looks better after this fix
![SKO-pslocal](https://user-images.githubusercontent.com/2170761/86952151-d9932680-c152-11ea-8481-a6f0dcf8d0cd.png)

Have you seen anything like this before?

**Comment by mhardcastle** [comment]
No, this looks like a very obvious bug which must have been there for ever )-: . I guess the effect on the HBA data is not huge because the offsets tend to be correlated between facets, but it's annoying. Please submit a PR for a fix.
