### ISSUE TITLE
Sources vanishing close to the facet edges

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/ddf-pipeline#230]
I have found some weird behaviour for some sources when looking at the individual datasets corresponding to the deep image of ELAIS-N1. Some sources look like flaring or vanishing in a crazy way in the individual images. Two examples:
![ID_13213_png](https://user-images.githubusercontent.com/215599/89187279-fa556d00-d594-11ea-9b63-e119303415ad.gif)
![ID_16094_png](https://user-images.githubusercontent.com/215599/89187309-04776b80-d595-11ea-90b6-603c8fbbc922.gif)

These sources are close to the facet edges at a distance of about 2.6 degrees to the centre or more. However, their detections are strong (above 10 sigma in general). The corresponding facet is noisy and present strong shifts in the position of the sources close to the edge. If the individual datasets are not shifted we could expect that behaviour (at least partially because some sources are not so close to the edge and are really blinking crazily). I could not check if applying shifts computed for the individual dataset the problem disappears but it could be a good test to run. 

In any case, my worry is about the final flux density in the deep image. I think that the shifts are computed for the final combined image but the shifts would be mainly "dataset-specific" and not taking this into account would produce a strong smearing (as observed) or an underestimation in the flux level if the source is completely out of the facet boundary for several observations. I think that this point should be explored in the future as it seems important for deep images.

**Comment by twshimwell** [comment]
Interesting issue Pepe would certainly be good to get to the bottom of. So just to check. All your fields are calibrated off exactly the same model? For the deconvolution of these images I guess you are using the final solutions (so the two sets of solutions) and you are also initiating it with a DicoModel from your deep image (i.e. the same command as in the final DDF-pipeline imaging command)? If there are discontinuities at the facet boundaries it can also be that the facet has somewhat diverged, do you think that could be a possibility in some of the epochs? 

Do you have the images somewhere accessible?

**Comment by nudomarinero** [comment]
Answers:
- All the fields are calibrated using the same model.
- For the deconvolution of the images we used the final solutions.
- We initiate with the DicoModel (and mask) of the deep image.
- I do not know about the divergence. It is a possibility because the facet is relatively bad. How could I check that?

For reference, the command for an individual dataset is:
```
#!/bin/bash

i=$1

DDF.py --Output-Name=image_full_ampphase_di_m-${i}.NS --Data-MS=/home/jsm/repos/cuillin_processing/ddf_config/big-mslist-${i}.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA_DI_CORRECTED --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=1 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.500000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=/data/jsm/ddf-deep-cycle2and4 --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --GAClean-AllowNegativeInitHMP True --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Predict-ColName DD_PREDICT --Output-RestoringBeam 6.000000 --Weight-ColName="IMAGING_WEIGHT" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=5.00 --Mask-External=image_full_ampphase_di_m.app.restored.fits.mask.fits --DDESolutions-GlobalNorm=None --DDESolutions-DDModeGrid=AP --DDESolutions-DDModeDeGrid=AP --DDESolutions-DDSols=[DDS3_full_smoothed,DDS3_full_slow_merged] --Predict-InitDicoModel=image_full_ampphase_di_m_masked.DicoModel --Selection-UVRangeKm=[0.100000,1000.000000] --GAClean-MinSizeInit=10 --Beam-Smooth=1 --Misc-ConserveMemory=1 | tee logs/image-${i}-manual.txt

DDF.py image_full_ampphase_di_m-${i}.NS.parset --Output-Name=image_full_ampphase_di_m-${i}.NS_shift --Output-Mode=RestoreAndShift --Output-ShiftFacetsFile=facet-offset.txt --Predict-InitDicoModel image_full_ampphase_di_m-${i}.NS.DicoModel --Cache-SmoothBeam=force --Log-Memory 1 --Cache-Dir=/data/jsm/ddf-deep-cycle2and4 --Misc-ConserveMemory=1 | tee logs/image_shift-${i}-manual.txt
```
One of the evident problems is that the shift step applies the shifts computed for the final image.

The images are in cuillin in Edinburgh but I could upload them somewhere else (perhaps Herts?)

**Comment by twshimwell** [comment]
Yeh identifying failed facets is a little subjective as the severity of failure varies a lot - we actually went with an approach to identify and remove them during the mosaicing step based on the astrometry. You could see whether these would be identified as "failed" by running for each image: offsets.py pipeline-parsetfile.cfg (where you can create a dummy pipeline parset file and then a bit of fiddling with the naming, so either changing the script to get your specific image names or e.g moving each image to a new folder and renaming to the normal name withinout the -${i}). If the astrometric errors (output when running offsets in astromap.fits) for a particular facet are greater than 0.5" then in the DR2 mosaicing we would say this facet is failed. This is of course a little arbitrary but does seem to be a good proxy for bad calibration/failed facets so might give an indication of whether or not the calibration is an issue in these regions for these epochs.

If your data are all calibrated against the same model id have thought this kind of means that some kind of average astrometry for each facet should be the same in each field. If there are ionospheric effects on scales much smaller than a facet though then I guess the sources can still move around a fair bit within a facet though and as just 1 offset is applied per facet then it isnt corrected at all but nor is the ionosphere really. This will be more severe on the outside of the field where the facets are generally larger. Not sure how it could really be fixed though without either using some screen or more facets.

**Comment by twshimwell** [comment]
(oh ps Wendy found an issue with the offsets code, https://github.com/mhardcastle/ddf-pipeline/issues/226, this is now fixed but worth pulling the latest ddf-pipeline before running the code)

**Comment by twshimwell** [comment]
Another thing that might be making it look odd is using the dicomodel. I wonder if its worth taking a few of the bad epochs and doing the imaging without using the dicomodel. I was thinking that maybe that can hide some effects by putting sources into the map even if they are not really there anymore -- so e.g. if the dicmodel puts in lots of faint sources and you just clean a bit then you will only refine the model for the brighter sources perhaps and this could make things look odd (maybe if the facet is severely failed and really looks quite messy then it could severely change sources in the map by recleaning them but leave other sources largely intact because they are not recleaned)

**Comment by mhardcastle** [comment]
Think it's fair to close this issue as the deep field processing has moved on quite a bit, as has the pipeline!
