### ISSUE TITLE
CleanSHM.py

### ISSUE THREAD

**Issue by ValentVacca** [mhardcastle/ddf-pipeline#231]
I am trying to run the public ddf-pipeline (version v2.2-158-g6176bd5) within a singularity but, right after I run it, I encounter the following problem

--------------------------------------
/usr/lib64/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:2 on None
  warn(ConfigurationMissingWarning(msg))
Welcome to ddf-pipeline, version v2.2-158-g6176bd5
Successful readonly open of default-locked table L645453_SB000_uv_12BB842DAt_122MHz.pre-cal.ms: 27 columns, 137250 rows
Running: CleanSHM.py
FAILED to run CleanSHM.py: return value is -4
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1819, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 949, in main
    run('CleanSHM.py',dryrun=o['dryrun'])    
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run CleanSHM.py: return value is -4

--------------------------------------

I think that there is a problem with CleanSHM.py. Indeed, when I run this script within the singularity I get the following message

--------------------------------------

/mnt/mupstorage2/vvacca/GOODS_NORTH/PULSAR/L645453/ddf_pulsar.sh: line 12: 15404 Illegal instruction     (core dumped) CleanSHM.py

--------------------------------------

Do you have any suggestions about how to solve the problem?

**Comment by mhardcastle** [comment]
This looks fairly fundamentally broken. CleanSHM.py is a few lines of Python (part of DDFacet rather than ddf-pipeline but that doesn't matter). My guess is that someone has built the DDFacet gridder with compiler options that aren't compatible with the machine it's being running on. What singularity are you using and where did you get it from?

**Comment by ValentVacca** [comment]
Thanks. I am using a singularity shared by a colleague of mine, it has not built indeed on the machine where I am working. Shall I build again the singularity to solve the problem?

**Comment by mhardcastle** [comment]
If you have that option, please do.

(Also if while you're building you have the chance to upgrade to the latest ddf-pipeline that would be good -- if future support is needed it helps to be running the master version.)

**Comment by ValentVacca** [comment]
It is actually a bit problematic for me to build again the new singularity since I do not have root permissions of the machine I am using. Anyway, I tried to run it on another node of the cluster and it runs but it stops when it should perform the optical cross-id. I tried different options: (1) method=panstarrs, but it fails to establish a connection, (2) method=pslocal  but I get a connection error, I guess because the pslocal requires connection to hertz and maybe the cluster where I work does not allow for it, (3) I tried with method=''/method=/method=None but in all these cases I get "Exception: Failed to download catalogue with method", (4) I deleted the section [offset] but it looks for facet_offset_file and says that it is referenced before assignment. Is there a way to fix this problem? Thanks

**Comment by mhardcastle** [comment]
Yes, if you can't make an internet connection then only method=None will work. This should be fixed in recent versions of the pipeline. Can you update to the latest version? Possibly you'll have the same problem with rebuilding the singularity, I know... Alternatively, it *may* work to have an empty [offset] section.

**Comment by ValentVacca** [comment]
Unfortunately none of these two options works, so probably I need to update the pipeline. Which version of the pipeline is better to use? is it just the master branch? and which version of DDF does it use (ie which branch from DDF github goes with that version of the pipeline)? Thanks again

**Comment by mhardcastle** [comment]
Do you actually need any of the pipeline products after that? (QU cubes, V images, and dynamic spectra...)

Otherwise yes just pull the latest master and I believe you should be fine with whatever version of DDF you already have.

**Comment by ValentVacca** [comment]
Yes, I need all these products. In this case do I need a specific version of the pipeline and of DDF?

**Comment by mhardcastle** [comment]
No -- you still just need the master version. Just checking in case it was actually OK for you to stop at the point where the v2.2 pipeline is crashing.

**Comment by ValentVacca** [comment]
I have now a new singularity. The pipeline has been updated to the master version, while DDF is the same as before (0.3.4.1). Now it stops at the very beginning, when starting DDF. At first I thought the problem was due to the fact that -Cache-DirWisdomFFTW was not properly set. However, even fixing this, the problem persists. I attach the log for further info. Thanks
[image_dirin_SSD_init.log](https://github.com/mhardcastle/ddf-pipeline/files/5365062/image_dirin_SSD_init.log)

**Comment by twshimwell** [comment]
Hey, hmmm I cant see anything obvious but it is quite an old version of DDFacet. It might be that some options and things have changed too - have you run ddf-pipeline with it at all before?

A bit of a random guess but I wonder if its having issues at the RA=360 to RA=0 transition. Perhaps try making the imsize smaller in the ddf-pipeline parset (maybe like just 5000 for testing).

**Comment by ValentVacca** [comment]
I have run the ddf-pipeline version v2.2-158-g6176bd5 with this DDFacet and it worked until the optical cross-match, this is the reason why I upgraded the ddf-pipeline... Thanks

**Comment by ValentVacca** [comment]
What version of DDFacet do you suggest to use with the master ddf-pipeline? Thanks

**Comment by mhardcastle** [comment]
I don't understand this problem, up to date versions of the pipeline work out what version of DDFacet they are running and adapt accordingly. Moreover this doesn't look like an incompatibility with flags, otherwise DDFacet wouldn't have run at all, rather than crashing half way through. There's no further logfile information about what caused the crash?

Any version of DDFacet should work, but ddf_pipeline_fixes_may18 is the one we have been using for production for LoTSS.

**Comment by ValentVacca** [comment]
OK, thanks. In attachment you can find the other log, but it is not more informative at least to me
[DDF-image_dirin_SSD_init.log](https://github.com/mhardcastle/ddf-pipeline/files/5383498/DDF-image_dirin_SSD_init.log)

**Comment by mhardcastle** [comment]
This is an old issue and I'm guessing would be fixed by running new DDFacet (perhaps using a new ddf-pipeline singularity. I'm going to close it, reopen if needed.
