### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'readonly'

### ISSUE THREAD

**Issue by lmorabit** [mhardcastle/ddf-pipeline#233]
I'm not sure if this is a ddf-pipeline problem, a DDFacet problem, or just an incompatibility between the two. The information below on the versions was taken from the logs. 

Software versions:
Welcome to ddf-pipeline, version v2.2-217-gfe5393d
DDFacet version is 0.3.4.1

experiencing the following error:

Traceback (most recent call last):
  File "/opt/lofar/DDFacet/bin/DDF.py", line 387, in <module>
    main(OP, messages)
  File "/opt/lofar/DDFacet/bin/DDF.py", line 235, in main
    Imager.main()
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1097, in main
    repMinor, continue_deconv, update_model = self.DeconvMachine.Deconvolve()
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 390, in Deconvolve
    self.InitIslands()
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 311, in InitIslands
    ModelImage=ModelImage, DicoDirty=self.DicoDirty)
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassInitSSDModelHMP.py", line 131, in giveDicoInitIndiv
    ParmDict.readonly(), self.InitMachine.DeconvMachine.facetcache.readonly(),1))
AttributeError: 'NoneType' object has no attribute 'readonly'
Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <bound method AsyncProcessPool.__del__ of <DDFacet.Other.AsyncProcessPool.AsyncProcessPool object at 0x7f4d24f1d990>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f4c9906d170>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f4d16f43758>> ignored
^[[91mFAILED to run DDF.py --Output-Name=image_dirin_SSD --Data-MS=mslist.txt --Deconv-PeakFactor 0.010000 --Data-ColName DATA --Parallel-NCPU=1 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=1 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=15.00 --Mask-External=external_mask.fits --Selection-UVRangeKm=[0.100000,1000.000000] --Cache-Dirty forcedirty --Cache-PSF force --GAClean-MinSizeInit=10: return value is 1^[[0m
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1857, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1038, in main
    uvrange=uvrange,catcher=catcher)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 287, in ddf_image
    run(runcommand,dryrun=options['dryrun'],log=logfilename('DDF-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run DDF.py --Output-Name=image_dirin_SSD --Data-MS=mslist.txt --Deconv-PeakFactor 0.010000 --Data-ColName DATA --Parallel-NCPU=1 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=1 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.150000 --Image-NPix=20000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 1.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 12.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=15.00 --Mask-External=external_mask.fits --Selection-UVRangeKm=[0.100000,1000.000000] --Cache-Dirty forcedirty --Cache-PSF force --GAClean-MinSizeInit=10: return value is 1

**Comment by mhardcastle** [comment]
I'm guessing here but I think the cache from the previous step has been corrupted or doesn't exist. I presume you didn't do anything odd here and you don't have cache files lying around. If you repeat with `--control-redofrom=start` does the problem recur?

**Comment by lmorabit** [comment]
I'll try that and let you know.

**Comment by twshimwell** [comment]
Did you also check the size of /dev/shm, that that folder empty before running the pipeline, and also the memory and swap of the node?

**Comment by lmorabit** [comment]
@mhardcastle that didn't work, although I'm not surprised as I start fresh every time. I'm working on a cluster where it's faster to copy the data to the local scratch for the node, which is SSD, and process there. I should have thought about this before but have been focused on other things.

@twshimwell I am requesting exclusive use of a node that has 1 TB of RAM, so I wouldn't expect memory / swap to be an issue.  If I run CleanSHM.py before starting the pipeline, do you think that would do it?  How much space do I need in /dev/shm >

**Comment by twshimwell** [comment]
Thats a fancy computer so would be suprised if its memory then - /dev/shm should be say 250GB and should be empty prior to starting (CleanSHM.py normally does this but sometimes things can get locked in there and you might need to search with ps -ef or something for old DDFacet jobs and pkill them and run CleanSHM.py again to empty it).

Do your image_dirin_SSD_init things look sensible (like the dirty image)?

**Comment by lmorabit** [comment]
I won't know until it completes successfully, but @twshimwell suggested adding 
```
[machine]
NCPU_DDF = 16
NCPU_killms = 16
```
to the config file (as in the log somewhere it was reporting NCPU=1) and this seems to have worked for now ...

**Comment by mhardcastle** [comment]
If you have some time to figure out why the NCPU auto-detect isn't working that would be interesting!

(With pipeline set up, do in an ipython:

``
In [1]: from getcpus import getcpus

In [2]: getcpus()
Out[2]: 16
```

**Comment by tikk3r** [comment]
> If you have some time to figure out why the NCPU auto-detect isn't working that would be interesting!

Just gave it a try in an interactive session with a ddf image I typically use and `getcpus` indeed returns 1. Your suggestion from the DDFacet issue regarding Slurm (to use `psutil.Process().cpu_affinity()` to properly handle the job's CPU allocation) does still return the proper number of CPUs, so in case of Slurm maybe a `len(psutil.Process().cpu_affinity())` instead would work.

```python
In [1]: import getcpus

In [2]: getcpus.getcpus()
Out[2]: 1

In [3]: import psutil

In [4]: psutil.cpu_count(logical=False)
Out[4]: 1

In [5]: psutil.cpu_count(logical=True)
Out[5]: 60

In [6]: len(psutil.Process().cpu_affinity())
Out[6]: 5
```

Could it be related to the Slurm setup? If I run `sinfo --Node --long` I see
```
NODELIST   NODES PARTITION       STATE CPUS    S:C:T MEMORY TMP_DISK WEIGHT AVAIL_FE REASON
wn-db-01       1  infinite        idle   38   38:1:1 352000        0      1 skylake, none                             
wn-fa-01       1  infinite        idle   22   22:1:1 175000        0      1 broadwel none                
wn-ha-01       1   normal*        idle   60   60:1:1 950000        0      1 napels,s none 
```
In the S:C:T column it seems to have the number of sockets and number of cores swapped for all machines. Maybe that causes a wrong count of physical cores?

**Comment by mhardcastle** [comment]
Interesting, thanks. A setup where psutil thinks it has one physical cpu and 60 virtual ones is indeed weird. The best thing to do here might be to query something that Slurm sets directly, as the code already does for Torque. The problem with the cpu_affinity idea is that it will allow the code to run on virtual CPUs on machines where hyperthreading isn't switched off.

**Comment by tikk3r** [comment]
I see, I didn't know that.  I am not aware of a file like the one you query for Torque. There is e.g. `SLURM_JOB_CPUS_PER_NODE`, which in the above case indeed returns 5.

> **SLURM_JOB_CPUS_PER_NODE**
Count of processors available to the job on this node. 

but if I understand correctly this still suffers from the hyperthreading problem as Slurm sees them as the same thing.
> **Slurm documentation refers to CPUs, cores and threads. What exactly is considered a CPU?**
If your nodes are configured with hyperthreading, then a CPU is equivalent to a hyperthread. Otherwise a CPU is equivalent to a core.
I don't see any variables pertaining to only physical cores.

**Comment by mhardcastle** [comment]
Well, I think if slurm is managing the use of cores then it's OK to believe slurm -- I would suspect most slurm setups would only allocate physical cores in the first place.

So we should probably query that environment variable and believe it if it's set. Does that sound OK? I've pushed code that purports to do this to the latest master if someone wants to test it.

**Comment by mhardcastle** [comment]
Since a fix was pushed and I have now verified that it works correctly on a Slurm cluster, closing this issue.
