### ISSUE TITLE
a few changes for galactic imaging

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#234]
For galactic imaging a few changes minr be useful. These are the option to do P only instead of AP calibration and also to optionally use the new SplitIsland capabilities in DDFacet. Also reading in a fits mask to merge with the mask would be good to (currently we can read in a region file)

**Comment by twshimwell** [comment]
Any objection to adding these features in as options? If not then ill push something (once tested) to master.

**Comment by mhardcastle** [comment]
No objection at all. Best would be to make a branch for them and do a pull request when done so I can just see the changes go past.

**Comment by twshimwell** [comment]
OK these options are all in the galactic branch now but I need to test still.

**Comment by twshimwell** [comment]
Hi @mhardcastle is it possible to merge this branch into master so that we can use it? It should work as normal when given the normal options. I was thinking though we can change the default options for low galactic lattitude (similar to what we are doing at low dec). An example parset would be:

[machine]
NCPU_DDF=32

[data]
mslist=mslist.txt
full_mslist=big-mslist.txt
colname=CORRECTED_DATA

[image]
imsize=20000
robust=-0.15
psf_arcsec=12.0
final_robust=-0.5
final_psf_arcsec=6.0
do_decorr=True
final_rmsfactor=1.0
low_imsize = 6000
low_psf_arcsec = 20
low_robust = -0.25
use_splitisland=True

[control]
restart=True
bootstrP=False
polcubes=False
stokesv=False
spectral_restored=False
clearcache=False
skip_di=True

[masking]
tgss=$$/TGSSADR1_7sigma_catalog.fits
extended_size=2000
thresholds=[50,50,50,50]
rmsfacet = False

[bootstrap]
catalogues=['$$/VLSS.fits','$$/wenss.fits']
names=['VLSS','WENSS']
radii=[40,10]
frequencies=[74e6,327e6]

[solutions]
ndir=45
uvmin=.1
normalize=['None','None','None']
NIterKF=[6, 6, 6, 6, 6, 6, 6]
dt_slow=1.
dt_fast=0.5
dt_di=0.2
apply_sols=['P', 'P', 'P', 'P', 'P', 'P', 'P']

[spectra]
do_dynspec=True

[offsets]
method=pslocal

[compression]
compress_polcubes=True
delete_compressed=True
compress_ms=True

**Comment by mhardcastle** [comment]
Hi Tim,

Yes, I've made a pull request (you can do this too you know (-: ) and will merge in a minute.

Re changing default options, yes we can do this. The code that gets run to make a config file when I do automatic processing is over in lotss-hba-survey/make_custom_config.py . So we can just amend that.

I guess at the moment the version of DDF I run doesn't have the splitisland option, so I'd need to upgrade that here before I could crunch through Galactic fields.

Cheers

Martin
