### ISSUE TITLE
add V mosaicing

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#235]
Functionality to do stokes V mosaicing added to mosaic.py and mosaic_pointing.py

**Comment by twshimwell** [comment]
Pushed to master in commit 56b58b8

Note that V maps dont have BMAJ etc so added exception.

            try:
                header[ch]=hdus[0].header[ch]
            # Exception for Stokes V images where dong have a BMAJ
            except KeyError:
                header[ch]=20.0/3600.0

**Comment by mhardcastle** [comment]
Shouldn't we leave BMAJ empty if the parent maps don't have one?

**Comment by twshimwell** [comment]
Oh so remove from header you think or set to e.g. nan?

**Comment by mhardcastle** [comment]
No BMAJ/BMIN/BPA at all is the right thing for maps that haven't been deconvolved. We don't deconvolve the V maps right?

**Comment by cyriltasse** [comment]
Yes we don't...

**Comment by mhardcastle** [comment]
OK so change the code just to skip the missing keywords with except: pass , I suggest.

Mosaicing undeconvolved maps is --- well, I guess you may get something out of it...

**Comment by twshimwell** [comment]
ok ive put an exception in there to pass this part.

I also had to make it so that it can deal with the V cube structure by just copying V from f[0].data[0][1] to f[0].data[0][0] if the V option is given (sorry a bit hacky -- perhaps adding an option to flatten might have been cleaner).

Yeh not sure whether these mosaics will be useful but was going to use them to make a stokes V HIPS.

**Comment by twshimwell** [comment]
This seems to all work except that when the V images app/int is done to get the PB then the PB derived isnt right with discrete pixels showing up in the generally smooth PB.
