### ISSUE TITLE
Change reference frequency in MSLIST

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#236]
When splitting data with DPPP the REF_FREQUENCY no longer corresponds to the central frequency causing some confusion when MSLIST is sorted in frequency. Rather than changing the frequency of the files Ithought maybe  auxcodes MSLIST could change:

self.freqs.append(t[0]['REF_FREQUENCY'])

to
self.freqs.append((np.min(t[0]['CHAN_FREQ']) + np.max(t[0]['CHAN_FREQ']))/2.0)

to fix this.

**Comment by rvweeren** [comment]
Yes, related to:
https://github.com/lofar-astron/DP3/issues/217

To fix it I do:

```
    ms = "my.ms"
    t = pt.table(ms + '/SPECTRAL_WINDOW',ack=False, readonly=False)
    freq = np.mean(t.getcol('CHAN_FREQ')[0])
    t.putcol('REF_FREQUENCY', freq)
    t.close()

```

**Comment by twshimwell** [comment]
Ah right and there are no unforeseen implications of changing the frequency in the header (I was a little scared to do that).

**Comment by rvweeren** [comment]
No, in fact if REF_FREQUENCY  the ddf-pipeline crashes. What would be good though is to only change REF_FREQUENCY **if** you detect it is wrong by say 0.1 MHz or more. So that in most situations REF_FREQUENCY is not changed.

**Comment by twshimwell** [comment]
Commit 56cba41 fixes this. Should not have any impact for data from regular prefactor processing but should tweak frequencies for data that has been split in frequency as described above.
