### ISSUE TITLE
Resetting column name before Predict_DDS2

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#243]
Hmmm are we supposed to be doing this:

    if not o['skip_di']:
        # Compute the DD predict
        colname=o['colname']
        separator("Compute DD Predict (full mslist)")
        ddf_image('Predict_DDS2',o['full_mslist'],cleanmode='SSD',
                applysols=o['apply_sols'][4],majorcycles=1,robust=o['image_robust'],colname=colname,peakfactor=0.01,
                automask=True,automask_threshold=o['thresholds'][1],normalization=o['normalize'][0],
                apply_weights=o['apply_weights'][0],use_weightspectrum=o['use_weightspectrum'],uvrange=uvrange,use_dicomodel=True,
                dicomodel_base=CurrentBaseDicoModelName,
                catcher=catcher,
                ddsols=CurrentDDkMSSolName, PredictSettings=("Predict","DD_PREDICT"))

I'd have thought we dont want to reset the column name here because we have the SCALED_DATA column and the DDS2_full sols are derived using SCALED_DATA. So isnt it odd that the Predict_DDS2 uses o['colname'] (i.e. DATA or CORRECTED_DATA) together with DDS2_full_smoothed.

**Comment by mhardcastle** [comment]
#314 reminded me of this which has been outstanding for ages. Should we not be using the same logic as in #314 here?

**Comment by twshimwell** [comment]
Yeh I thought we should be using scaled_data here if we bootstrap... do you agree?

**Comment by mhardcastle** [comment]
I think so. This is @cyriltasse 's change from way back when we were making the new version of the pipeline, but I can't see a reason why we would revert to the use of the unscaled data.

**Comment by mhardcastle** [comment]
Should be fixed now
