### ISSUE TITLE
killMS problem inverting matrix running the pipeline with python3

### ISSUE THREAD

**Issue by BiavaNadia** [mhardcastle/ddf-pipeline#245]
Running the pipeline with python3 in Bologna and Trieste on different datasets we found a problem in inverting matrix with killMS at step **DDS3_full**. This happens for two / three subbands (around 120 MHz and at 168 MHz) and the pipeline stops when it encounters this problem. We got around the problem by removing the problematic datasets but noting that they do not create problems in the previous steps. Also one of the two observations had already been calibrated one years ago using python2 without encountering this problem.
Could it be a problem with using python3?

**Comment by mhardcastle** [comment]
It could be a problem with different versions of e.g. numpy between the py2 and py3 versions -- so indirectly related to a python3 run. We have been using a py3 environment in a singularity in production for some time without seeing this problem.

I would suggest raising a killms issue over on https://github.com/cyriltasse/killMS/issues with the specific error message, @cyriltasse may have some ideas!

**Comment by mhardcastle** [comment]
Established that this was a killms problem (with up to date numpy etc). Shortly the public version of killms should have a fix that cures it. Closing.
