### ISSUE TITLE
Issue running the DDF pipeline with python3 in Bologna & Trieste

### ISSUE THREAD

**Issue by ebonnassieux** [mhardcastle/ddf-pipeline#246]
Colleagues in Italy have recently run into issues using the DDF pipeline locally:

Running the pipeline with python3 in Bologna and Trieste on different datasets we found a problem in inverting matrix with killMS at step DDS3_full. This happens for two / three subbands (around 120 MHz and at 168 MHz) and the pipeline stops when it encounters this problem. We got around the problem by removing the problematic datasets but noting that they do not create problems in the previous steps. Also one of the two observations had already been calibrated one years ago using python2 without encountering this problem.
Could it be a problem with using python3?

Have LOFAR users elsewhere encountered this issue?

**Comment by mhardcastle** [comment]
See #245 (-:
