### ISSUE TITLE
mask_dicomodel missing in ampphase

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#25]
after recent changes in the master branch is seems the mask_dicomodel step is missing after the ampphase image.

**Comment by mhardcastle** [comment]
It now happens after the low-res image is made so we mask using the model including the low-res mask.

**Comment by twshimwell** [comment]
Ah ok, I thought there was likely a reason. Now though the image_ampphase1_masked.DicoModel is searched for but not found at the killms step after the image_ampphase ddfacet.

**Comment by mhardcastle** [comment]
Good point! OK, I have pushed a fix.
