### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#258]
I don't know if its not to early to report errors from the new Singularity image, but I got:
[logBash.zip](https://github.com/mhardcastle/ddf-pipeline/files/7575894/logBash.zip)
[logs.zip](https://github.com/mhardcastle/ddf-pipeline/files/7575943/logs.zip) - logs/ folder

>  - 20:09:07 - ClassInterpol      |   Merging solutions in frequency
> Traceback (most recent call last):
>   File "/usr/local/src/killMS/killMS/MergeSols.py", line 246, in <module>
>     main(options=options)
>   File "/usr/local/src/killMS/killMS/MergeSols.py", line 236, in main
>     CM.MakeDicoMerged()
>   File "/usr/local/src/killMS/killMS/MergeSols.py", line 154, in MakeDicoMerged
>     DicoOut['SourceCatSub']=Dico0['SourceCatSub']
>   File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 253, in __getitem__
>     return format.read_array(bytes,
>   File "/usr/lib/python3/dist-packages/numpy/lib/format.py", line 727, in read_array
>     raise ValueError("Object arrays cannot be loaded when "
> ValueError: Object arrays cannot be loaded when allow_pickle=False

[...]

>  - 20:09:06 - ClipCal            | Writing IMAGING_WEIGHT in L232875_SB220_uv.dppp.pre-cal_124B2FCD4t_164MHz.pre-cal.ms
> [92mRunning: MergeSols.py --SolsFilesIn=solslist_4910677203.03.txt --SolFileOut=DDS0_4910677203.03_merged.npz [0m
> [91mFAILED to run MergeSols.py --SolsFilesIn=solslist_4910677203.03.txt --SolFileOut=DDS0_4910677203.03_merged.npz : return value is 1[0m
> Traceback (most recent call last):
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1922, in <module>
>     main(o)
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1269, in main
>     CurrentDDkMSSolName=killms_data(CurrentBaseDicoModelName,o['mslist'],'DDS0',colname=colname,
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 541, in killms_data
>     outsols=smooth_solutions(mslist,outsols,catcher=None,dryrun=o['dryrun'],InterpToMSListFreqs=InterpToMSListFreqs,
>   File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 655, in smooth_solutions
>     run(ss,dryrun=dryrun)
>   File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 68, in run
>     die('FAILED to run '+s+': return value is '+str(retval),database=database)
>   File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 51, in die
>     raise Exception(s)
> Exception: FAILED to run MergeSols.py --SolsFilesIn=solslist_4910677203.03.txt --SolFileOut=DDS0_4910677203.03_merged.npz : return value is 1

when trying to precess L232875.

**Comment by mhardcastle** [comment]
Yes, it is too early...  As you can see this is a killMS python3 bug; there's a public killMS version that fixes this and a number of other killms problems that hasn't happened yet (might be today). Once that releases there will be a proper point release of ddf-pipeline to include the singularity and then you are welcome to report errors.
