### ISSUE TITLE
SDR indexing

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#259]
Indexing returned by "status" query is different to that used when stage. Instead appears that index returned by a "files" query returns the dict with appropriate index for the stage (but "files" doesnt tell you the online/offline status unfortunately)

**Comment by mhardcastle** [comment]
Hey Tim, the code as it is seems to work for me, maybe that's a coincidence though? Are you seeing it staging the wrong files?

**Comment by twshimwell** [comment]
Ohh hmmm i wonder if sometimes it can return things in different orders.  Yeh I see it staging the large pol cubes instead of images.tar. If I instead tell it to stage misc.tar then it stages images.tar for me.

**Comment by mhardcastle** [comment]
Weird, it's worked every single time I've tried it, but I'll see if I can get it to use the files index instead...

**Comment by mhardcastle** [comment]
OK, please give the new version in master a go when you get a chance!

**Comment by twshimwell** [comment]
Many thanks! seems to be working for me now. Hopefully still works on your side too.

**Comment by twshimwell** [comment]
Ah maybe I spoke too soon. Stages the right files but in def download()

status,number=files[filename]

I think should be just

status=files[filename]

and number isnt needed in this function

**Comment by mhardcastle** [comment]
Darn it... OK try now...

**Comment by mhardcastle** [comment]
Think this is fixed now!
