### ISSUE TITLE
Singularity requirements missing

### ISSUE THREAD

**Issue by Joshuaalbert** [mhardcastle/ddf-pipeline#269]
I'm attempting to use the novel singularity recipe to run DDF and killMS commands.
I'm get requirement problems. To test do:
``` bash
sudo singularity build ddf-pipeline.simg ddf-pipeline.singularity
# let it build
singularity shell ddf-pipeline.simg
>> DDF.py --help
```

The first error is due to requirement `numpy==1.22.2` but the requirement is `'numpy<1.22,>=1.18'`. Here's the traceback.
![Screenshot from 2022-02-22 12-49-13](https://user-images.githubusercontent.com/14807032/155189999-fad1786c-73c1-4de4-a94f-046857619089.png)

**Comment by Joshuaalbert** [comment]
btw, I'm wondering if there is a reason to use the distro's repos for python packages rather than an environment manager like conda + pip.

**Comment by AlexKurek** [comment]
I got the same issue. Maybe its becouse of recent PyBDSFs commits / releases?
I replaced `python3-numpy` with `pip3 install numpy==1.19.5` and it seems itds OK now.

**Comment by mhardcastle** [comment]
Mine is working fine with a forced install of numpy 1.21 (similar to the solution proposed by @AlexKurek), or was last time I built it. I am testing a build from master with this one modification.

**Comment by Joshuaalbert** [comment]
Hi Martin, could you share a gist with your working recipe? Maybe I'm not placing the requirement in the correct spot.

**Comment by mhardcastle** [comment]
If my recipe works I'll push to ddf-pipeline master and then it'll be available. Just want to check that nothing has broken since I last built it.

**Comment by Joshuaalbert** [comment]
Thanks!

**Comment by mhardcastle** [comment]
Just to note that the recipe in master is working for me.

**Comment by mhardcastle** [comment]
(And the reason for using the distro repos is that they make the image quicker to build -- but it can cause problems as in this case.)
