### ISSUE TITLE
Add possible step to redo direction independent calibration step

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#27]
As a standard the direction independent calibration uses a model from TGSS. Sometimes better models are available and the direction independent phase calibration can be rapidly redone at the start of the ddf-pipeline.

**Comment by mhardcastle** [comment]
Use killms for the DI solve, presumably? What format model would you like this to accept?

**Comment by mhardcastle** [comment]
Think it's fair to say this has been superseded by the dr2 pipeline changes.
