### ISSUE TITLE
ModuleNotFoundError: No module named 'reproject.interpolation.core_celestial'

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#270]
Im getting:
```
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/mosaic.py", line 13, in <module>
    from reproj_test import reproject_interp_chunk_2d
  File "/usr/local/src/ddf-pipeline/utils/reproj_test.py", line 5, in <module>
    from reproject.interpolation.core_celestial import _reproject_celestial as reproj_interp
ModuleNotFoundError: No module named 'reproject.interpolation.core_celestial'
```
when trying to do:
`singularity exec -B [patch] ddf-py3.singularity_oryg.sif mosaic.py --directories [...] --rootname N4449_mozaic_DR2_CWL_ --exact --find_noise`
Im using original Singularity recipe (not the one I modified).

**Comment by mhardcastle** [comment]
Looks like an incompatible change in the reproject package. I'll see if I can fix or pin the reproject version in the singularity to an earlier one. Mosaicing has not been tested in the singularity environment up till now.

**Comment by AlexKurek** [comment]
Just a hint: mosaicing is working in @[tikk3r](https://github.com/tikk3r) recipe, I checked.

**Comment by mhardcastle** [comment]
Is that a python 2 setup? Reproject 0.5.1 doesn't compile in the current environment, and I suspect the C bindings.

I am going to try a patch to reproj_test that may or may not wok...

**Comment by AlexKurek** [comment]
Yes, Python 2.7.5.
Python 3.9 is not supported for Reproject 0.5.1. It seems only the latest 0.8 version supports Python 3.9:
https://pypi.org/project/reproject/0.8/#files

**Comment by mhardcastle** [comment]
Mosaicing in the singularity image now ready for testing...
