### ISSUE TITLE
Cannot find parset, some features may not work

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#274]
Im see `Cannot find parset, some features may not work` in the log-s when launching DDF:
`singularity exec -B /storage/akurek/N6946/N6946_731961/results/tar/results/ ddf-py3.singularity.sif pipeline.py tier1-jul2018.cfg`
File `tier1-jul2018.cfg` is present in `/storage/akurek/N6946/N6946_731961/results/tar/results/`:

> akurek@lof8:/storage/akurek/N6946/N6946_731961/results/tar/results$ ls
> 
> big-mslist.txt
> ddf-py3.singularity.sif
> L731967_121MHz_uv_pre-cal.ms
> L731967_123MHz_uv_pre-cal.ms
> L731967_125MHz_uv_pre-cal.ms
> L731967_127MHz_uv_pre-cal.ms
> L731967_129MHz_uv_pre-cal.ms
> L731967_130MHz_uv_pre-cal.ms
> L731967_132MHz_uv_pre-cal.ms
> L731967_134MHz_uv_pre-cal.ms
> L731967_136MHz_uv_pre-cal.ms
> L731967_138MHz_uv_pre-cal.ms
> L731967_140MHz_uv_pre-cal.ms
> L731967_142MHz_uv_pre-cal.ms
> L731967_144MHz_uv_pre-cal.ms
> L731967_146MHz_uv_pre-cal.ms
> L731967_150MHz_uv_pre-cal.ms
> L731967_152MHz_uv_pre-cal.ms
> L731967_154MHz_uv_pre-cal.ms
> L731967_156MHz_uv_pre-cal.ms
> L731967_158MHz_uv_pre-cal.ms
> L731967_160MHz_uv_pre-cal.ms
> L731967_162MHz_uv_pre-cal.ms
> L731967_164MHz_uv_pre-cal.ms
> L731967_166MHz_uv_pre-cal.ms
> mslist.txt
> mslist.txt.ddfcache
> tier1-jul2018.cfg

There are 23 MSs. Is it all OK or should I expect some problems or inferior quality?

**Comment by mhardcastle** [comment]
This is a ddfacet error not a ddf-pipeline one. It may result from deleting the DDF source tree or not having DDF_DIR set. If DDF.py is running OK then it's unlikely to cause any problems.
