### ISSUE TITLE
part b) pipeline issues with latest DDF/kMS (early 2023 versions)

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#295]
Issue on the DI calibration step:

 MS PROPERTIES: 
   - File Name: /net/lofar9/data2/shimwell/ongoing-runs/GalField5/L2011631_127MHz_uv_pre-cal.ms
   - Column Name: DATA
   - Selection: FIELD_ID==0 && DATA_DESC_ID==0
   - Pointing center: (ra, dec)=(19:09:57.150, +08.57.02.900) 
   - Frequency = 127.05 MHz [ 126.12 -> 127.98 MHz]
   - Wavelength =  2.36 meters
   - Time bin =  8.0 seconds
   - Total Integration time =   4.00 hours
   - Number of antenna  = 58
   - Number of baseline = 1653
   - Number of SPW = 1
   - Number of channels = 20
 - 12:05:02 - killMS                       | Column DATA_DI_CORRECTED not in MS
 - 12:05:02 - ClassMS                      |   Putting column DATA_DI_CORRECTED in /net/lofar9/data2/shimwell/ongoing-runs/GalField5/L2011631_127MHz_uv_pre-cal.ms

Traceback (most recent call last):
  File "/usr/local/src/killMS/killMS/kMS.py", line 1558, in <module>
    main(OP=OP,MSName=MSName)
  File "/usr/local/src/killMS/killMS/kMS.py", line 742, in main
    VS_PredictCol=ClassVisServer.ClassVisServer(options.MSName,ColName=GD["SkyModel"]["SkyModelCol"],
TypeError: __init__() got an unexpected keyword argument 'IdSharedMem'
 - 12:05:11 - ClearSHM                     | Clear shared memory
 - 12:05:11 - Multiprocessing              | reaping 1 shared memory objects associated with 1 dead DDFacet processes
 - 12:05:11 - ClearSHM                     | Clear Semaphores
 - 12:05:11 - ClearSHM                     | Clear shared dictionaries
FAILED to run kMS.py --MSName L2011631_127MHz_uv_pre-cal.ms --SolverType KAFCA --PolMode Scalar --BaseImageName PredictDI_0 --dt 0.200000 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 32 --OutSolsName DIS0 --InCol DATA --DebugPdb=0 --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIR --SolverType CohJones --PolMode IFull --SkyModelCol DD_PREDICT --OutCol DATA_DI_CORRECTED --ApplyToDir 0 --dt 1.068249 --NChanSols 4: return value is 1
Traceback (most recent call last):

**Comment by mhardcastle** [comment]
I'm now stuck on this one too. I have pushed a trivial fix to the killMS branch and will test shortly.
