### ISSUE TITLE
 part c) pipeline issues with latest DDF/kMS (early 2023 versions) #295 

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#296]
Emtpy ['BeamTimes'] in solutions. Only seen for one observation so far:

>>> t = np.load('SOLSDIR/[L2007713_140MHz_uv_pre-cal.ms/killMS.DDS0.sols.npz'](http://l2007713_140mhz_uv_pre-cal.ms/killMS.DDS0.sols.npz'))
>>> t['BeamTimes']
array([], dtype=float64)

Data has been put in Herts on /beegfs/car/shimwell/GalField5/bad-field/ to investigate.

**Comment by cyriltasse** [comment]
This is solved in the latest kMS
