### ISSUE TITLE
part d) pipeline issues with latest DDF/kMS (early 2023 versions)

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#297]
Issues after creating symbolic links (does actually create them)

 - 00:42:23 - ClassInterpol                | Coming from merged solution file, creating symbolic link
 - 00:42:23 - ClassInterpol                | Creating /net/lofar9/data2/shimwell/ongoing-runs/GalField5/SOLSDIR/L2011631_127MHz_uv_pre-cal.ms/DDS0_5175063664.01_smoothed.npz symbolic link
 - 00:42:23 - ClassInterpol                | Creating /DDS0_5175063664.01_smoothed.npz symbolic link
Traceback (most recent call last):
  File "/usr/local/src/killMS/killMS/SmoothSols.py", line 944, in <module>
    main(options=options)
  File "/usr/local/src/killMS/killMS/SmoothSols.py", line 936, in main
    CI.Save()
  File "/usr/local/src/killMS/killMS/SmoothSols.py", line 880, in Save
    os.symlink(os.path.abspath(OutFile),symsolname)
OSError: [Errno 30] Read-only file system: '/net/lofar9/data2/shimwell/ongoing-runs/GalField5/DDS0_5175063664.01_smoothed.npz' -> '/DDS0_5175063664.01_smoothed.npz'

**Comment by cyriltasse** [comment]
I'm looking into rerunnng the pipeline on your dataset @twshimwell on `smp4`. I see your data - now could you point me to the ddf-pipeline parset you're using?

**Comment by cyriltasse** [comment]
No but to adress issues a, b, c, d, perhaps I should rerun everything from start?

**Comment by twshimwell** [comment]
Ah right yes might as well. This is a galactic field so I was using a slightly different from standard parset. It was 

/beegfs/car/shimwell/GalField5/bad-field/tier1-apr2021-galactic.cfg

**Comment by cyriltasse** [comment]
ok thanks!

**Comment by cyriltasse** [comment]
I had solved this one as well I think, closing it for now
