### ISSUE TITLE
briefly revisit normalisation

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#30]
Decide between blbased, blbased, blbased and ['AbsAnt', 'AbsAnt', 'Abs'] (new versus old scheme).

**Comment by twshimwell** [comment]
Runs ongoing on P126+65 (Leiden) and L521348 (Herts).

Reason for revisiting this is because P126+65 has an amplitude error introduced by normalisation. The attached left is with normalisation None and right is BLbased.

The L521348 field does not show severe issues like this. I'm starting another field in leiden too (P23) to see if that has any clear normalisation issues.

It would be very good to access the normalisation values... anyone know how to get them?

<img width="1286" alt="screen shot 2017-04-10 at 9 56 03 am" src="https://cloud.githubusercontent.com/assets/12065270/24851443/f81cc7a8-1dd3-11e7-853c-44adf86b34bb.png">

**Comment by mhardcastle** [comment]
I'm sure we can dump the normalization values out of DDFacet.

**Comment by twshimwell** [comment]
Yeh might be a nice thing to have in the diagnostics.

**Comment by mhardcastle** [comment]
OK, there is a Norm_testing branch of DDFacet that you can pull, where the normalization factors are saved as numpy files inside the ms. You can do e.g.

```
cd my_meaurement_set.ms
gu=np.load('gu.npy')
plt.plot(gu[0,:,0])
plt.show()
```
to see the per-antenna normalization factors as a function of antenna number -- or easy to write a little script to plot up multiple mss simultaneously. The per-direction normalization factors are written out too.

**Comment by mhardcastle** [comment]
plotsols_mslist.py in ddf-pipeline/master plots solutions from all the mss in a supplied mslist.txt file.

**Comment by twshimwell** [comment]
Thanks, these normalisation files are handy. Nothing jumps out as being responsible for the amplitude error though (see attached for examples of normalisation values)


In my tests I am seeing really minimal difference between the old and the new normalisation schemes (for some reason the old normalisation creates a ~50mJy source in my field). Attached is a comparison of the image_ampphase for my field and Martins field (plus an image showing the source that was created). The left is always the old normalisation and the right is the new normalisation.

I don't think these runs need to go right to the end (let me know if you disagree and I can continue them and can run the quality pipeline). 

I also think that given there is not much difference perhaps for now we can conclude this ticket and select blbased?

<img width="1334" alt="screen shot 2017-04-10 at 4 29 13 pm" src="https://cloud.githubusercontent.com/assets/12065270/24867018/379d7336-1e0c-11e7-9aee-e72d9cd62ab7.png">
<img width="1332" alt="screen shot 2017-04-10 at 4 28 16 pm" src="https://cloud.githubusercontent.com/assets/12065270/24867028/3b461c9a-1e0c-11e7-892a-a5d5e1107b2f.png">


![screenshot from 2017-04-10 16-43-26](https://cloud.githubusercontent.com/assets/12065270/24867270/fb69a0dc-1e0c-11e7-93d0-17df2c085d31.png)


<img width="1376" alt="screen shot 2017-04-10 at 4 54 22 pm" src="https://cloud.githubusercontent.com/assets/12065270/24867718/6e4825aa-1e0e-11e7-83dd-d11d7dcf5d4a.png">



<img width="1353" alt="screen shot 2017-04-10 at 4 54 27 pm" src="https://cloud.githubusercontent.com/assets/12065270/24867746/80ea5f2a-1e0e-11e7-83f0-100a4e84f5d8.png">

**Comment by mhardcastle** [comment]
Are the plots the ones for the field P126+65 where you saw a big problem?

**Comment by twshimwell** [comment]
Yeh and these are the old normalisation (so AbsAnt) but the images are the same as blbased.

**Comment by mhardcastle** [comment]
Hmm... so nothing jumps out in the per-antenna plots either for BLBased or AbsAnt? That's where I would expect to see this rather than per direction.

Do you know which direction number shows the issue? Does it relate to either of the ones that stand out on the high-frequency plots?

**Comment by twshimwell** [comment]
Hmm, I was trying to plot the antenna variation with gu[0,:,0] but yeh unless there are 45 antennas this does seem to be the direction variation. The gu array has a shape

In [3]: np.shape(gu)
Out[3]: (1, 45, 1, 1)

how does one get the values for the different antennas?

The amplitude errors seem to be present in most directions in this field.

**Comment by mhardcastle** [comment]
That's not the shape of gu I get:
```
In [1]: gu=np.load('gu.npy')

In [2]: gu.shape
Out[2]: (1, 58, 1)
```
Aren't you plotting gmean_abs?

**Comment by twshimwell** [comment]
Yes sorry I've been plotting gmean_abs. I don't have any files called gu.npy though.

**Comment by twshimwell** [comment]
Ah, correct. For most of my runs I have both gu.npy and gmean_abs.npy but for one run (the one with Abs normalisation when making the image_full_low maps) I just get the gmean_abs.npy.

**Comment by twshimwell** [comment]
Hmm ill see how this progress through the self calibration as the plots I have now are from the image_phase1 so perhaps suffer from calibration off a poor model. However, certainly big variations in the gu.npy values, I guess its the remote stations that have the low values. Will make some plots from the later stages of the calibration tomorrow.

<img width="1205" alt="screen shot 2017-04-10 at 10 01 19 pm" src="https://cloud.githubusercontent.com/assets/12065270/24880121/7586df0c-1e39-11e7-915b-761533d40e29.png">

**Comment by twshimwell** [comment]
Yeh it looks to be the case that the image_phase1 normalisation for the remote antennas is due to a poor sky model. For the image_ampphase it is much better (see attached). In DDFacet these normalisation files are always written out with the same names, is it worth us using the e.g. f_ap1, p1, etc naming convention here too?

<img width="1165" alt="screen shot 2017-04-11 at 7 00 06 am" src="https://cloud.githubusercontent.com/assets/12065270/24893605/ed8cdeca-1e84-11e7-939d-f6a6e8f9d76d.png">

**Comment by mhardcastle** [comment]
Yes this looks more like what I've been seeing (attached). So no really obvious indication of what's causing your bad artefacts?
![gu](https://cloud.githubusercontent.com/assets/5337708/24895564/154d293e-1e89-11e7-8f97-fcec29b5371c.png)

If we want to keep these files long-term we can improve the naming -- I'd been thinking this was just for debugging.

**Comment by twshimwell** [comment]
Yes nothing obvious yet unfortunately but ill keep looking.

**Comment by mhardcastle** [comment]
By the way, just to clear this up -- BLBased does the same as MeanAbs and _then_ the baseline-based correction. So if you have Abs normalization or BLBased you get a gmean_abs; BLBased has the antenna-based gu.npy as well. If you do AbsAnt you get the 2D correction array per direction and antenna.

**Comment by twshimwell** [comment]
OK, thanks.

Now I have the solutions for the full bandwidth and still nothing obvious. 

![allsols_ants](https://cloud.githubusercontent.com/assets/12065270/24906773/76e8ea18-1eb9-11e7-9564-2b01526fed95.png)
![allsols_dirs](https://cloud.githubusercontent.com/assets/12065270/24906774/7707700a-1eb9-11e7-9026-8be2a8db879a.png)

I've started another run just to use exactly the same solutions and normalisation None (previously it was the extra step which includes both the calibration and the imaging where I saw the artefacts disappear).

**Comment by twshimwell** [comment]
Is using no normalisation a possibility in the pipeline? Or will that cause issues?

**Comment by mhardcastle** [comment]
It'll cause flux scale drift for sure...

**Comment by twshimwell** [comment]
My run using exactly the same solutions with and without blbased normalisation finished and results confirm that the normalisation is causing the severe artefacts in this particular field. So very strange nothing apparent in the normalisation values. Hopefully this field is just a one off though.

<img width="1273" alt="screen shot 2017-04-12 at 9 25 24 am" src="https://cloud.githubusercontent.com/assets/12065270/24946138/28310866-1f62-11e7-9257-78603b52fb3a.png">

**Comment by mhardcastle** [comment]
Is this compared to no norm or to MeanAbs(Ant)?

**Comment by twshimwell** [comment]
This is blbased versus normalisation = None.

The ['AbsAnt', 'AbsAnt', 'Abs'] normalisation produces very similar results to blbased.

**Comment by mhardcastle** [comment]
Yes, sorry, I see you said that already. OK. Maybe smoothing will save us. But I don't think we can do without any sort of normalization.

**Comment by twshimwell** [comment]
I notice for this field the bootstrap parameters are quite large (0.5 to 0.7). For these present tests I have not done any bootstrapping... I wonder if there is a possibility the artefacts could be related to the large bootstrap values and big variations in these as a function of frequency.

**Comment by mhardcastle** [comment]
Interesting. Is it in a strange part of the sky?

If the apparent in-band spectral indices are extreme then it's possible deconvolution will screw up and/or the models used in killms will be wrong. That's one reason for doing bootstrap early in the process.

**Comment by twshimwell** [comment]
its at 08:20:00 +64:00:00 which doesnt seem too odd.

Hmm also maybe this bootstrap idea cant explain why when setting the normalisation=None the artefacts go away can it?

**Comment by mhardcastle** [comment]
Not obviously!

**Comment by twshimwell** [comment]
The strange thing is I have an old run with the old normalisation (and with bootstrap) and that doesnt contain substantial artefacts whereas my new runs with the old normalisation (but no bootstrap) have big artefacts. Hopefully none of the changes in killms could cause this. I suspect I should start a run with bootstrap.

**Comment by twshimwell** [comment]
The strange thing is I have old runs with the old normalisation which don't show these severe artefacts (with bootstrap and from the 9th March). Then my new runs with the old normalisation (and without bootstrap) have these prominent artefacts. Hopefully it isnt a change in killms that is causing this. I guess I should run bootstrap just to see.

**Comment by twshimwell** [comment]
Oh the old one was done with MeanAmp whereas my new "reproduction" of the old one is MeanAbs... too many options :)

**Comment by mhardcastle** [comment]
I don't think there is a MeanAmp... if you had that set it's likely that no normalization was done.

**Comment by twshimwell** [comment]
OK, that run with the non existent normalisation must have been done in error.

Just a remaining question which I hope confirms that old runs where done with no normalisation. I am finding a run where the full high run was done with blbased and then the full low run was done with meanabs (this is when there was the bug in the pipeline and back when the pipeline did the high res first). This low res does not show the artefacts. I guess this is because the *cache files were created with blbased and then this run used meanabs which results in messages in the log like:

"differences in parameters (param: this vs cached) "

Perhaps this made it use no normalisation for the full low image.

**Comment by mhardcastle** [comment]
The caches definitely would have been re-made for the low-res images, because lots of things change, not just normalization. So I don't think that would have given no normalization. I think it would have used MeanAbs.

**Comment by twshimwell** [comment]
Hmm well I'm very stumped then unless I'm missing something. I have two image_full_lows which seem to have been made the same way but one has the artefacts but the other does not (both with MeanAbs). It is the only new one that has substanstial artefacts (the old one was made on the 21st March).

The images preceding this, e.g. the image_ampphase1 look very comparable between the two runs.

**Comment by twshimwell** [comment]
Could there be an issue with MeanAbs in the newest version?

**Comment by twshimwell** [comment]
Actually I've now become pretty convinced this problem I am seeing on my field is due to not running the bootstrapping and nothing to do with ddfacet... I'll start a run to investigate this but it'll take a little while unfortunately as it isnt till the image_full_low that the artefacts are really clear.

**Comment by mhardcastle** [comment]
Well, that would be consistent with everything I guess. Look forward to hearing the answer. (In a sense I would be pleased if it turned out the bootstrap is necessary for decent imaging -- I've always thought it might be but never had any evidence...)

**Comment by twshimwell** [comment]
OK, indeed it is the bootstrap. The data already had a scaled data from a previous run so I haven't redone all the steps from bootstrap and afterwards but as a test I just imaged the full_low using the solutions from the CORRECTED_DATA run and applied them to the SCALED_DATA (ill do the full run from bootstrap). Example images below are left with bootstrap and right without bootstrap. No idea really why the normalisation causes this and why Normalisation=None removes the artefacts. 

<img width="1343" alt="screen shot 2017-04-13 at 7 13 26 am" src="https://cloud.githubusercontent.com/assets/12065270/24991140/03b74808-2019-11e7-88bb-db5512c039ed.png">
<img width="1353" alt="screen shot 2017-04-13 at 7 13 16 am" src="https://cloud.githubusercontent.com/assets/12065270/24991141/03eb680e-2019-11e7-8bfe-3ed81380a872.png">

**Comment by twshimwell** [comment]
Recently finished runs with bootstrapping and with the new and old normalisation seem to show that the normalisation (blbased) causes these amplitude errors. However, I have no idea why the run with the old normalisation and without bootstrapping still showed the amplitude errors.

**Comment by mhardcastle** [comment]
Here's a comparison image showing (top) SumBLBased, (middle) BLBased and (bottom) the old calibration of a portion of L229587 (see ``/data/lofar/mjh/L229587`` for more -- including ``old`` and ``blbased`` subdirectories).

Clearly going to something less constraining than BLBased is helping a lot here (analogous to the way we used MeanAbs rather than MeanAbsAnt for final images in the old pipeline).

What do you think @cyriltasse ? Good enough?

![ds9](https://cloud.githubusercontent.com/assets/5337708/25228160/3c1cd744-25c3-11e7-8858-edf90e03ffd8.png)

**Comment by cyriltasse** [comment]
@mhardcastle well - yeah - looking really excelent... We should test the faint point and extended source statistics though between the full-GlobalNormed and the full-SumBLBased though. But we probably can do that wel we have a few pointings available.

**Comment by mhardcastle** [comment]
OK! Well, I've pushed the change to the default tier1.cfg files, and will rerun a bunch more images. If everything looks good I'll report back and then hopefully close this.

**Comment by twshimwell** [comment]
Did you do a comparison run with MeanAbs versus SumBLBased?

**Comment by twshimwell** [comment]
(using the same solutions)

**Comment by mhardcastle** [comment]
Nope. The old images are with MeanAbs but obviously different solutions.

**Comment by mhardcastle** [comment]
But if SumBLBased is good enough, which it seems to be, I'm inclined just to get on and start processing...

**Comment by twshimwell** [comment]
I also wanted to check if blbased,blbased was better than AbsAnt, AbsAnt for the first two steps and have started a run to test that which should finish late today (using the blbased for the first two and the MeanAbs for the last to compare with one that was AbsAnt, AbsAnt,MeanAbs). 

But yeh these are hopefully tiny things and processing should go ahead. For this though I'd be tempted not to use blbased and to use either:

'AbsAnt', 'AbsAnt','MeanAbs'

or 

'AbsAnt','AbsAnt','SUMBLBased'

**Comment by twshimwell** [comment]
Just to give images comparing

['AbsAnt', 'AbsAnt','MeanAbs'] and all 'Blbased'

ds9 /net/lofar8/data2/shimwell/L562061_P126_65_feb2017/uvcut_auto_oldnorm_wboot/image_full_ampphase1.app.restored.fits unsmoothed_images/image_full_ampphase1.app.restored.fits

where the old norm folder is the 'AbsAnt' etc. Shows that the old normalisation was doing a good job in this case.

**Comment by mhardcastle** [comment]
Well, let's see what your testing shows.

**Comment by mhardcastle** [comment]
But I think the important comparison is between MeanAbs and SumBLBased in the final imaging. Probably it doesn't matter what we do for the first two as long as it is something fairly restrictive to avoid flux scale drift.

**Comment by mhardcastle** [comment]
(Of course the first one doesn't matter at all because we don't apply the amplitude solutions. It's just there for completeness in case there is ever some 'normalization' that affects phase.)

**Comment by twshimwell** [comment]
Yeh I agree (provided nothing weird is happening). I'll start a final imaging with SumBLBased for comparison with MeanAbs as soon my node gets free.

**Comment by twshimwell** [comment]
I'll leave things going overnight but low images with SumBLBased and MeanAbs look very similar. At the moment to me it looks like either is probably fine.

**Comment by mhardcastle** [comment]
Good. I have another full-res run that looks improved with SumBLBased, should have a couple more tomorrow.

**Comment by twshimwell** [comment]
As expected runs done with ['AbsAnt', 'AbsAnt','MeanAbs']  and ['Blbased','Blbased',MeanAbs'] look very similar. I think we can probably conclude this ticket :) We just need to choose which one now. Anyone have a preference? I guess the choice is probably between or some combination of the two.

['AbsAnt', 'AbsAnt','MeanAbs'] 

['Blbased','Blbased','SUMBLBased']

**Comment by mhardcastle** [comment]
Well, I'm happy to stick with the latter which seems to work and is the basis of the processing I've done so far.

**Comment by twshimwell** [comment]
Great. Lets close this issue for now then.

**Comment by twshimwell** [comment]
Just for the record. Very minor difference but directly comparing images produced with the same calibration but just changing SUMBLBased  and MeanAbs. I see marginally less amplitude error artefacts on MeanAbs (attached left is SUMBLBased and right is MeanAbs).

Perhaps not worth switching for this first run given that the difference is small and several fields have already been run with SUMBLBased but perhaps something for the future (although more things may change by then too).

<img width="1031" alt="screen shot 2017-04-22 at 9 19 26 am" src="https://cloud.githubusercontent.com/assets/12065270/25302365/d73ea0a2-273c-11e7-8112-65608d8ed96b.png">

**Comment by mhardcastle** [comment]
Are the flux scales the same here? What does the difference image look like?

**Comment by twshimwell** [comment]
Yes flux scales are the same. The absblbased-absmean image also shown here.
<img width="822" alt="screen shot 2017-04-22 at 11 24 45 am" src="https://cloud.githubusercontent.com/assets/12065270/25303197/5e461ff6-274e-11e7-898b-819277de8e54.png">

**Comment by twshimwell** [comment]
The above was all on the same colour scale. Below the colour scale is the same for the two images but the range is less for the difference image to show the structure.
<img width="815" alt="screen shot 2017-04-22 at 11 26 28 am" src="https://cloud.githubusercontent.com/assets/12065270/25303221/a4b8d0b4-274e-11e7-861c-ced30d30d08a.png">

**Comment by twshimwell** [comment]
Note these runs were done with 

['AbsAnt', 'AbsAnt', 'MeanAbs']

and

['AbsAnt', 'AbsAnt', 'AbsBLBased']

using exactly the same solutions (so the same run just with a different last imaging step)

**Comment by mhardcastle** [comment]
You mean SumBLBased (I hope). OK, yes, something real going on there for sure.  I guess since we are only applying the normalization to avoid flux scale drift we should not just be asking which of the two gives the best images, but also which of the two is most correct. (No normalization at all probably gives the best images, after all.)

**Comment by twshimwell** [comment]
Sorry yes I meant SumBLBased
