### ISSUE TITLE
New version part (g): RuntimeError: Column REF_FREQUENCY is not writable

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#305]
I fixed a few more things, now when trying to run bottstrap it fails with

```
Running bootstrap
Running: bootstrap.py tier1-apr2021-galactic.cfg
Running: CleanSHM.py
 - 15:24:21 - ClearSHM                     | Clear shared memory
 - 15:24:21 - ClearSHM                     | Clear Semaphores
 - 15:24:21 - ClearSHM                     | Clear shared dictionaries
For L2007713_125MHz_uv_pre-cal.ms changing ref freq from 124218750.0 to 125096130.37109375
Traceback (most recent call last):
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 273, in <module>
    run_bootstrap(o)
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 88, in run_bootstrap
    m=MSList(o['mslist'])
  File "/data/lofar/tasse/DEV/ddf-pipeline/utils/auxcodes.py", line 360, in __init__
    t.putcol('REF_FREQUENCY', freqest1)
  File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 1155, in putcol
    self._putcol(columnname, startrow, nrow, rowincr, value)
RuntimeError: Column REF_FREQUENCY in table /beegfs/lofar/tasse/L2007713_125MHz_uv_pre-cal.ms/SPECTRAL_WINDOW is not writable
```

which is [here](https://github.com/mhardcastle/ddf-pipeline/blob/68afe568914d6b0e86fe085fa2d05ec3b1c1b383/utils/auxcodes.py#L360). The table is opened as readonly and it's a bit of a dagerous thing to do. Not sure what the idea is in that code... @mhardcastle any idea how to fix this?

**Comment by mhardcastle** [comment]
Actually this has been raised independently as #303 . I have no idea why it does this -- comes from a three-year-old commit of @twshimwell 's!

**Comment by twshimwell** [comment]
Hmmm I don't know I opened it as readonly and then tried to write to it. Should we just change it to not readonly? We do still want to change REF_FREQ to keep it the mean frequency?

**Comment by mhardcastle** [comment]
If we actually need to change the table, then we should remove the readonly flag. Maybe casacore has just started to check for this or something.

**Comment by twshimwell** [comment]
I see the inspiration for this original REF_FREQUENCY change was - https://github.com/mhardcastle/ddf-pipeline/issues/236

**Comment by cyriltasse** [comment]
Ok so I can safely change the readonly to `False`?

**Comment by mhardcastle** [comment]
I think so!


________________________________

**Comment by twshimwell** [comment]
Yeh

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cyriltasse** [comment]
Ok that solved this one
