### ISSUE TITLE
Lossing track of DATA_SUB column

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#314]
This is a pretty bad bug if not doing the bootstrap step and doing the subtraction of sources in the outer region (fortunately we dont really run with these options very often).

Line 1441 - Line 1444 of pipeline.py does:

        if o['bootstrap']:
            colname='SCALED_DATA'
        else:
            colname=o['colname']

If the outer region extract is done and bootstrap isnt done then this will reset the column to "DATA" (or whatever you have in your ddf-pipeline parset). Whereas it should be DATA_SUB as thats the appropriate column to use when the extract is done.

**Comment by twshimwell** [comment]
Pushed fix to master - [7dd8cc0](https://github.com/mhardcastle/ddf-pipeline/commit/7dd8cc03c4b2e2e31f1152d455e6a188bbbb3c84)

        if o['bootstrap']:
            colname='SCALED_DATA'
        else:
            if o['do_wide']:
                colname='DATA_SUB'
            else:
                colname=o['colname']

**Comment by twshimwell** [comment]
Same error also occurs on lines 1386-1390:

            separator("Another DI step")
            if o['bootstrap']:
                colname='SCALED_DATA'
            else:
                colname=o['colname']

Put same alteration in with [5805f10](https://github.com/mhardcastle/ddf-pipeline/commit/5805f104a0676ef25d1e587e55099bb31fa0fbcb)

**Comment by mhardcastle** [comment]
Thanks for this, seems like the right thing to do even if this isn't a mode we normally use.

We might just want a function which can be called throughout the pipeline which says 'what's our current base column'.

**Comment by twshimwell** [comment]
That might be a good idea. It seems its getting quite easy to get confused with all the different columns at the moment and very easy to accidentally make a mistake.

**Comment by mhardcastle** [comment]
Should be fixed now.
