### ISSUE TITLE
Using dt_di in parset

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#315]
Presently we always override the dt_di option in the parset by doing:

runcommand+=" --dt %f --NChanSols %i"%(dt+1e-4,n_df)

in the killms_data data function if DISettings is not none.

We should probably change this to e.g. using the automatically derived one (from give_dt_dnu) as default but if dt_di is specified in the parset we should use that value.

**Comment by mhardcastle** [comment]
The logic here was very confused but I think the test version now fixes this -- dt and NChanSols will be used if not None, else the automatically calculated ones.

**Comment by twshimwell** [comment]
Reopening issue because we accidentally changed intended behaviour.

Now the dt_di is set to whatever is in the parset or otherwise it goes to a default value of 0.5.

Instead we want the default at None (i.e. using the automatic code to find value). We also want to remove dt_di = 0.2 from our standard parsets because this is too fast -- we didnt really mean to use this value because it was always overwritten by the automatic thing. 

Attached image showing difference in a test field between dt=0.5 (bottom) and dt=0.2 (top). For this field the automatic value would be dt=2. 
![Screenshot 2023-11-30 at 12 30 22](https://github.com/mhardcastle/ddf-pipeline/assets/12065270/c9d361b1-1267-489d-b6b4-54f3d6a15433)

**Comment by mhardcastle** [comment]
Also NChansols should default to None I take it?

**Comment by twshimwell** [comment]
Yeh also None for NChanSols.

Thank you very much!
