### ISSUE TITLE
Clusterfile not set in `image_dirin_SSD_m_c_di` and `image_dirin_SSD_m_c_di_m` steps

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#319]
I can see that `clustercat=None` instead of `clustercat=ClusterCat` here https://github.com/mhardcastle/ddf-pipeline/blob/ef2fb07965e5768e54a79b07c679240ba362a324/scripts/pipeline.py#L1247 and here https://github.com/mhardcastle/ddf-pipeline/blob/ef2fb07965e5768e54a79b07c679240ba362a324/scripts/pipeline.py#L1266, this is a bug right?

**Comment by mhardcastle** [comment]
Does look that way since we have already clustered. I think you wrote that part (-:

I am working in a 'bugfix' branch right now to deal with some of these issues, so I can fix and push there.
