### ISSUE TITLE
access to SDR repository 

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#345]
SDR_wrapper experiences error:

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

when trying to access the LoTSS-DR2 repository. I followed this up at SURF but they were not able to find any issues. Anyway, a temporary fix is to change the following in sdr_wrapper.py

def request_with_retry(url,rfunction=requests.get):
    done=False
    while not done:
        try:
            r=rfunction(url,timeout=60)

to

def request_with_retry(url,rfunction=requests.get):
    done=False
    while not done:
        try:
            r=rfunction(url,timeout=60,verify=False)

**Comment by twshimwell** [comment]
And also in download_file.py

response = requests.get(url, stream=True,verify=True,timeout=60,headers=headers)

to

response = requests.get(url, stream=True,verify=False,timeout=60,headers=headers)

**Comment by mhardcastle** [comment]
This was fixed in November in commit d449ff1b3832cfcb0d0f4be70404a343898a62b2 .
