### ISSUE TITLE
Solution Smoothing

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#35]
So I've added Merge and Smooth tools to kMS to do TEC fitting. Thinking of the amplitude, I did an optional polynomial bandpass fitter. I'm not sure we can do that actually - things seem do go very wrong with some stations. So should we do TEC fit along frequency, and amplitude (spline) against time?

![screenshot - 12052017 - 17 45 25](https://cloud.githubusercontent.com/assets/6523227/26006167/bbaed9ce-373b-11e7-8253-59d779c5d857.png)

![screenshot - 12052017 - 17 46 28](https://cloud.githubusercontent.com/assets/6523227/26006132/a15a8b22-373b-11e7-94e9-46967b7407d0.png)

**Comment by cyriltasse** [comment]
Actually thinking about the amplitude smoothing I'll just do a gaussian filter with a user defined widths in freq/time

**Comment by mhardcastle** [comment]
I think that's probably safest.

**Comment by cyriltasse** [comment]
OK, I've added the Gaussian filter, it seems to be doing a fairly good job on the amplitudes, use the following line

`SmoothSols.py --SolsFileIn L401839.killms_f_ap_deep.merged.npz --SolsFileOut TestMerge.Interp.npz --Amp-SmoothType Gauss --Amp-GaussKernel 5,0.5
`
and get

![screenshot - 13052017 - 10 38 42](https://cloud.githubusercontent.com/assets/6523227/26023995/af4ad88a-37c8-11e7-922e-421948d50727.png)

**Comment by mhardcastle** [comment]
Looks good. So just to be clear, so far all that's being done here is smoothing -- there's no TEC fitting here yet? Is there a tool that splits out the merged, smoothed solutions back to a solution for each ms?

**Comment by mhardcastle** [comment]
Oh sorry, I see the answers to both questions in e-mail...

**Comment by mhardcastle** [comment]
So @twshimwell, how shall we proceed with testing this on real data? Do you want to take the lead while I work on the mosaicing and cataloguing stuff?

**Comment by cyriltasse** [comment]
So yeah phases are fitted with TEC+Const phase and amplitudes with either polynomial or gaussian filter

**Comment by twshimwell** [comment]
Great, yes I can do testing of this. I'll just wait till my ongoing runs get to a suitable place to pause.

**Comment by twshimwell** [comment]
ok I've started a low resolution run. Will post up some results when i have them

**Comment by cyriltasse** [comment]
You did do the Phase-TEC and Amp-GaussFilter, right?

**Comment by twshimwell** [comment]
Yeh I used this command

`SmoothSols.py --SolsFileIn L401839.killms_f_ap_deep.merged.npz --SolsFileOut TestMerge.Interp.npz --Amp-SmoothType Gauss --Amp-GaussKernel 5,0.5
`

**Comment by twshimwell** [comment]
first results on the low maps look interesting. The left is the smoothed and the right is unsmoothed. The negative holes are pretty much completely gone but the noise is substantially higher. I wonder if when using the normal scheme we are artificially decreasing the noise? I'll have a go making some high resolution images next.

<img width="827" alt="screen shot 2017-05-13 at 11 47 00 pm" src="https://cloud.githubusercontent.com/assets/12065270/26029503/bc7e44ba-3836-11e7-9164-c9fb536691a5.png">

**Comment by cyriltasse** [comment]
Hummm, you could also try smoothing amp only or phase only?

**Comment by twshimwell** [comment]
Sure, I can try those runs too. Just looking at the images again. If you want to look they are in

/net/para10/data1/shimwell/software/killmsddf/april-2016runs/L274093_P210_47_April_2017/L274093

The images without and with smoothing are:

image_full_low.app.restored.fits
image_full_low_smoothed.app.restored.fits

**Comment by cyriltasse** [comment]
I suspect Amp only might give a better result...

**Comment by twshimwell** [comment]
In the same directory I have now also done the low images with just amp smooth and with just TEC. Where the solutions were made with:

SmoothSols.py --SolsFileIn L274093.killms_f_ap1.merged.npz --SolsFileOut L274093.killms_f_ap1.merged.InterpAmp.npz --InterpMode Amp --Amp-SmoothType Gauss --Amp-GaussKernel 5,0.5
SmoothSols.py --SolsFileIn L274093.killms_f_ap1.merged.npz --SolsFileOut L274093.killms_f_ap1.merged.InterpPhase.npz --InterpMode TEC --Amp-SmoothType Gauss --Amp-GaussKernel 5,0.5 (note I guess the amp smoothing here isnt used but the code still needs it to be specified).

The corresponding images are image_full_low_smoothed_amp and image_full_low_smoothed_phase if you want to look at them.

The attached image shows these results, clockwise from top left this is unsmoothed, amp+tec smooth, amp only smooth, tec only smooth. To me it looks like the amplitude smoothing and the tec both play roles in the noise increase (phase smoothing more so) and also both are quite effective at getting rid of the halos and holes (best results here when both applied). 

I'll get the same type of images for the high resolution now and we can see how those look (perhaps that will reveal more issues with the phase as we are still at fairly moderate resolution here). Also once those are made then its probably worth comparing things like the source fluxes.



<img width="1233" alt="screen shot 2017-05-15 at 8 00 09 pm" src="https://cloud.githubusercontent.com/assets/12065270/26071710/481d1ffa-39a9-11e7-87b7-70a80b9a249f.png">

**Comment by mhardcastle** [comment]
I don't want to rain on the parade, but increased noise was exactly what we saw when we just smoothed amplitude in time and I am not convinced that we are doing anything here other than decreasing the significance of the holes/halos by pushing up the noise floor.

**Comment by twshimwell** [comment]
Yeh I think we are seeing the same here as when we just did the simpler amplitude smoothing. These images are all on the same colour scale, perhaps it seems a bit fainter but yeh ideally we don't want the noise to increase.

This is all post processing on solutions with a uvmin of 1.5klambda. Really for this I think the hope is that we can get rid of that uvmin (which also gets rid of the halos/haloes) and not loose the diffuse emission. I'll try this next.

Do you think its worth updating the pipeline to optionally use these new smoothing scripts rather than the old smoothing script? I wouldn't be sure what to do in the early stages though when we just have sparser frequency coverage.

**Comment by twshimwell** [comment]
The high resolution images show similar results to the low resolution images. So, the attached image shows these results, clockwise from top left this is unsmoothed, amp+tec smooth, amp only smooth, tec only smooth. Again it looks like the amplitude smoothing and the tec both play roles in the noise increase (phase smoothing more so) and also both appear to be quite effective at getting rid of the halos and holes (best results here when both applied although as Martin points out it also just lowers the signal to noise of the holes/haloes).

<img width="1207" alt="screen shot 2017-05-17 at 5 09 01 pm" src="https://cloud.githubusercontent.com/assets/12065270/26161214/9163460a-3b23-11e7-855c-5ca033bc0981.png">
<img width="1206" alt="screen shot 2017-05-17 at 5 07 50 pm" src="https://cloud.githubusercontent.com/assets/12065270/26161215/917eefea-3b23-11e7-8e57-8d59f059e23c.png">


I'll now try working on a dataset where I've done the 2nd selfcal so I have solutions with no uvmin. I'll try smoothing those solutions (amp+tec, tec only, amp only) and see if I can get back some of the diffuse emission as in this field there is plenty of diffuse emission associated with a large galaxy in the field that disappears at the 2nd selfcal step.

**Comment by twshimwell** [comment]
Attached is a comparison between the regular image_full_ampphase1_smoothed (amp smoothing + tec), image_full_ampphase1 (uvmin 1.5klambda) and image_full_ampphase2 (uvmin none) in the top left, top right and bottom left respectively. 

It seems that with the smoothing we are able to recover some of the diffuse emission without using any uvmin. However, the noise is higher and there is still less diffuse emission than when using the uvmin in the calibration (although it could be that some of this emission is a halo but from other maps its known that this big extension out of the north and south of this galaxy are indeed real).

<img width="999" alt="screen shot 2017-05-18 at 4 49 31 pm" src="https://cloud.githubusercontent.com/assets/12065270/26208313/1020ea62-3bea-11e7-989a-d97dba17361d.png">

**Comment by mhardcastle** [comment]
Conclusion: smoothing doesn't remove the effects of fitting the data with an incorrect model, but reducing the number of degrees of freedom helps. I think this is as expected. I still think it's fundamentally the wrong thing to do to fit all the data with a model we know to be incomplete.

**Comment by twshimwell** [comment]
Looking at solutions for fields where the calibration isnt going too well I sometimes see clear outliers in the solutions. Perhaps it would be interesting to see the impact of flagging these concatenated solutions (and not smoothing).

<img width="630" alt="screen shot 2017-05-22 at 6 20 31 pm" src="https://cloud.githubusercontent.com/assets/12065270/26318477/81299798-3f1b-11e7-9b7b-a1fbd235f953.png">

**Comment by mhardcastle** [comment]
While the smoothing is still in the code and still something to think about this issue related to the holes and again that's more or less closed by the powersmooth modification, so closing for now.
