### ISSUE TITLE
Improve bad facet identification

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#352]
We attempt to recognise bad facets by the errors in the astrometry derived from PanStarrs. Presently we use a criteria of 0.5" and if the error exceeds this then during mosaicing (in mosaic.py) we blank the facet. This approach needs revising because its been found that this criteria sometimes removes perfectly good facets particularly at low declination or low galactic lattitude.

In offsets_compact branch the new script find-bad-facets.py attempts to detect poor facets using the image_full_low_m image by looking at a number of different things including: properties of a Gaussian fitted to the facet pixels, trying to identify jumps in the noise properties at facet edges, the dynamic range and the astrometry. Each facet then gets a score for how bad it is depending on these properties and hopefully poor facets can be moderately robustly identified.

**Comment by twshimwell** [comment]
I wonder if the fastest approach here is a little bit manual. The script seems pretty good at finding bad facets but sometimes finds too many. So what I can do is run it over all fields in LoTSS-DR3 and about 1 in 10 of these it will find has a bad facet. I could simply then inspect them by eye.

If we added a column into the quality database where a list of bad facets could be given then I could populate that... 

It'll be a slightly painful task but might be more robust.

**Comment by mhardcastle** [comment]
Pretty horrendous if you have to inspect every single field where there's something flagged up! Is it always the case that the false positives are big extended sources like in this example?

**Comment by mhardcastle** [comment]
We could ignore small 'bad' facets as they will quite often be dominated by bright sources, or they wouldn't be small in the first place. Also if they are actually high-noise in the rms maps they'll be weighted down in the mosaic. Might be useful to think in terms of what level of badness we actually need to filter out...

**Comment by twshimwell** [comment]
Hmmm good point indeed. Maybe a simple solution then is just to always keep the smallest few facets so ill try that.

**Comment by twshimwell** [comment]
find-bad-facets.py saves Facet_statistics file and a BadFacets.txt file giving the statistics of all the different facets and the facets declared bad.  

Pretty ok but still requires a manual check really. 

I think this one is now done (all existing LoTSS-DR3 fields examined)
