### ISSUE TITLE
Mosaic pointing script should check DR3

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#355]
Check the DR3 field in the database in the mosaic script.

**Comment by twshimwell** [comment]
Maybe it could only use pointings that have 2 in the DR3 entry. So all fields that will make up DR3 have 1 in that entry but once verified (i.e. compared checksums and done bad facet identification and redone the offsets) I can then change them to 2.

**Comment by mhardcastle** [comment]
Sorted in the current version.
