### ISSUE TITLE
Towards public release

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#37]
ddf-pipeline has always been public but we should try to co-ordinate releasing a publicly usable version with the planned releases of DDFacet and KillMS.

Minimum set of things that needs doing:

* decide on a licence
* add documentation taking a user through installation and running of the code
* tidy up the root directory (massively -- it's a big mess)
* decide what's in and what's out (e.g. there are lots of scripts for the Zooniverse project in there that probably should just move to another github).
* setup.py script for a proper install

Any other suggestions?

**Comment by cyriltasse** [comment]
For the license we use GNU2 for DDFacet, and I'll probably do the same for kMS.

**Comment by mhardcastle** [comment]
Draft public release branch in pub_release -- with GPL2.

**Comment by mhardcastle** [comment]
All done except the last one. Going to implement Cyril's suggestion for a script that does all the cloning and pulling of his code as soon as the relevant bits of his code are public.

**Comment by mhardcastle** [comment]
Done now, pub_release merged to master. `install.sh` script pulls the public versions of DDFacet and KillMS.

This needs testing, though any problems should be pretty trivial.
