### ISSUE TITLE
fit beam

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#43]
Would be nice to fit the synthesized beam if possible and not done with ddfacet.

**Comment by cyriltasse** [comment]
Thinking about this - maybe the best way to do this would be to fit the psf with pybdsm - telling it we have a restoring beam of 0.0 arcsec... the answer it will give for that fake source is the one we want?

**Comment by twshimwell** [comment]
OK, if this is the easiest way to do it then it sounds ok. I guess we would just need to do this after the initial direction independent run to make the dirty image which gives a psf image. Also at the low resolution step and also at the final high resolution step we would need to split up the imaging similarly.

**Comment by twshimwell** [comment]
I see there is a new psf fitter in ddfacet so could try this again.

**Comment by twshimwell** [comment]
Hmm yeh thats a good point. In the survey when we go to low dec our psf is going to get very elongated. Perhaps we should have different restoring beams for different dec ranges?

**Comment by mhardcastle** [comment]
Yeah I agree we're going to need that. Wendy used a significantly larger beam for the GAMA fields for example.

**Comment by wllwen007** [comment]
Yeah, definitely. I used a 8x9 arcsec beam determined from my own fits to the psf. WSClean at least was fitting a very large beam to the very wide wings of the psf so may be interesting if DDFacet does this differently...

**Comment by cyriltasse** [comment]
The fitting code (which was so sh*t) was recoded by Oleg - should be better now?... Hopefully...

**Comment by mhardcastle** [comment]
Is this merged into your working branch though?

**Comment by cyriltasse** [comment]
currently testing it - but yeah - in `ddf_pipeline_fixes_MergeCyril`

**Comment by cyriltasse** [comment]
I'd advice you to wait a bit more before testing the newer pipeline, it's a bit unstable right now...

**Comment by mhardcastle** [comment]
So on a quick test Oleg's fitter looks to do a lot better job on LOFAR data than what was in there before: it gets 6 x 4 arcsec for the DDF test image (which is the 150-MHz MS from one of our LoTSS images) whereas the old fitter got 135 x 111 arcsec (!).

As it's already possible in the pipeline to specify any beam, including an elliptical one, or none at all and use the default DDF fitted beam, I think we can close this issue as a pipeline issue. Might be interesting to try free fitting to the PSF to see what it makes of a low-dec field.
