### ISSUE TITLE
Automatic pull

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#46]
Would there be a wahy to make the pipeline automatically pull to the github directories of its dependencies? Like if I find bugs in DynSpecMS, and fix, would be nice for ddf-pipeline to pull - so that I don't have to mail you to pull...

**Comment by mhardcastle** [comment]
I think it would be possible but it would have to be an option -- there are plenty of times when you're testing with private versions of the dependencies and the last thing you want to do is pull.

**Comment by mhardcastle** [comment]
control-pull option added in the development version, i.e. run with --control-pull=True. We may want to make this the default at some point, currently it's not.

**Comment by mhardcastle** [comment]
I guess we can close this for now, I have been using the option quite a bit and it seems to do the job.
