### ISSUE TITLE
Caching question

### ISSUE THREAD

**Issue by sabourke** [mhardcastle/ddf-pipeline#47]
Should the MSs be on fast storage or is having cache_dir on fast storage sufficient? I'm wondering if I should copy the MSs to fast storage prior to running the pipeline or if that would be pretty pointless?

**Comment by twshimwell** [comment]
It puts things in /dev/shm so the speed of the storage shouldnt matter much.

**Comment by mhardcastle** [comment]
I put cache_dir on fast storage if I have it, and leave the original mss on slow (i.e. NFS) storage, which seems to work. Depends how slow your slow storage is, of course.

**Comment by sabourke** [comment]
Ok, great. Thanks for the info!
