### ISSUE TITLE
Cleaning depth

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#49]
Need to go a bit deeper in the cleaning/masking it seems. Looking at LoTSS data release catalogue and going through all the sources to see if they are masked in each of the images that they appear in (usually 3 or 4) I seem to be finding that sources with total fluxes less than 1-2 mJy are generally not masked in all the images.

**Comment by mhardcastle** [comment]
Isn't this because they are down the beam in some of those images and so not actually above the noise threshold?

**Comment by twshimwell** [comment]
I believe so

[Screenshot 2017-12-05 14.15.45.PDF](https://github.com/mhardcastle/ddf-pipeline/files/1531248/Screenshot.2017-12-05.14.15.45.PDF)

**Comment by twshimwell** [comment]
Thats just 2000 sources that I did first and sources up to (in exceptional circumstances) 1-2mJy are impacted. I will look at a few to see distances from the pointing centres but will make the whole catalogue first to find some nice examples.

**Comment by mhardcastle** [comment]
Is this the beam-weighted masked fraction that you're plotting now?

**Comment by twshimwell** [comment]
Yeh its the sum of the weight images at the position of the source when its in the mask divided by the sum of the weight images at the position of the source for all images it is within.

Always excluded facets blanked due to astrometric errors (I think these are blanked in the weight images anyway). The weight images also are blanked outside 0.3 of the primary beam.

**Comment by mhardcastle** [comment]
Hard to tell from the plots, but I'm guessing the fraction of sources with masked_fraction<0.8 (say) isn't that high?

**Comment by twshimwell** [comment]
in the mosaics for DR1 

62% have a masked_fraction less than 0.8
32% have a masked_fraction of 0.0

**Comment by mhardcastle** [comment]
Yeah, so very high then. This is strange. There are sources with peak fluxes of tens of mJy with Mask_Fraction=0. You have to be up at Jy level to guarantee Mask_Fraction=1. And there doesn't seem to be much relation at all between flux and fraction (see plot).

It would be interesting to see if this is improved by going deeper but right now I'm concerned whether we even have the right answer.

[fraction.pdf](https://github.com/mhardcastle/ddf-pipeline/files/1562130/fraction.pdf)

**Comment by twshimwell** [comment]
Hmm ok ill check the code again and look at one of these examples of high flux no mask.

**Comment by twshimwell** [comment]
Perhaps this type of thing is happening. 

[Screenshot 2017-12-15 10.29.26.PDF](https://github.com/mhardcastle/ddf-pipeline/files/1562178/Screenshot.2017-12-15.10.29.26.PDF)

**Comment by mhardcastle** [comment]
That'll certainly be a problem for some of them. PyBDSM's being too clever here isn't it... we might need to go back to the Gaussian catalogue )-:

(What I'm after would be some way of saying 'fluxes are reliable above this threshold'.)

**Comment by twshimwell** [comment]
Yeh I guess that we might have to go back to the gaussian catalogue then (just showing the actual masks for the source above). So ill just take the RA and DEC of each gaussian and provide a masked catalogue for that. Not quite sure how to then merge that into the source catalogue.

[Screenshot 2017-12-15 10.42.11.PDF](https://github.com/mhardcastle/ddf-pipeline/files/1562214/Screenshot.2017-12-15.10.42.11.PDF)

**Comment by mhardcastle** [comment]
Take the average of the Mask_Fractions for all the Gaussians that go to make up a source, I guess.

**Comment by twshimwell** [comment]
Yeh maybe flux weighted.

**Comment by twshimwell** [comment]
Is this needed urgently? If so I can make the code better but presently it will run until Sunday.

**Comment by mhardcastle** [comment]
No,  nobody is going to need this in a hurry. We just need to get our story straight before the final catalogue release. 

I'll reopen the issue over on the catalogue github.

**Comment by mhardcastle** [comment]
I think we have a general agreement that we need to go deeper in the next iteration of processing. Closing this as a pipeline issue.
