### ISSUE TITLE
enhancing quality pipeline

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#55]
Would be nice to make this a bit better. Not quite sure what is best but things we could consider:

-- source counts (not sure how time consuming this but it would be nice)
-- dynamic range (not crucial but might be nice)
-- writing out some quality numbers to a file
--  looking at drift in fluxscale from bootstrapped values
-- moving from first to panstarrs for astrometric checks
-- perhaps looking at source sizes too.

**Comment by mhardcastle** [comment]
I've done most of this over the past few days. Running the quality pipeline currently dumps some stuff out to the surveys database including a DR estimate and numbers of sources in the central 16 deg^2. I will eventually run the quality pipeline for everything that comes into the public archive at Herts so all this info can be accumulated for every field.

I think there is quite serious flux scale drift in DR2, but that's probably a new issue.

**Comment by twshimwell** [comment]
Great! This sounds really useful. I guess the flux scale drift isn’t too surprising given that DR1 had quite big errors too.
