### ISSUE TITLE
UCS2 error running DDFacet

### ISSUE THREAD

**Issue by sposullivan** [mhardcastle/ddf-pipeline#56]
After installing the ddf-pipeline I get this error after typing 'DDF.py -h':
ImportError: ~/DDF/DDFacet/build/lib/DDFacet/cbuild/Gridder/_pyWeightingCore.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize

My version of Python2.7 (on a CentOS Linux machine) uses a 4-byte representation for Unicode characters (UCS4), so does the above error mean _pyWeightingCore.so was compiled with UCS2? 
Any suggestions on how I might fix this error? Or how I might build the DDFacet Gridder to work with a UCS4 python build?

when running ./ddf-pipeline/scripts/install.sh I get two somewhat concerning outputs (though maybe unrelated to the above issue):
1. -- Invalid option for BUILD TYPE, defaulted to 'Release' build
CMake Warning at Gridder/CMakeLists.txt:9 (message):
  Instructing gcc to use your native supported instruction set.  This will
  break .so portability and may raise the ILLEGAL_INSTRUCTION signal on
  incompatible chipsets
2. package init file 'SkyModel/__init__.py' not found (or not a regular file)

**Comment by mhardcastle** [comment]
This is strange, because obviously the C code should be compiled at install time, i.e. on your system, so it should match your system's setup. Is there anything obviously wrong with the output of configure (just before the compilation where it reports on where it finds python and the libraries)?

Warning (1) is nothing to worry about as long as you build on the same system you intend to run on.  Warning (2) can safely be ignored since SkyModel is installed separately.

**Comment by mhardcastle** [comment]
By the way, CentOS should work fine as a general proposition -- my local system uses Scientific Linux which is very similar.

**Comment by sposullivan** [comment]
Maybe this, just after 'python setup.py build':
fatal: No tags can describe '58806e7e5623fa7c51f2e11843b15250c5f3201f'.
Try --always, or create some tags.
running build

Full output here:
[ddf_install.log](https://github.com/mhardcastle/ddf-pipeline/files/1759419/ddf_install.log)

**Comment by mhardcastle** [comment]
OK, this
```
-- Found PythonLibs: /sw/env/gcc-6.4.0_openmpi-2.1.0/pkgsrc/2017Q2/lib/libpython2.7.so (found version "2.7.13") 
-- Found PythonInterp: /home/stnv061/anaconda2/bin/python (found version "2.7.14") 
-- Found NumPy: /home/stnv061/anaconda2/lib/python2.7/site-packages/numpy/core/include  
```
looks like two different version of Python are being found (pythonlibs is coming from a completely different place from pythoninterp). I think that might be the problem. 

I don't understand the error message about tags but I get it too and it doesn't appear to have any effect.

**Comment by sposullivan** [comment]
Thanks Martin, that helped me track down the issue. 
I needed to add this to setup.py in DDFacet so that cmake would use the right library:

subprocess.check_call(["cd %s && cmake -DPYTHON_LIBRARY=/home/stnv061/anaconda2/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=/home/stnv061/anaconda2/include/python2.7/ .. && make" % path, ""], shell=True)

from https://stackoverflow.com/questions/42548750/how-to-set-the-default-library-path-for-python/42549431

now 'DDF -h' works
