### ISSUE TITLE
Spectral imaging

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#57]
We should give the user the option to make the final image as a cube with a user-specified number of channels. This costs almost nothing since two channels are made internally anyway: allows spectral index/curvature images to be made.

**Comment by sposullivan** [comment]
This would be very nice to have from a polarization imaging (Q, U) perspective also...

**Comment by cyriltasse** [comment]
@sposullivan `DDFacet` can do polarisation imaging - but no deconvolution - what do you have in mind?

**Comment by cyriltasse** [comment]
What I was thinking of for your science case was to add a final step to image the IQUV residuals...

**Comment by mhardcastle** [comment]
I suspect making enough channels to do sensible rm synthesis work is going to be too expensive.

At some point someone needs to sort out a plain old clean option for DDFacet to deconvolve QUV!

**Comment by sposullivan** [comment]
The plan is to find some way of getting Q,U images at something like 50 or 100 kHz channels, such that we can run RM synthesis on the bright Stokes I sources. I was chatting with Tim and trying to do a initial test with Q and U dirty images. Currently having some install issues with DDF...
Grand plan is to do this for all of LOTSS...

**Comment by mhardcastle** [comment]
That's a 20000 x 20000 x 480 image cube...

**Comment by twshimwell** [comment]
Can just do it for little regions around sources?

**Comment by sposullivan** [comment]
At the moment, I use Factor calibrated data to image cutouts after phase-shifting the uv-data to the source of interest. Maybe we can do some similar cutout imaging with ddfacet?

**Comment by mhardcastle** [comment]
Yes that would work -- but I think imaging everything on spec on a pipeline basis is not going to be viable. Maybe we could build something into the pipeline to identify sources with enough SNR to be possible targets and then do little cutouts round each one. (Maybe this is what everyone else is talking about and I'm just being slow on the uptake!)

**Comment by sposullivan** [comment]
The plan is to start with a catalog of sources (eg. LOTSS Stokes I) and start imaging everything with peak I flux of ~30 mJy or greater. Exact flux cutoff will need more careful thought based on what we may miss versus how long it will take, etc.

**Comment by cyriltasse** [comment]
Could be not very diffificult to also do the (20k**2)x480 cube if necessary.

Also - do you need imaging - or is single pixel spectra in a discrete set of directions enough? Cos then it's be trivial to incorporate this in DynSpecMS (where we form dynamic spectra in pre-selected directions - and that's already in the pipeline)... I kind of love this idea actually...

**Comment by mhardcastle** [comment]
From the pipeline point of view, this would need to be done automatically (otherwise you need to get all the MSs and the model images and pick up where the pipeline leaves off). It's not completely unlike the code of Cyril's to make dynamic spectra at (externally specified) positions, but would need some image analysis to find the positions on the fly.

**Comment by sposullivan** [comment]
Dynamic spectra sounds great (but need to read exactly what it does first), for finding polarized sources because most sources will not be polarized. In most cases the instrumentally polarized signal at RM ~0 will be larger than the real signal (at eg RM = 20 rad/m2); will this be a problem for the dynamic spectra? 
And when a polarized source is found, I would want to image the whole source because the resolved RM distribution would be of most interest to me.

**Comment by cyriltasse** [comment]
Not sure I understand you first question, but the whole pipeline works only on I-stokes. Now in the new pipeline there is a full-pol DI calibration, so the intrumental RM is removed to the first order. Second order will make residual I-stokes to leak a bit into the visibility cross pols. To looked at in real data easily, you can start with just launching DynSpecMS in the directon of a bright off-axis source of one of LoTTS field (and a few pixels off in empty regions for comparison), and see what happen. It produces `fits` files with (t,nu,IQUV) cubes... Then you'll have your answer.

For the second question, `DDFacet` could do just that quite effisciently, provided a list of target, image sizes, and some little work... This probably has more prospects?

**Comment by sposullivan** [comment]
Thanks Cyril. Looking forward to investigating DynSpecMS. I expect I will have to use DDFacet in any case so I will continue with this also.

**Comment by mhardcastle** [comment]
This is now an option in the pipeline. Needs testing, then we can close this issue.

**Comment by mhardcastle** [comment]
OK, the spectral imaging seems to work. Oddly the band images don't get the right frequency in the FITS header, which is probably my screwup somewhere in DDFacet... will leave this open till I get a chance to look at it.

**Comment by mhardcastle** [comment]
After nearly 2 years of not fixing this I have just put the header fix in the pipeline.
