### ISSUE TITLE
change default psf values in parset.py to None?

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#58]
Might be nice to by default let ddfacet fit the psf and otherwise change it in the parset.

**Comment by twshimwell** [comment]
not really surprisingly but the psf fitting in ddfacet doesnt get it right for lofar dec 0 obs.

**Comment by mhardcastle** [comment]
This is new ddfacet with Oleg's improved fitter?

**Comment by twshimwell** [comment]
Its the latest ddf_pipeline_fixes_MergeCyril_issue474 branch which I think has the improved fitter. The attached shows the ddfacet fitted psf (63x25arcsec) and what id get from fitting in casaviewer (pix 1.5arcsec as usual).

<img width="1233" alt="screenshot 2018-03-22 16 17 31" src="https://user-images.githubusercontent.com/12065270/37779426-a712ef34-2dec-11e8-8e27-9db2399845b4.png">

**Comment by cyriltasse** [comment]
This is an issue for the DDFacet github...

**Comment by mhardcastle** [comment]
When all the excitement in DDFacet has died down and there is a stable merged version I would raise this as a DDFacet bug. It should clearly be able to do better than that.

**Comment by mhardcastle** [comment]
Agreed that this needs fixing in DDFacet. (We should be doing something sensible about the forced PSF at low dec but letting DDFacet fit for it is not the solution at the moment -- and will never be for LoTSS because mosaicing requires us to force a fitted beam.)
