### ISSUE TITLE
DR2 bootstrap

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#61]
DR2 pipeline will need the bootstrap to work again. Needs to be done after first phase self-cal as before since otherwise the model image amplitudes will get out of step with the UV data. Should be trivial to fix.

**Comment by mhardcastle** [comment]
I plan to streamline the parsets for this by saying that the bootstrap image is always the same size and resolution as the low-resolution image.

**Comment by mhardcastle** [comment]
Would add quite a lot of runtime if we did it properly.

I guess we've ditched the amplitude normalization somewhere along the line, though, so we ought to check what effect that has.

**Comment by twshimwell** [comment]
Yeh, good to see if it is necessary but also in DR1 i think it drifted a bit sometimes. Perhaps at the end it could be done just on the continuum image which could then be scaled (so not going through the different SB blocks again).

**Comment by mhardcastle** [comment]
We could certainly check it on the low-res image but if we were doing the thing where we make multifrequency images then scaling wouldn't really work properly...

**Comment by mhardcastle** [comment]
Bootstrap is back in, anyway. Need to test with a full run and look at the flux scale drift between the bootstrap results and the end product (the low-res map now always matches bootstrap so it would be a good one to use for the comparison).

**Comment by mhardcastle** [comment]
A major bug in the way bootstrap interacts with the different DR2 columns should hopefully now be fixed.

**Comment by mhardcastle** [comment]
Seems to be OK now, closing.
