### ISSUE TITLE
DR2 control/restart

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#62]
The exit-after and restart-from control options are broken in the DR2 pipeline version(s) and should be fixed (in particular the ability to restart from a given stage would be useful).

**Comment by mhardcastle** [comment]
exitafter may now be fixed. Restart not yet.

**Comment by twshimwell** [comment]
Great. What should we do about the IMAGING_WEIGHTS with the restart? These can change if the pipeline has done more kms runs.

**Comment by mhardcastle** [comment]
The first imaging steps should never use IMAGING_WEIGHTS anyway. If restarting from after the first killMS run then it's valid to use the weights that are there. If restarting from somewhere in the middle, well, I guess you take your chances -- restarting is only really there for test purposes.

I guess ideally we would store the imaging weights from each killms run but I don't think it's worth the hassle...

**Comment by twshimwell** [comment]
Yeh ok. 

Maybe we should have an option (that ofcourse would be very rarely used but might be handy for restarting failed runs) to reset imaging_weights? We can just put them all to 1?

**Comment by mhardcastle** [comment]
There is now a remove_columns option that will remove all the pipeline-generated columns at the start of a run (best used on the command line i.e. `--control-remove_columns=True`). When I get round to looking at the redo-from options properly, I'll probably do this there as well.

**Comment by mhardcastle** [comment]
OK, I think, looking at this, the redo-from option just can't be done properly in the way it was in the DR1 pipeline, because of the re-use of columns for DR2 (e.g. PREDICT). We can redo from the start or from after the dirin image is made, removing all columns, but after that we're stuck because we don't know where the PREDICT_DATA comes from. Since I want to redo the fields affected by #147 from the dirin stage, I have implemented that, and am closing this issue.

(Also remove_columns now removes IMAGING_WEIGHT, so this is automatically reset with that option. Recommended way of restarting is now `--control-redofrom=start`.)
