### ISSUE TITLE
DR2 astrometry fixes

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#63]
The astrometry code needs fixing in the DR2 pipeline. Should be a case of just reinstating the old code but does the option still work in DDFacet? (Also see issue #57 -- if we make image cubes by default then we need the re-stitching to work on cubes too.)

**Comment by mhardcastle** [comment]
Offsets code is working again now. DDFacet parts still need investigation.

**Comment by cyriltasse** [comment]
ok, I've updated the code to do three shifted images in the three bands discussed by email
