### ISSUE TITLE
DR2 multiple pointings

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#65]
@twshimwell has already put this code in, need to test and close this issue when it works.

**Comment by mhardcastle** [comment]
I think there were a couple of bugs in the naming of files to check (affects restarts). Pushed what I believe are fixes.

**Comment by twshimwell** [comment]
Ive pushed a fix to this. It now creates symbolic links in the SOLSDIR directory for each msfile to link that msfile to a the appropriate smoothed solution set.

**Comment by twshimwell** [comment]
This seems to work so ill close this issue. Reopen if any issues.

**Comment by twshimwell** [comment]
Warning -- this crashes when trying to do DDS1 calibration after image_phase step. This is because kMS cant find the solutions because it doesnt look in SOLSDIR. Fix required in kMS.

**Comment by twshimwell** [comment]
Cyril has pushed a fix to kms so that this works now.
