### ISSUE TITLE
DR low res

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#66]
Put low resolution imaging back in before the final high resolution imaging and use the mask from the low resolution imaging to help get diffuse sources masked

**Comment by twshimwell** [comment]
I guess this should go in before the image_full_ampphase_di_m.NS step. However, that step doesnt do any deconvolution at present so wouldnt benefit a great deal from an improved mask... 

Maybe we should do a few major cycles on image_full_ampphase_di_m.NS?

**Comment by mhardcastle** [comment]
I think we definitely should add at least one. (Should be an option -- too much stuff is hard-wired in right now.)

**Comment by twshimwell** [comment]
OK well ive pushed to master-fixes_DI_3_3C_CubiCalkMS to add back in the low resolution imaging again (at the correct place). As we had in the old version (e.g. master-fixes). We now have:

-- same low resolution imaging
-- an extended mask is made from image_full_low_im and merged with the previous clean mask (im not sure why we didnt use image_full_low_m for this -- i guess just because we had to do this step on image_full_low_im anyway?)

Slight alterations (hopefully everyone agrees here):

-- in the present code the image_full_ampphase_di_m wasnt used to update the mask (the code was there but this was commented out for some reason). So ive used this again with o['thresholds'][2] as the cleaning threshold.
-- similarly the dicomodel masking on image_full_ampphase_di_m was also commented out. This is now in there to provide the CurrentBaseDicoModelName which also makes use of the new improved masking from the low resolution step.
-- now we do 1 major cycle on image_full_ampphase_di_m.NS but maybe this should be an option or at least tested to see how many major cycles we want.

After a bit of testing maybe this issue can be closed if I havent messed things up.
This needs testing. Also we need to add in the option for the major cy

**Comment by mhardcastle** [comment]
OK, let's test and close all of these issues when we're happy with the results.

**Comment by twshimwell** [comment]
Should add the init negative thing to the low res

**Comment by twshimwell** [comment]
ive pushed to master-fixes_DI_3_3C_CubiCalkMS a change so that all full low images use  AllowNegativeInitHMP=True

Once we have a few fields where we can check the low_m images are adequately deconvolved with noiselike residuals I think this issue can be closed.

The only outstanding thing was that the present position of this low step, between the two final high resolution steps, increases the compute time. However, it seems to me this is worth it to get better masks but not sure if anyone feels otherwise.

**Comment by twshimwell** [comment]
Seems fine.
