### ISSUE TITLE
Add back smoothbeam

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#67]
In the old version we have the smooth beam for all image_full steps. I guess we want the same here? That would be:

image_full_ampphase_di
image_full_ampphase_di_m
image_full_low
image_full_low_im
image_full_low_m
image_full_ampphase_di_m.NS

**Comment by mhardcastle** [comment]
Is it actually needed for anything but the final images?

**Comment by mhardcastle** [comment]
(not that it matters I guess since it should be possible to force it to reuse the cached version)

**Comment by twshimwell** [comment]
ok, im not sure if its needed for anything but the final ones. But yeh I guess it doesnt matter which is why we did it before. Ive pushed an update that uses the smooth beam for all the image_full* images.

**Comment by twshimwell** [comment]
Smoothbeam is now implemented. Closing this issue.
