### ISSUE TITLE
change powersmooth to zero?

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#68]
Currently we are still running with powersmooth at 1.0 (the default). Now we have a small uvmin of just 0.1 i guess this doesnt matter much but maybe we want it at 0.0?

**Comment by cyriltasse** [comment]
This doesn't really matter - it's playing a role when using a uvmin - which we don't do anymore...

**Comment by twshimwell** [comment]
ok. ive changed the default to 0.0 then just so its more clear its not doing anything. I've pushed that.
