### ISSUE TITLE
check covq values used

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#69]
presently im seeing quite a few bad facets appear when doing the image_full steps which might be due to covq in kms.

The covq values used in the earlier part of the pipeline are 0.02 (where im not seeing bad facets) and in this later part are 0.1. Maybe we dont want to be as high as 0.1

**Comment by mhardcastle** [comment]
So the obvious question is whether you've tried changing the covq and rerunning...

**Comment by cyriltasse** [comment]
Decreasing CovQ will make faint facets more robust, but DR in bright ones less. That field wher Tim has bad facets has got M51 poorly deconvolved. So we should deconvolve it well (by enabling the negatives initHMP), and if the problem persists, decrease CovQ... I think.

**Comment by twshimwell** [comment]
Yeh im trying this now. Im starting by redoing the image_ampphase_di and putting on the allow negatives option (which I see was turned on at this step at somepoint but is presently commented -- maybe not always good?). I'll see if that works and if not ill try gradually decreasing covq. Its quite a time consuming to test...

I guess ideally we want covq as high as possible so if this is a rare case then we dont want to change it i guess.

**Comment by twshimwell** [comment]
Just looking at the deconvolution when using this allow negative option to not using it. Left doesnt use it and right does.

-- extended sources seem better without it.
-- point sources seem quite a lot worse..

We currently have this option in all the full imaging (I guess because we have been testing mainly on diffuse emission). I wonder whether we should because of degrading the point sources.

<img width="715" alt="screenshot 2018-06-08 08 59 03" src="https://user-images.githubusercontent.com/12065270/41143653-58f4589c-6afa-11e8-9edc-7e1414f0ac00.png">
<img width="718" alt="screenshot 2018-06-08 08 59 28" src="https://user-images.githubusercontent.com/12065270/41143655-5926ea5a-6afa-11e8-9323-060f2380e961.png">
<img width="719" alt="screenshot 2018-06-08 08 59 55" src="https://user-images.githubusercontent.com/12065270/41143657-59553dec-6afa-11e8-8dde-ba995e528dac.png">

**Comment by cyriltasse** [comment]
Jeez - is that just deconvolution? Have you recalibrated?

**Comment by cyriltasse** [comment]
I'm very surprised - you're sure something's not messed up with the solution files?

**Comment by twshimwell** [comment]
OK, im thinking its the imaging_weights. I therefore need to redo all the image_phase calibration to get the same imaging weights as previously.

**Comment by twshimwell** [comment]
With Cyrils new improvements to the amplitude smoothing it seems many bad facets can be fixed. For now lets not bother fiddling with covq again.
