### ISSUE TITLE
Archiving script

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#73]
For processing on SARA we will probably need to stop the job half way through and then resubmit it to finish it off. This is because we have a 3 day job limit.

I thought maybe in the archiving script we could have an option to keep intermediate products needed to resume the job. This will save us time tarring up files we dont need to store to resume the processing.

**Comment by twshimwell** [comment]
Also need to decide what to keep as the final products. Maybe:

SOLSDIR, final images, models, residuals and masks (full_low_m and image_full_ampphase1_di_m.NS)

It would be nice to also keep the data... I guess this is going to be close to 500GB. This would mean that if we process all existing data then we get 300TB which is far more than we have free here in Leiden.

The alternative is to delete the data but for some studies (in the clusters group we will want to do this) reimaging, source subtraction and other things will be needed.

**Comment by twshimwell** [comment]
Oh maybe the bootstrap files too.

**Comment by cyriltasse** [comment]
LET'S EDIT THIS POST.

I'd say
- image_full_ampphase_di_m.NS (+.app.restored.fits, .DicoModel, .tessel.reg, .mask<last>.fits)
- same for the low-res image
- same for the UQ cubes, and V image
- image_dirin_SSD_m.npy.ClusterCat.npy
- Bootstrapping products
- SOLSDIR

**Comment by mhardcastle** [comment]
We don't need to store the data so long as we can re-apply solutions when we need to.

**Comment by twshimwell** [comment]
yeh but we need the IMAGING_WEIGHTS and DATA_DI_CORRECTED

**Comment by mhardcastle** [comment]
DATA_DI_CORRECTED can be regenerated from the solutions, no?

IMAGING_WEIGHTS I agree....

**Comment by twshimwell** [comment]
ok seems like we dont need to store the 300TB then.

**Comment by twshimwell** [comment]
if IMAGING_WEIGHTS are kept as npy arrays then it will also help with the "restart from" functionality.

**Comment by cyriltasse** [comment]
ok - kMS now saving the weights...

**Comment by twshimwell** [comment]
How big are the final products? I wonder if we could upload them to the distrib area instead of leiden. Do you get faster and more reliable speeds to that when downloading the prefactor products?

**Comment by mhardcastle** [comment]
Final products are about 350 GB, I estimate, of which the QU low-res cube is 266 GB.

It's more reliable downloading from SARA than doing these uploads mostly because the connection doesn't flake out every few minutes -- think it's an issue with the ssh connection. At the moment it's going to take longer to upload than download. The data volumes are not all that dissimilar in the two directions.

**Comment by mhardcastle** [comment]
In the meantime I've pushed the upload.py script and lots of associated changes to master. The way this works at Herts is that monitor.py runs constantly and downloads or uploads data as needed. It may be possible to modify this for Leiden though I don't think you have the job queueing system that it relies on for starting jobs.

Tim, perhaps you can check that what's landing in the archive directory is what you want (and that it's usable -- e.g. run ds9 on some of the big fits images). I have had to disable some of the safety features of rsync to get this to work well.

**Comment by twshimwell** [comment]
One thing we dont have is any of the smoothed solutions because these are not put into SOLSDIR (its just links in SOLSDIR). We should probably keep the smoothed solutions.

**Comment by mhardcastle** [comment]
OK, all of them? So DDS*smoothed*.npz?

**Comment by twshimwell** [comment]
Yeh I guess if we want these archived products to allow someone to remake the DD calibrated images from prefactor products then we need to keep all of them i think.

**Comment by mhardcastle** [comment]
OK, this is done and pushed and the existing archive datasets have been updated.

**Comment by mhardcastle** [comment]
So I'm getting a consistent upload speed to Leiden of 14 MB/s when the connection isn''t flaky. So that would be about 7 hours a dataset. That's just about fast enough to keep up with the rate we're processing them. So probably OK. Would still be better going to a dedicated host at the Leiden end or to SARA, where I can saturate the network connection now.

**Comment by mhardcastle** [comment]
Seems to be working, closing this.
