### ISSUE TITLE
DR2 config file

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#76]
We should (carefully!) update the config file in `examples/tier1.cfg`, and/or the parset defaults, to reflect what we intend to do for DR2 (enabling bootstrap, offset finding, spectral images, dynspecms, polarization etc) and test it all the way through on a few fields. Might be nice if these included known time-variable and polarized sources (can dynspecms detect the known pulsar in HETDEX, @cyriltasse ?).

**Comment by twshimwell** [comment]
The 2 pulsars in HETDEX are 

B1112+50 is 168.91, 50.5034 
J1518+4904 is 229.569583, 49.07616667

These are fields L229625 and L261311

**Comment by mhardcastle** [comment]
Great, well as I have been doing L229625 for other reasons as my test field we should be able to test dynspecms. The pulsar looks about 20 mJy apparent flux, can we see that?

(Is the thing to the N of it a PWN?)

**Comment by twshimwell** [comment]
EDIT THIS POST TO UPDATE DR2 PROCESSING PARAMETERS

[machine]
NCPU_DDF=32
NCPU_killms=32

[data]
mslist=mslist.txt
full_mslist=big-mslist.txt

[image]
imsize=20000
robust=-0.15
psf_arcsec=12.0
final_robust=-0.5
final_psf_arcsec=6.0
do_decorr=True
low_imsize = 6000
low_psf_arcsec = 20
low_robust = -0.25
final_rmsfactor=1.0

[control]
restart=True
bootstrap= True
polcubes=True
stokesv=True

[masking]
tgss=$$/TGSSADR1_7sigma_catalog.fits
extended_size=2000
thresholds=[15,5,5,5]
rmsfacet = True

[bootstrap]
catalogues=['$$/VLSS.fits.txt','$$/wenss.fits.txt']
names=['VLSS','WENSS']
radii=[40,10]
frequencies=[74e6,327e6]

[solutions]
ndir=45
uvmin=.1
normalize=['None','None','None']
NIterKF=[6, 6, 6, 6, 6, 6, 6]
dt_slow=1.
dt_fast=0.5
dt_di=0.2
NChanSols_di=10

[spectra]
do_dynspec=True

**Comment by mhardcastle** [comment]
I've added the offsets section to this.

I have been using NChanSols_di=1 in recent runs. Any thoughts on this?

**Comment by mhardcastle** [comment]
(to add to the confusion the parset default is 2... maybe 10 is more appropriate for 3C fields?)

**Comment by twshimwell** [comment]
That parameter i dont think is actually used anymore...

Instead give_dt_dnu overwrites it for di calibration i thought.

**Comment by cyriltasse** [comment]
I think it's not used anymore in the pipeline script - is it?

**Comment by twshimwell** [comment]
its still passed around in the pipeline but not actually used. In our DDFacet/kMS calls we are pretty bad are just adding things to the end of the line . So in the kMS DI calls there is -NChanSols = o['NChanSols_di'] in addition to -NChanSols = the value from give_dt_dnu.

**Comment by mhardcastle** [comment]
Ah right. It is still passed to the killms function and to kMS itself but I guess it is overridden by the second NChanSols argument. I will remove it from the parset and sort out the duplicate option.

**Comment by mhardcastle** [comment]
... pushed. So there is a tier1-jul2018.cfg file in the examples dir.

**Comment by mhardcastle** [comment]
My removal of NChanSols_di broke the killms call, fixed in the most recent push.

**Comment by mhardcastle** [comment]
Added the spectral imaging, which we forgot.

**Comment by mhardcastle** [comment]
we're happy...
