### ISSUE TITLE
DR2 coordination

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#79]
Discussed on telecon this morning. I think I'd like to do this with a proper database (e.g. mysql back end running at Herts) and hooks in the pipeline that can keep it updated with things like status, success/failure, data location. Could be a lot more flexible in the long run and only requires an ssh tunnel to allow it to be used remotely. I will put some scripts together to handle this unless you feel strongly you'd rather do it your way @twshimwell .

**Comment by twshimwell** [comment]
This solution sounds far better than what I had suggested so very happy with it :)

**Comment by mhardcastle** [comment]
Yeah I forgot about #53, oh well.

So in detail here's what I think we want to do. We have a database of pointings, the index key is the pointing ID. Each pointing has a status. We update this (1) when a pointing is first downloaded from SARA (2) when a job is submitted to process it (maybe only relevant to Herts) (3) when ddf-pipeline starts to run (4) when ddf-pipeline finishes (differentiating success and failure) and (5) when the archiving script runs to store to Leiden. We also store information about the RA, DEC, name of the field, the name of the user who's processing it, the cluster it's running on, the node doing the processing, and the location on disk of the data prior to archiving. We can then add a bunch of fields to the database with status 'not started' and maybe a priority, and a script can atomically pick one to work on whenever there's spare capacity. We can easily export this database as a web page so we can get an at a glance view of the processing status and we can probably do some nice visualization from the database too.

**Comment by cyriltasse** [comment]
Sounds really cool and fancy... Looking forward...

**Comment by cyriltasse** [comment]
I should say I can't help with this, I have zero skill in sql...

**Comment by cyriltasse** [comment]
Maybe Alex has ideas too, on how to interface it etc?

**Comment by mhardcastle** [comment]
This is well within my coding capabilities fortunately! (I've been doing web database programming for some of the other parts of my job for years.)

I forgot to add: all of this should work without breaking the stand-alone capabilities of the pipeline for people who aren't doing surveys processing. So probably I'll develop it as a bunch of wrapper scripts around things we already have.

**Comment by twshimwell** [comment]
Thats really nice. I too have zero sql skill. A priority would certainly be handy as we always get requests for fields to process. 

In the future would be great to link this in with the surfsara/juelich/poznan stuff too and update the same database. But I guess once this code is created and the database is online then we can also try to update the the files from the grid processing side of things.

For the grid processing we presently use a file that contains a line like the below so it might be nice to build upon something like this (although ofcourse we can change our line format but should keep many of the entries).

JD,260803,2457073.8409722224,8,2.00278016,243,260799,2457073.8333333335,8,2.00278016,244,P223_52,CS013HBA*

(status, field id, field date, field num of chans, field integration period, field subbands, cali id, cal data, cal num of chans, cal interation period, cal subbands, field id, antennas to flag)

We then simply update the first column to indicate different stages of the processing and whether or not its processed. We dont have anything sql based so what you are proposing is much more advanced.

**Comment by twshimwell** [comment]
oh and also the parset that is executed

**Comment by mhardcastle** [comment]
Yeah, could do that. It's written to the summary.txt file at the moment when ddf-pipeline finishes, but could be dumped in the database as well.

**Comment by mhardcastle** [comment]
I've pushed some start code for this to the current dev branch -- so far only added to the download script.

It introduces a dependency on the python packages sshtunnel and mysql-python.

**Comment by mhardcastle** [comment]
(Tested at Herts, Leiden.)

**Comment by mhardcastle** [comment]
OK, all the scripts are instrumented with this now.
