### ISSUE TITLE
region file for make_extended_mask

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#80]
If rmsfacet=True (which we have in the current DR2 setup) then in make_extended_mask the region file 'image_dirin_DDS.tessel.reg' is used. Shouldnt we instead use one of the region files that contains the facets we are using for calibration?

(I noticed this because for some reason the assign_labels_to_poly "Failed to locate a label" at the make_extended_mask step for one of my runs).

**Comment by mhardcastle** [comment]
Yep, this is a result of Cyril's changes to the clustering. Fixed in baf1f3002858558a322d974acdafe90e1776f85c
