### ISSUE TITLE
clustering in DR2

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#84]
I think previously we managed to show that the phase errors in DR2 and DR1 are very similar if we use the same clustering. However looking at the products I have from DR2 and DR1 runs so far it seems that DR2 has much larger facets in the central region and larger phase errors in this region too. See attached where left is DR2 and right is DR1 facets.

Should we move back to the old clustering scheme?
<img width="714" alt="screen shot 2018-07-20 at 10 02 32" src="https://user-images.githubusercontent.com/12065270/42990817-173a3b8a-8c04-11e8-8575-1521d26cdc67.png">

**Comment by cyriltasse** [comment]
The old clustering has many flaws, like cutting extended emission apart. I can make the new clustering to make a more compact facetting if really needed...

**Comment by rvweeren** [comment]
I noticed the same as what Tim reported. DR1 clustering looks better in terms of 'phase' errors around bright sources in the center of the FoV.

**Comment by twshimwell** [comment]
Looks much closer to the older scheme now. Perhaps still a little bit bigger facets though (left DR2 and right DR1 of one of the HETDEX fields). Worth making a little more compact still?

<img width="718" alt="screenshot 2018-08-01 13 31 31" src="https://user-images.githubusercontent.com/12065270/43519429-b8d7137a-958f-11e8-8a44-8a4c016def86.png">

**Comment by cyriltasse** [comment]
I can't easilly make it more compact...
