### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#85]
I'm seeing much worse performance on my new nodes (32 cores of Xeon Gold 6130) vs old nodes (32 cores of E5-2697A v4 or  E5-2698 v3). Every timed step seems to be a factor 2-3 slower on the new nodes.

I've tried building DDF and kMS on the new nodes -- no difference. numpy speed tests say they're the same. Standard CPU benchmarks say they're the same or put the 6130s ahead.

I'm going to free up some nodes to do some benchmarking and also try building new versions of numpy and numexpr, but if anyone has any brilliant ideas in the meantime I'd love to hear them.

**Comment by cyriltasse** [comment]
Are you swapping?

**Comment by mhardcastle** [comment]
I don't think so. The new machines only have 192 GB, so memory's a possible issue, but they seem slower even in steps that don't use much RAM,.

**Comment by mhardcastle** [comment]
Some of the nodes (including all the ones I'd reserved for LOFAR work) had decided to switch into a low-power state where the CPUs were all clocked at 1 GHz. Hey ho, at least it's easily fixable with a reboot and some messing with the bios.

**Comment by cyriltasse** [comment]
I love self-solved issues....
