### ISSUE TITLE
Crash on NCP - Failed to locate a label

### ISSUE THREAD

**Issue by tikk3r** [mhardcastle/ddf-pipeline#88]
While trying to image an NCP dataset from the EoR observations, the pipeline crashes when it starts with the `image_full_low_im` images. The error message is `RuntimeError: Failed to locate a label! (F15_S12)` (here's a gist with a bigger snippet of the error message: https://gist.github.com/tikk3r/807e2b4ce5467e30ca2aecaec75a536b). I am running the latest version in Leiden.
Per @twshimwell 's suggestions I have tried increasing the low resolution image size, but it still crashes (I tried 6500 and 7000). It is the `make_extended_mask.py` script that fails.
Could it have to do with the NCP itself, e.g. coordinates?

Cheers,

Frits

**Comment by mhardcastle** [comment]
I think it's entirely possible that this is a co-ordinate issue, I'm afraid. That label-finding code was never all that robust. If you can point me to your directory on the Leiden systems to give me a test image to work with I can take a look at fixing it when I am back from vacation next week.

**Comment by tikk3r** [comment]
> If you can point me to your directory on the Leiden systems to give me a test image to work with I can take a look at fixing it when I am back from vacation next week.

Of course, all pipeline output is in this directory: `/net/para11/data2/sweijen/EoR/NCP/L258431/killms`.
