### ISSUE TITLE
New C dependencies for MySQL Python modules

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/ddf-pipeline#91]
The use of MySQLdb discussed in #79 introduces a new C library requirement (see https://stackoverflow.com/questions/43102442/whats-the-difference-between-mysqldb-mysqlclient-and-mysql-connector-python) and makes it more difficult to install the pipeline dependencies for those that do not administer their clusters.

There are two pure Python alternatives that would solve this problem. The [_mysql-connector-python_](https://dev.mysql.com/doc/connector-python/en/) is the official library but the API is probably different (I have not checked yet). There is also [_pymysql_](https://pymysql.readthedocs.io/en/latest/index.html) that has a similar API to MySQLdb and I think it can be used as a direct replacement (the imports work OK but I have not tested the functionality). Given that the performance should not be critical. Could we consider using a pure Python MySQL library like _pymysql_ ?

**Comment by mhardcastle** [comment]
@nudomarinero further suggests by e-mail that pymysql works, but of course unless run in tier 1 production mode no mysql code is actually run. We need to test this with the existing database code to make sure it works in production.
