### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#96]
Hi,

I tried to install this according to the instruction in the manual.md file.
But when I arrive at git checkout DR1, it says 

> fatal: Not a git repository (or any of the parent directories): .git

If I continue with the installation, it does a couple of things, and when cloning DDFacet, it asks me for a username and a password. I gave it mine, but then it complains that my branch is on the level as origin/master, followed by setup.py not found.

Am I missing something crucial in the installation?
Thx.

**Comment by amisk** [comment]
Nevermind, I had to cd into ddf-pipeline.

But now it stops at 
> changing mode of build/scripts-2.7/DDF.py from 664 to 775
changing mode of build/scripts-2.7/CleanSHM.py from 664 to 775
changing mode of build/scripts-2.7/MemMonitor.py from 664 to 775
changing mode of build/scripts-2.7/Restore.py from 664 to 775
changing mode of build/scripts-2.7/SelfCal.py from 664 to 775
sed: kann ddf-pipeline/misc/DDF.sh nicht lesen: Datei oder Verzeichnis nicht gefunden

The last line means that this file is not found.

**Comment by amisk** [comment]
Never mind again. Started in the wrong directory.

**Comment by mhardcastle** [comment]
I've fixed the mistake in the instructions in 8aa2864 .

**Comment by mhardcastle** [comment]
Also note that by running the DR1 pipeline you're missing out on a bunch of improvements in DR2. You might want to talk to @twshimwell  about getting access to the private versions of DDFacet and kMS needed for DR2.

**Comment by amisk** [comment]
I know. First I only wanted to see if it works for my data which I was never be able run through factor, and then checkout DR2.
Thx.
