### ISSUE TITLE
No module named DDFacet.Array

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#98]
Hey,

Just wanted to start this for the first time and I get the error that DDFacet.Array is not found.
If I go into ipython or python interactive shell, I can not import DDFacet, although everything relevant is in $PATH and $PYTHONPATH.

However, I noticed that I can import DDFacet if I run the python3 interactive shell.
Is python 3 necessary? If so, I can I make sure that DDFacet uses 3 instead of 2.7?
And if not, why is it unable to import DDFacet?

This is the complete error message
```
Welcome to ddf-pipeline, version v1.4.1-17-g0587ef1
Running: CleanSHM.py
Traceback (most recent call last):
  File "/home/amisk/programme/DDF/DDFacet/build/scripts-2.7/CleanSHM.py", line 23, in <module>
    from DDFacet.Array import NpShared
ImportError: No module named DDFacet.Array
Traceback (most recent call last):
  File "/home/amisk/programme/DDF/DDFacet/build/scripts-2.7/CleanSHM.py", line 23, in <module>
    from DDFacet.Array import NpShared
ImportError: No module named DDFacet.Array
FAILED to run CleanSHM.py: return value is 1
Traceback (most recent call last):
  File "/home/amisk/programme/DDF/ddf-pipeline/scripts/pipeline.py", line 419, in <module>
    run('CleanSHM.py',dryrun=o['dryrun'])    
  File "/home/amisk/programme/DDF/ddf-pipeline/utils/auxcodes.py", line 45, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/home/amisk/programme/DDF/ddf-pipeline/utils/auxcodes.py", line 27, in die
    raise Exception(s)
Exception: FAILED to run CleanSHM.py: return value is 1

```

Also, if look at sys.path, in both python2.7 and 3 the same DDF paths are present.

**Comment by mhardcastle** [comment]
The pipeline is python2 at the moment, python3 will definitely not help here!

Check your pythonpath carefully: if ROOT is your root directory, then it should include ROOT, ROOT/DDFacet, and ROOT/DDFacet/DDFacet .

**Comment by amisk** [comment]
Ok. It apparently runs now.

Altough I just saw that I had to install the Polygon2 package instead of Polygon.

**Comment by mhardcastle** [comment]
OK, yeah, the path in the install script doesn't appear to use the path setup that DDFacet now uses. This is a bug but there is not a lot of point fixing it till we have a public release of a DDFacet/killMS that works with master. I will keep this open as a reminder.

**Comment by twshimwell** [comment]
This one fixed Arpad?

**Comment by twshimwell** [comment]
Also is this issue still relevant @amisk?

**Comment by amisk** [comment]
Nope. I forgot to add a path.
